/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Header for class java/lang/IllegalArgumentException */

#ifndef _java_lang_IllegalArgumentException_H_
#define _java_lang_IllegalArgumentException_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct java_lang_String;
struct java_lang_Class;

/*******************************************************************************
 * Class java/lang/IllegalArgumentException
 ******************************************************************************/

typedef struct java_lang_IllegalArgumentException java_lang_IllegalArgumentException;

#define classname_java_lang_IllegalArgumentException	"java/lang/IllegalArgumentException"

#define class_java_lang_IllegalArgumentException(env) \
	((struct java_lang_Class*)JRI_FindClass(env, classname_java_lang_IllegalArgumentException))

/*******************************************************************************
 * Public Methods
 ******************************************************************************/

#ifdef DEBUG

/*** public <init> ()V ***/
extern JRI_PUBLIC_API(struct java_lang_IllegalArgumentException*)
java_lang_IllegalArgumentException_new(JRIEnv* env, struct java_lang_Class* clazz);

/*** public <init> (Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(struct java_lang_IllegalArgumentException*)
java_lang_IllegalArgumentException_new_1(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a);

#else /* !DEBUG */

/*** public <init> ()V ***/
#define java_lang_IllegalArgumentException_new(env, clazz)	\
	((struct java_lang_IllegalArgumentException*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_IllegalArgumentException_new))

/*** public <init> (Ljava/lang/String;)V ***/
#define java_lang_IllegalArgumentException_new_1(env, clazz, a)	\
	((struct java_lang_IllegalArgumentException*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_IllegalArgumentException_new_1, a))

#endif /* !DEBUG*/

/*** public <init> ()V ***/
extern JRIMethodID FAR methodID_java_lang_IllegalArgumentException_new;
#define name_java_lang_IllegalArgumentException_new	"<init>"
#define sig_java_lang_IllegalArgumentException_new 	"()V"
#define use_java_lang_IllegalArgumentException_new(env, clazz)	\
	(methodID_java_lang_IllegalArgumentException_new =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_lang_IllegalArgumentException_new,	\
			sig_java_lang_IllegalArgumentException_new))
#define unuse_java_lang_IllegalArgumentException_new(env, clazz)	\
	(methodID_java_lang_IllegalArgumentException_new = JRIUninitialized)

/*** public <init> (Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_java_lang_IllegalArgumentException_new_1;
#define name_java_lang_IllegalArgumentException_new_1	"<init>"
#define sig_java_lang_IllegalArgumentException_new_1 	"(Ljava/lang/String;)V"
#define use_java_lang_IllegalArgumentException_new_1(env, clazz)	\
	(methodID_java_lang_IllegalArgumentException_new_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_lang_IllegalArgumentException_new_1,	\
			sig_java_lang_IllegalArgumentException_new_1))
#define unuse_java_lang_IllegalArgumentException_new_1(env, clazz)	\
	(methodID_java_lang_IllegalArgumentException_new_1 = JRIUninitialized)

/*******************************************************************************
 * IMPLEMENTATION SECTION: 
 * Define the IMPLEMENT_java_lang_IllegalArgumentException symbol 
 * if you intend to implement the native methods of this class. This 
 * symbol makes the private and protected methods available. You should 
 * also call the register_java_lang_IllegalArgumentException routine 
 * to make your native methods available.
 ******************************************************************************/

extern JRI_PUBLIC_API(struct java_lang_Class*)
use_java_lang_IllegalArgumentException(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unuse_java_lang_IllegalArgumentException(JRIEnv* env);

extern JRI_PUBLIC_API(struct java_lang_Class*)
register_java_lang_IllegalArgumentException(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unregister_java_lang_IllegalArgumentException(JRIEnv* env);

#ifdef IMPLEMENT_java_lang_IllegalArgumentException

#endif /* IMPLEMENT_java_lang_IllegalArgumentException */

#ifdef __cplusplus
} /* extern "C" */

/*******************************************************************************
 * C++ Definitions
 ******************************************************************************/

#include "java_lang_RuntimeException.h"

struct java_lang_IllegalArgumentException : virtual public java_lang_RuntimeException {

	static struct java_lang_Class* _use(JRIEnv* env) {
		return use_java_lang_IllegalArgumentException(env);
	}

	static void _unuse(JRIEnv* env) {
		unuse_java_lang_IllegalArgumentException(env);
	}

	static struct java_lang_Class* _register(JRIEnv* env) {
		return register_java_lang_IllegalArgumentException(env);
	}

	static void _unregister(JRIEnv* env) {
		unregister_java_lang_IllegalArgumentException(env);
	}

	static struct java_lang_Class* _class(JRIEnv* env) {
		return class_java_lang_IllegalArgumentException(env);
	}

	/* Public Methods */
	/*** public <init> ()V ***/
	static java_lang_IllegalArgumentException* _new(JRIEnv* env, struct java_lang_Class* clazz) {
		return java_lang_IllegalArgumentException_new(env, clazz);
	}

	/*** public <init> (Ljava/lang/String;)V ***/
	static java_lang_IllegalArgumentException* _new(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
		return java_lang_IllegalArgumentException_new_1(env, clazz, a);
	}

#ifdef IMPLEMENT_java_lang_IllegalArgumentException

#endif /* IMPLEMENT_java_lang_IllegalArgumentException */
};

#endif /* __cplusplus */

#endif /* Class java/lang/IllegalArgumentException */
