/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Header for class vrml/external/field/EventIn */

#ifndef _vrml_external_field_EventIn_H_
#define _vrml_external_field_EventIn_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct java_lang_String;
struct vrml_external_Node;
struct vrml_external_field_EventIn;
struct java_lang_Class;

/*******************************************************************************
 * Class vrml/external/field/EventIn
 ******************************************************************************/

typedef struct vrml_external_field_EventIn vrml_external_field_EventIn;

#define classname_vrml_external_field_EventIn	"vrml/external/field/EventIn"

#define class_vrml_external_field_EventIn(env) \
	((struct java_lang_Class*)JRI_FindClass(env, classname_vrml_external_field_EventIn))

/*******************************************************************************
 * Public Methods
 ******************************************************************************/

#ifdef DEBUG

/*** public getType ()I ***/
extern JRI_PUBLIC_API(jint)
vrml_external_field_EventIn_getType(JRIEnv* env, struct vrml_external_field_EventIn* self);

/*** public finalize ()V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_finalize(JRIEnv* env, struct vrml_external_field_EventIn* self);

#else /* !DEBUG */

/*** public getType ()I ***/
#define vrml_external_field_EventIn_getType(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_getType))

/*** public finalize ()V ***/
#define vrml_external_field_EventIn_finalize(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_finalize))

#endif /* !DEBUG*/

/*** public getType ()I ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_getType;
#define name_vrml_external_field_EventIn_getType	"getType"
#define sig_vrml_external_field_EventIn_getType 	"()I"
#define use_vrml_external_field_EventIn_getType(env, clazz)	\
	(methodID_vrml_external_field_EventIn_getType =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_getType,	\
			sig_vrml_external_field_EventIn_getType))
#define unuse_vrml_external_field_EventIn_getType(env, clazz)	\
	(methodID_vrml_external_field_EventIn_getType = JRIUninitialized)

/*** public finalize ()V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_finalize;
#define name_vrml_external_field_EventIn_finalize	"finalize"
#define sig_vrml_external_field_EventIn_finalize 	"()V"
#define use_vrml_external_field_EventIn_finalize(env, clazz)	\
	(methodID_vrml_external_field_EventIn_finalize =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_finalize,	\
			sig_vrml_external_field_EventIn_finalize))
#define unuse_vrml_external_field_EventIn_finalize(env, clazz)	\
	(methodID_vrml_external_field_EventIn_finalize = JRIUninitialized)

/*******************************************************************************
 * IMPLEMENTATION SECTION: 
 * Define the IMPLEMENT_vrml_external_field_EventIn symbol 
 * if you intend to implement the native methods of this class. This 
 * symbol makes the private and protected methods available. You should 
 * also call the register_vrml_external_field_EventIn routine 
 * to make your native methods available.
 ******************************************************************************/

extern JRI_PUBLIC_API(struct java_lang_Class*)
use_vrml_external_field_EventIn(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unuse_vrml_external_field_EventIn(JRIEnv* env);

extern JRI_PUBLIC_API(struct java_lang_Class*)
register_vrml_external_field_EventIn(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unregister_vrml_external_field_EventIn(JRIEnv* env);

#ifdef IMPLEMENT_vrml_external_field_EventIn

/*******************************************************************************
 * Native Methods: 
 * These are the signatures of the native methods which you must implement.
 ******************************************************************************/

/*** protected native setString (I[Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_setString(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jstringArray b);

/*** protected native set1String (ILjava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_set1String(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, struct java_lang_String *b);

/*** protected native setNode (I[Lvrml/external/Node;)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_setNode(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jobjectArray b);

/*** protected native set1Node (ILvrml/external/Node;)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_set1Node(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, struct vrml_external_Node *b);

/*** protected native setInt (I[I)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_setInt(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jintArray b);

/*** protected native set1Int (II)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_set1Int(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jint b);

/*** protected native setFloat (IF)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_setFloat(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jfloat b);

/*** protected native setFloatArray (I[F)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_setFloatArray(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jfloatArray b);

/*** protected native set1Float (I[F)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_set1Float(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jfloatArray b);

/*** protected native setTime (D)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_setTime(JRIEnv* env, struct vrml_external_field_EventIn* self, jdouble a);

/*** protected native setBoolean (Z)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_setBoolean(JRIEnv* env, struct vrml_external_field_EventIn* self, jbool a);

/*** protected native setImage (IIII[B)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_setImage(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jint b, jint c, jint d, jbyteArray e);

/*** private native nFinalize ()V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventIn_nFinalize(JRIEnv* env, struct vrml_external_field_EventIn* self);

/*******************************************************************************
 * Implementation Field Accessors: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** private cBrowser I ***/
extern JRI_PUBLIC_API(jint)
get_vrml_external_field_EventIn_cBrowser(JRIEnv* env, vrml_external_field_EventIn* obj);
extern JRI_PUBLIC_API(void)
set_vrml_external_field_EventIn_cBrowser(JRIEnv* env, vrml_external_field_EventIn* obj, jint v);

/*** private cEvent I ***/
extern JRI_PUBLIC_API(jint)
get_vrml_external_field_EventIn_cEvent(JRIEnv* env, vrml_external_field_EventIn* obj);
extern JRI_PUBLIC_API(void)
set_vrml_external_field_EventIn_cEvent(JRIEnv* env, vrml_external_field_EventIn* obj, jint v);

/*** private type I ***/
extern JRI_PUBLIC_API(jint)
get_vrml_external_field_EventIn_type(JRIEnv* env, vrml_external_field_EventIn* obj);
extern JRI_PUBLIC_API(void)
set_vrml_external_field_EventIn_type(JRIEnv* env, vrml_external_field_EventIn* obj, jint v);

#else /* !DEBUG */

/*** private cBrowser I ***/
#define get_vrml_external_field_EventIn_cBrowser(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_cBrowser))
#define set_vrml_external_field_EventIn_cBrowser(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_cBrowser, v)

/*** private cEvent I ***/
#define get_vrml_external_field_EventIn_cEvent(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_cEvent))
#define set_vrml_external_field_EventIn_cEvent(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_cEvent, v)

/*** private type I ***/
#define get_vrml_external_field_EventIn_type(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_type))
#define set_vrml_external_field_EventIn_type(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_type, v)

#endif /* !DEBUG*/

extern JRIFieldID FAR fieldID_vrml_external_field_EventIn_cBrowser;
#define name_vrml_external_field_EventIn_cBrowser	"cBrowser"
#define sig_vrml_external_field_EventIn_cBrowser 	"I"
#define use_vrml_external_field_EventIn_cBrowser(env, clazz)	\
	(fieldID_vrml_external_field_EventIn_cBrowser =	\
		JRI_GetFieldID(env, clazz,	\
			name_vrml_external_field_EventIn_cBrowser,	\
			sig_vrml_external_field_EventIn_cBrowser))
#define unuse_vrml_external_field_EventIn_cBrowser(env, clazz)	\
		(fieldID_vrml_external_field_EventIn_cBrowser = JRIUninitialized)

extern JRIFieldID FAR fieldID_vrml_external_field_EventIn_cEvent;
#define name_vrml_external_field_EventIn_cEvent	"cEvent"
#define sig_vrml_external_field_EventIn_cEvent 	"I"
#define use_vrml_external_field_EventIn_cEvent(env, clazz)	\
	(fieldID_vrml_external_field_EventIn_cEvent =	\
		JRI_GetFieldID(env, clazz,	\
			name_vrml_external_field_EventIn_cEvent,	\
			sig_vrml_external_field_EventIn_cEvent))
#define unuse_vrml_external_field_EventIn_cEvent(env, clazz)	\
		(fieldID_vrml_external_field_EventIn_cEvent = JRIUninitialized)

extern JRIFieldID FAR fieldID_vrml_external_field_EventIn_type;
#define name_vrml_external_field_EventIn_type	"type"
#define sig_vrml_external_field_EventIn_type 	"I"
#define use_vrml_external_field_EventIn_type(env, clazz)	\
	(fieldID_vrml_external_field_EventIn_type =	\
		JRI_GetFieldID(env, clazz,	\
			name_vrml_external_field_EventIn_type,	\
			sig_vrml_external_field_EventIn_type))
#define unuse_vrml_external_field_EventIn_type(env, clazz)	\
		(fieldID_vrml_external_field_EventIn_type = JRIUninitialized)

/*******************************************************************************
 * Implementation Methods: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** protected <init> (III)V ***/
extern JRI_PUBLIC_API(struct vrml_external_field_EventIn*)
vrml_external_field_EventIn_new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c);

/*** protected native setString (I[Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setString(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jstringArray b);

/*** protected native set1String (ILjava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_set1String(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, struct java_lang_String *b);

/*** protected native setNode (I[Lvrml/external/Node;)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setNode(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jobjectArray b);

/*** protected native set1Node (ILvrml/external/Node;)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_set1Node(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, struct vrml_external_Node *b);

/*** protected native setInt (I[I)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setInt(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jintArray b);

/*** protected native set1Int (II)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_set1Int(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jint b);

/*** protected native setFloat (IF)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setFloat(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jfloat b);

/*** protected native setFloatArray (I[F)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setFloatArray(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jfloatArray b);

/*** protected native set1Float (I[F)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_set1Float(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jfloatArray b);

/*** protected native setTime (D)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setTime(JRIEnv* env, struct vrml_external_field_EventIn* self, jdouble a);

/*** protected native setBoolean (Z)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setBoolean(JRIEnv* env, struct vrml_external_field_EventIn* self, jbool a);

/*** protected native setImage (IIII[B)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setImage(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jint b, jint c, jint d, jbyteArray e);

/*** protected static newEventIn (III)Lvrml/external/field/EventIn; ***/
extern JRI_PUBLIC_API(struct vrml_external_field_EventIn *)
vrml_external_field_EventIn_newEventIn(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c);

/*** private native nFinalize ()V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventIn_nFinalize(JRIEnv* env, struct vrml_external_field_EventIn* self);

#else /* !DEBUG */

/*** protected <init> (III)V ***/
#define vrml_external_field_EventIn_new(env, clazz, a, b, c)	\
	((struct vrml_external_field_EventIn*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_vrml_external_field_EventIn_new, a, b, c))

/*** protected native setString (I[Ljava/lang/String;)V ***/
#define vrml_external_field_EventIn_setString(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_setString, a, b))

/*** protected native set1String (ILjava/lang/String;)V ***/
#define vrml_external_field_EventIn_set1String(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_set1String, a, b))

/*** protected native setNode (I[Lvrml/external/Node;)V ***/
#define vrml_external_field_EventIn_setNode(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_setNode, a, b))

/*** protected native set1Node (ILvrml/external/Node;)V ***/
#define vrml_external_field_EventIn_set1Node(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_set1Node, a, b))

/*** protected native setInt (I[I)V ***/
#define vrml_external_field_EventIn_setInt(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_setInt, a, b))

/*** protected native set1Int (II)V ***/
#define vrml_external_field_EventIn_set1Int(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_set1Int, a, b))

/*** protected native setFloat (IF)V ***/
#define vrml_external_field_EventIn_setFloat(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_setFloat, a, b))

/*** protected native setFloatArray (I[F)V ***/
#define vrml_external_field_EventIn_setFloatArray(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_setFloatArray, a, b))

/*** protected native set1Float (I[F)V ***/
#define vrml_external_field_EventIn_set1Float(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_set1Float, a, b))

/*** protected native setTime (D)V ***/
#define vrml_external_field_EventIn_setTime(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_setTime, a))

/*** protected native setBoolean (Z)V ***/
#define vrml_external_field_EventIn_setBoolean(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_setBoolean, a))

/*** protected native setImage (IIII[B)V ***/
#define vrml_external_field_EventIn_setImage(env, obj, a, b, c, d, e) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_setImage, a, b, c, d, e))

/*** protected static newEventIn (III)Lvrml/external/field/EventIn; ***/
#define vrml_external_field_EventIn_newEventIn(env, clazz, a, b, c) \
	((struct vrml_external_field_EventIn *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_vrml_external_field_EventIn_newEventIn, a, b, c))

/*** private native nFinalize ()V ***/
#define vrml_external_field_EventIn_nFinalize(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventIn_nFinalize))

#endif /* !DEBUG*/

/*** protected <init> (III)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_new;
#define name_vrml_external_field_EventIn_new	"<init>"
#define sig_vrml_external_field_EventIn_new 	"(III)V"
#define use_vrml_external_field_EventIn_new(env, clazz)	\
	(methodID_vrml_external_field_EventIn_new =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_new,	\
			sig_vrml_external_field_EventIn_new))
#define unuse_vrml_external_field_EventIn_new(env, clazz)	\
	(methodID_vrml_external_field_EventIn_new = JRIUninitialized)

/*** protected native setString (I[Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_setString;
#define name_vrml_external_field_EventIn_setString	"setString"
#define sig_vrml_external_field_EventIn_setString 	"(I[Ljava/lang/String;)V"
#define use_vrml_external_field_EventIn_setString(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setString =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_setString,	\
			sig_vrml_external_field_EventIn_setString))
#define unuse_vrml_external_field_EventIn_setString(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setString = JRIUninitialized)

/*** protected native set1String (ILjava/lang/String;)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_set1String;
#define name_vrml_external_field_EventIn_set1String	"set1String"
#define sig_vrml_external_field_EventIn_set1String 	"(ILjava/lang/String;)V"
#define use_vrml_external_field_EventIn_set1String(env, clazz)	\
	(methodID_vrml_external_field_EventIn_set1String =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_set1String,	\
			sig_vrml_external_field_EventIn_set1String))
#define unuse_vrml_external_field_EventIn_set1String(env, clazz)	\
	(methodID_vrml_external_field_EventIn_set1String = JRIUninitialized)

/*** protected native setNode (I[Lvrml/external/Node;)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_setNode;
#define name_vrml_external_field_EventIn_setNode	"setNode"
#define sig_vrml_external_field_EventIn_setNode 	"(I[Lvrml/external/Node;)V"
#define use_vrml_external_field_EventIn_setNode(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setNode =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_setNode,	\
			sig_vrml_external_field_EventIn_setNode))
#define unuse_vrml_external_field_EventIn_setNode(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setNode = JRIUninitialized)

/*** protected native set1Node (ILvrml/external/Node;)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_set1Node;
#define name_vrml_external_field_EventIn_set1Node	"set1Node"
#define sig_vrml_external_field_EventIn_set1Node 	"(ILvrml/external/Node;)V"
#define use_vrml_external_field_EventIn_set1Node(env, clazz)	\
	(methodID_vrml_external_field_EventIn_set1Node =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_set1Node,	\
			sig_vrml_external_field_EventIn_set1Node))
#define unuse_vrml_external_field_EventIn_set1Node(env, clazz)	\
	(methodID_vrml_external_field_EventIn_set1Node = JRIUninitialized)

/*** protected native setInt (I[I)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_setInt;
#define name_vrml_external_field_EventIn_setInt	"setInt"
#define sig_vrml_external_field_EventIn_setInt 	"(I[I)V"
#define use_vrml_external_field_EventIn_setInt(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setInt =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_setInt,	\
			sig_vrml_external_field_EventIn_setInt))
#define unuse_vrml_external_field_EventIn_setInt(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setInt = JRIUninitialized)

/*** protected native set1Int (II)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_set1Int;
#define name_vrml_external_field_EventIn_set1Int	"set1Int"
#define sig_vrml_external_field_EventIn_set1Int 	"(II)V"
#define use_vrml_external_field_EventIn_set1Int(env, clazz)	\
	(methodID_vrml_external_field_EventIn_set1Int =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_set1Int,	\
			sig_vrml_external_field_EventIn_set1Int))
#define unuse_vrml_external_field_EventIn_set1Int(env, clazz)	\
	(methodID_vrml_external_field_EventIn_set1Int = JRIUninitialized)

/*** protected native setFloat (IF)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_setFloat;
#define name_vrml_external_field_EventIn_setFloat	"setFloat"
#define sig_vrml_external_field_EventIn_setFloat 	"(IF)V"
#define use_vrml_external_field_EventIn_setFloat(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setFloat =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_setFloat,	\
			sig_vrml_external_field_EventIn_setFloat))
#define unuse_vrml_external_field_EventIn_setFloat(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setFloat = JRIUninitialized)

/*** protected native setFloatArray (I[F)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_setFloatArray;
#define name_vrml_external_field_EventIn_setFloatArray	"setFloatArray"
#define sig_vrml_external_field_EventIn_setFloatArray 	"(I[F)V"
#define use_vrml_external_field_EventIn_setFloatArray(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setFloatArray =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_setFloatArray,	\
			sig_vrml_external_field_EventIn_setFloatArray))
#define unuse_vrml_external_field_EventIn_setFloatArray(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setFloatArray = JRIUninitialized)

/*** protected native set1Float (I[F)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_set1Float;
#define name_vrml_external_field_EventIn_set1Float	"set1Float"
#define sig_vrml_external_field_EventIn_set1Float 	"(I[F)V"
#define use_vrml_external_field_EventIn_set1Float(env, clazz)	\
	(methodID_vrml_external_field_EventIn_set1Float =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_set1Float,	\
			sig_vrml_external_field_EventIn_set1Float))
#define unuse_vrml_external_field_EventIn_set1Float(env, clazz)	\
	(methodID_vrml_external_field_EventIn_set1Float = JRIUninitialized)

/*** protected native setTime (D)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_setTime;
#define name_vrml_external_field_EventIn_setTime	"setTime"
#define sig_vrml_external_field_EventIn_setTime 	"(D)V"
#define use_vrml_external_field_EventIn_setTime(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setTime =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_setTime,	\
			sig_vrml_external_field_EventIn_setTime))
#define unuse_vrml_external_field_EventIn_setTime(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setTime = JRIUninitialized)

/*** protected native setBoolean (Z)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_setBoolean;
#define name_vrml_external_field_EventIn_setBoolean	"setBoolean"
#define sig_vrml_external_field_EventIn_setBoolean 	"(Z)V"
#define use_vrml_external_field_EventIn_setBoolean(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setBoolean =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_setBoolean,	\
			sig_vrml_external_field_EventIn_setBoolean))
#define unuse_vrml_external_field_EventIn_setBoolean(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setBoolean = JRIUninitialized)

/*** protected native setImage (IIII[B)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_setImage;
#define name_vrml_external_field_EventIn_setImage	"setImage"
#define sig_vrml_external_field_EventIn_setImage 	"(IIII[B)V"
#define use_vrml_external_field_EventIn_setImage(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setImage =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_setImage,	\
			sig_vrml_external_field_EventIn_setImage))
#define unuse_vrml_external_field_EventIn_setImage(env, clazz)	\
	(methodID_vrml_external_field_EventIn_setImage = JRIUninitialized)

/*** protected static newEventIn (III)Lvrml/external/field/EventIn; ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_newEventIn;
#define name_vrml_external_field_EventIn_newEventIn	"newEventIn"
#define sig_vrml_external_field_EventIn_newEventIn 	"(III)Lvrml/external/field/EventIn;"
#define use_vrml_external_field_EventIn_newEventIn(env, clazz)	\
	(methodID_vrml_external_field_EventIn_newEventIn =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_newEventIn,	\
			sig_vrml_external_field_EventIn_newEventIn))
#define unuse_vrml_external_field_EventIn_newEventIn(env, clazz)	\
	(methodID_vrml_external_field_EventIn_newEventIn = JRIUninitialized)

/*** private native nFinalize ()V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventIn_nFinalize;
#define name_vrml_external_field_EventIn_nFinalize	"nFinalize"
#define sig_vrml_external_field_EventIn_nFinalize 	"()V"
#define use_vrml_external_field_EventIn_nFinalize(env, clazz)	\
	(methodID_vrml_external_field_EventIn_nFinalize =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventIn_nFinalize,	\
			sig_vrml_external_field_EventIn_nFinalize))
#define unuse_vrml_external_field_EventIn_nFinalize(env, clazz)	\
	(methodID_vrml_external_field_EventIn_nFinalize = JRIUninitialized)

#endif /* IMPLEMENT_vrml_external_field_EventIn */

#ifdef __cplusplus
} /* extern "C" */

/*******************************************************************************
 * C++ Definitions
 ******************************************************************************/

#include "java_lang_Object.h"

struct vrml_external_field_EventIn : virtual public java_lang_Object {

	static struct java_lang_Class* _use(JRIEnv* env) {
		return use_vrml_external_field_EventIn(env);
	}

	static void _unuse(JRIEnv* env) {
		unuse_vrml_external_field_EventIn(env);
	}

	static struct java_lang_Class* _register(JRIEnv* env) {
		return register_vrml_external_field_EventIn(env);
	}

	static void _unregister(JRIEnv* env) {
		unregister_vrml_external_field_EventIn(env);
	}

	static struct java_lang_Class* _class(JRIEnv* env) {
		return class_vrml_external_field_EventIn(env);
	}

	/* Public Methods */
	/*** public getType ()I ***/
	jint getType(JRIEnv* env) {
		return vrml_external_field_EventIn_getType(env, this);
	}

	/*** public finalize ()V ***/
	void finalize(JRIEnv* env) {
		vrml_external_field_EventIn_finalize(env, this);
	}

#ifdef IMPLEMENT_vrml_external_field_EventIn

	/* Protected Methods */
	/*** protected <init> (III)V ***/
	static vrml_external_field_EventIn* _new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
		return vrml_external_field_EventIn_new(env, clazz, a, b, c);
	}

	/*** protected native setString (I[Ljava/lang/String;)V ***/
	void setString(JRIEnv* env, jint a, jstringArray b) {
		vrml_external_field_EventIn_setString(env, this, a, b);
	}

	/*** protected native set1String (ILjava/lang/String;)V ***/
	void set1String(JRIEnv* env, jint a, struct java_lang_String *b) {
		vrml_external_field_EventIn_set1String(env, this, a, b);
	}

	/*** protected native setNode (I[Lvrml/external/Node;)V ***/
	void setNode(JRIEnv* env, jint a, jobjectArray b) {
		vrml_external_field_EventIn_setNode(env, this, a, b);
	}

	/*** protected native set1Node (ILvrml/external/Node;)V ***/
	void set1Node(JRIEnv* env, jint a, struct vrml_external_Node *b) {
		vrml_external_field_EventIn_set1Node(env, this, a, b);
	}

	/*** protected native setInt (I[I)V ***/
	void setInt(JRIEnv* env, jint a, jintArray b) {
		vrml_external_field_EventIn_setInt(env, this, a, b);
	}

	/*** protected native set1Int (II)V ***/
	void set1Int(JRIEnv* env, jint a, jint b) {
		vrml_external_field_EventIn_set1Int(env, this, a, b);
	}

	/*** protected native setFloat (IF)V ***/
	void setFloat(JRIEnv* env, jint a, jfloat b) {
		vrml_external_field_EventIn_setFloat(env, this, a, b);
	}

	/*** protected native setFloatArray (I[F)V ***/
	void setFloatArray(JRIEnv* env, jint a, jfloatArray b) {
		vrml_external_field_EventIn_setFloatArray(env, this, a, b);
	}

	/*** protected native set1Float (I[F)V ***/
	void set1Float(JRIEnv* env, jint a, jfloatArray b) {
		vrml_external_field_EventIn_set1Float(env, this, a, b);
	}

	/*** protected native setTime (D)V ***/
	void setTime(JRIEnv* env, jdouble a) {
		vrml_external_field_EventIn_setTime(env, this, a);
	}

	/*** protected native setBoolean (Z)V ***/
	void setBoolean(JRIEnv* env, jbool a) {
		vrml_external_field_EventIn_setBoolean(env, this, a);
	}

	/*** protected native setImage (IIII[B)V ***/
	void setImage(JRIEnv* env, jint a, jint b, jint c, jint d, jbyteArray e) {
		vrml_external_field_EventIn_setImage(env, this, a, b, c, d, e);
	}

	/*** protected static newEventIn (III)Lvrml/external/field/EventIn; ***/
	static struct vrml_external_field_EventIn * newEventIn(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
		return vrml_external_field_EventIn_newEventIn(env, clazz, a, b, c);
	}

	/* Private Field Accessors */
	/*** private cBrowser I ***/
	jint cBrowser(JRIEnv* env) {
		return get_vrml_external_field_EventIn_cBrowser(env, this);
	}
	void cBrowser(JRIEnv* env, jint v) {
		set_vrml_external_field_EventIn_cBrowser(env, this, v);
	}

	/*** private cEvent I ***/
	jint cEvent(JRIEnv* env) {
		return get_vrml_external_field_EventIn_cEvent(env, this);
	}
	void cEvent(JRIEnv* env, jint v) {
		set_vrml_external_field_EventIn_cEvent(env, this, v);
	}

	/*** private type I ***/
	jint type(JRIEnv* env) {
		return get_vrml_external_field_EventIn_type(env, this);
	}
	void type(JRIEnv* env, jint v) {
		set_vrml_external_field_EventIn_type(env, this, v);
	}

	/* Private Methods */
	/*** private native nFinalize ()V ***/
	void nFinalize(JRIEnv* env) {
		vrml_external_field_EventIn_nFinalize(env, this);
	}

#endif /* IMPLEMENT_vrml_external_field_EventIn */
};

#endif /* __cplusplus */

#endif /* Class vrml/external/field/EventIn */
