/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Header for class vrml/external/field/EventOut */

#ifndef _vrml_external_field_EventOut_H_
#define _vrml_external_field_EventOut_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct java_lang_Object;
struct vrml_external_field_EventOutObserver;
struct java_lang_String;
struct vrml_external_Node;
struct vrml_external_field_EventOut;
struct java_lang_Class;

/*******************************************************************************
 * Class vrml/external/field/EventOut
 ******************************************************************************/

typedef struct vrml_external_field_EventOut vrml_external_field_EventOut;

#define classname_vrml_external_field_EventOut	"vrml/external/field/EventOut"

#define class_vrml_external_field_EventOut(env) \
	((struct java_lang_Class*)JRI_FindClass(env, classname_vrml_external_field_EventOut))

/*******************************************************************************
 * Public Methods
 ******************************************************************************/

#ifdef DEBUG

/*** public getType ()I ***/
extern JRI_PUBLIC_API(jint)
vrml_external_field_EventOut_getType(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*** public advise (Lvrml/external/field/EventOutObserver;Ljava/lang/Object;)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_advise(JRIEnv* env, struct vrml_external_field_EventOut* self, struct vrml_external_field_EventOutObserver *a, struct java_lang_Object *b);

/*** public finalize ()V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_finalize(JRIEnv* env, struct vrml_external_field_EventOut* self);

#else /* !DEBUG */

/*** public getType ()I ***/
#define vrml_external_field_EventOut_getType(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_getType))

/*** public advise (Lvrml/external/field/EventOutObserver;Ljava/lang/Object;)V ***/
#define vrml_external_field_EventOut_advise(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_advise, a, b))

/*** public finalize ()V ***/
#define vrml_external_field_EventOut_finalize(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_finalize))

#endif /* !DEBUG*/

/*** public getType ()I ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_getType;
#define name_vrml_external_field_EventOut_getType	"getType"
#define sig_vrml_external_field_EventOut_getType 	"()I"
#define use_vrml_external_field_EventOut_getType(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getType =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_getType,	\
			sig_vrml_external_field_EventOut_getType))
#define unuse_vrml_external_field_EventOut_getType(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getType = JRIUninitialized)

/*** public advise (Lvrml/external/field/EventOutObserver;Ljava/lang/Object;)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_advise;
#define name_vrml_external_field_EventOut_advise	"advise"
#define sig_vrml_external_field_EventOut_advise 	"(Lvrml/external/field/EventOutObserver;Ljava/lang/Object;)V"
#define use_vrml_external_field_EventOut_advise(env, clazz)	\
	(methodID_vrml_external_field_EventOut_advise =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_advise,	\
			sig_vrml_external_field_EventOut_advise))
#define unuse_vrml_external_field_EventOut_advise(env, clazz)	\
	(methodID_vrml_external_field_EventOut_advise = JRIUninitialized)

/*** public finalize ()V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_finalize;
#define name_vrml_external_field_EventOut_finalize	"finalize"
#define sig_vrml_external_field_EventOut_finalize 	"()V"
#define use_vrml_external_field_EventOut_finalize(env, clazz)	\
	(methodID_vrml_external_field_EventOut_finalize =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_finalize,	\
			sig_vrml_external_field_EventOut_finalize))
#define unuse_vrml_external_field_EventOut_finalize(env, clazz)	\
	(methodID_vrml_external_field_EventOut_finalize = JRIUninitialized)

/*******************************************************************************
 * IMPLEMENTATION SECTION: 
 * Define the IMPLEMENT_vrml_external_field_EventOut symbol 
 * if you intend to implement the native methods of this class. This 
 * symbol makes the private and protected methods available. You should 
 * also call the register_vrml_external_field_EventOut routine 
 * to make your native methods available.
 ******************************************************************************/

extern JRI_PUBLIC_API(struct java_lang_Class*)
use_vrml_external_field_EventOut(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unuse_vrml_external_field_EventOut(JRIEnv* env);

extern JRI_PUBLIC_API(struct java_lang_Class*)
register_vrml_external_field_EventOut(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unregister_vrml_external_field_EventOut(JRIEnv* env);

#ifdef IMPLEMENT_vrml_external_field_EventOut

/*******************************************************************************
 * Native Methods: 
 * These are the signatures of the native methods which you must implement.
 ******************************************************************************/

/*** private native advise ()V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventOut_advise_1(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*** protected native getString ([Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventOut_getString(JRIEnv* env, struct vrml_external_field_EventOut* self, jstringArray a);

/*** protected native get1String (I)Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
native_vrml_external_field_EventOut_get1String(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a);

/*** protected native getNode ([Lvrml/external/Node;)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventOut_getNode(JRIEnv* env, struct vrml_external_field_EventOut* self, jobjectArray a);

/*** protected native get1Node (I)Lvrml/external/Node; ***/
extern JRI_PUBLIC_API(struct vrml_external_Node *)
native_vrml_external_field_EventOut_get1Node(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a);

/*** protected native getInt ([I)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventOut_getInt(JRIEnv* env, struct vrml_external_field_EventOut* self, jintArray a);

/*** protected native get1Int (I)I ***/
extern JRI_PUBLIC_API(jint)
native_vrml_external_field_EventOut_get1Int(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a);

/*** protected native getFloat (I[F)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventOut_getFloat(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a, jfloatArray b);

/*** protected native get1Float (I)F ***/
extern JRI_PUBLIC_API(jfloat)
native_vrml_external_field_EventOut_get1Float(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a);

/*** protected native getSize ()I ***/
extern JRI_PUBLIC_API(jint)
native_vrml_external_field_EventOut_getSize(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*** protected native getTime ()D ***/
extern JRI_PUBLIC_API(jdouble)
native_vrml_external_field_EventOut_getTime(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*** protected native getBoolean ()Z ***/
extern JRI_PUBLIC_API(jbool)
native_vrml_external_field_EventOut_getBoolean(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*** protected native getByte ([B)V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventOut_getByte(JRIEnv* env, struct vrml_external_field_EventOut* self, jbyteArray a);

/*** private native nFinalize ()V ***/
extern JRI_PUBLIC_API(void)
native_vrml_external_field_EventOut_nFinalize(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*******************************************************************************
 * Implementation Field Accessors: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** private cBrowser I ***/
extern JRI_PUBLIC_API(jint)
get_vrml_external_field_EventOut_cBrowser(JRIEnv* env, vrml_external_field_EventOut* obj);
extern JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_cBrowser(JRIEnv* env, vrml_external_field_EventOut* obj, jint v);

/*** private cEvent I ***/
extern JRI_PUBLIC_API(jint)
get_vrml_external_field_EventOut_cEvent(JRIEnv* env, vrml_external_field_EventOut* obj);
extern JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_cEvent(JRIEnv* env, vrml_external_field_EventOut* obj, jint v);

/*** private type I ***/
extern JRI_PUBLIC_API(jint)
get_vrml_external_field_EventOut_type(JRIEnv* env, vrml_external_field_EventOut* obj);
extern JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_type(JRIEnv* env, vrml_external_field_EventOut* obj, jint v);

/*** private userData Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
get_vrml_external_field_EventOut_userData(JRIEnv* env, vrml_external_field_EventOut* obj);
extern JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_userData(JRIEnv* env, vrml_external_field_EventOut* obj, struct java_lang_Object * v);

/*** private observer Lvrml/external/field/EventOutObserver; ***/
extern JRI_PUBLIC_API(struct vrml_external_field_EventOutObserver *)
get_vrml_external_field_EventOut_observer(JRIEnv* env, vrml_external_field_EventOut* obj);
extern JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_observer(JRIEnv* env, vrml_external_field_EventOut* obj, struct vrml_external_field_EventOutObserver * v);

#else /* !DEBUG */

/*** private cBrowser I ***/
#define get_vrml_external_field_EventOut_cBrowser(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_cBrowser))
#define set_vrml_external_field_EventOut_cBrowser(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_cBrowser, v)

/*** private cEvent I ***/
#define get_vrml_external_field_EventOut_cEvent(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_cEvent))
#define set_vrml_external_field_EventOut_cEvent(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_cEvent, v)

/*** private type I ***/
#define get_vrml_external_field_EventOut_type(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_type))
#define set_vrml_external_field_EventOut_type(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_type, v)

/*** private userData Ljava/lang/Object; ***/
#define get_vrml_external_field_EventOut_userData(env, obj) \
	((struct java_lang_Object *)JRI_GetField(env, obj, fieldID_vrml_external_field_EventOut_userData))
#define set_vrml_external_field_EventOut_userData(env, obj, v) \
	JRI_SetField(env, obj, fieldID_vrml_external_field_EventOut_userData, v)

/*** private observer Lvrml/external/field/EventOutObserver; ***/
#define get_vrml_external_field_EventOut_observer(env, obj) \
	((struct vrml_external_field_EventOutObserver *)JRI_GetField(env, obj, fieldID_vrml_external_field_EventOut_observer))
#define set_vrml_external_field_EventOut_observer(env, obj, v) \
	JRI_SetField(env, obj, fieldID_vrml_external_field_EventOut_observer, v)

#endif /* !DEBUG*/

extern JRIFieldID FAR fieldID_vrml_external_field_EventOut_cBrowser;
#define name_vrml_external_field_EventOut_cBrowser	"cBrowser"
#define sig_vrml_external_field_EventOut_cBrowser 	"I"
#define use_vrml_external_field_EventOut_cBrowser(env, clazz)	\
	(fieldID_vrml_external_field_EventOut_cBrowser =	\
		JRI_GetFieldID(env, clazz,	\
			name_vrml_external_field_EventOut_cBrowser,	\
			sig_vrml_external_field_EventOut_cBrowser))
#define unuse_vrml_external_field_EventOut_cBrowser(env, clazz)	\
		(fieldID_vrml_external_field_EventOut_cBrowser = JRIUninitialized)

extern JRIFieldID FAR fieldID_vrml_external_field_EventOut_cEvent;
#define name_vrml_external_field_EventOut_cEvent	"cEvent"
#define sig_vrml_external_field_EventOut_cEvent 	"I"
#define use_vrml_external_field_EventOut_cEvent(env, clazz)	\
	(fieldID_vrml_external_field_EventOut_cEvent =	\
		JRI_GetFieldID(env, clazz,	\
			name_vrml_external_field_EventOut_cEvent,	\
			sig_vrml_external_field_EventOut_cEvent))
#define unuse_vrml_external_field_EventOut_cEvent(env, clazz)	\
		(fieldID_vrml_external_field_EventOut_cEvent = JRIUninitialized)

extern JRIFieldID FAR fieldID_vrml_external_field_EventOut_type;
#define name_vrml_external_field_EventOut_type	"type"
#define sig_vrml_external_field_EventOut_type 	"I"
#define use_vrml_external_field_EventOut_type(env, clazz)	\
	(fieldID_vrml_external_field_EventOut_type =	\
		JRI_GetFieldID(env, clazz,	\
			name_vrml_external_field_EventOut_type,	\
			sig_vrml_external_field_EventOut_type))
#define unuse_vrml_external_field_EventOut_type(env, clazz)	\
		(fieldID_vrml_external_field_EventOut_type = JRIUninitialized)

extern JRIFieldID FAR fieldID_vrml_external_field_EventOut_userData;
#define name_vrml_external_field_EventOut_userData	"userData"
#define sig_vrml_external_field_EventOut_userData 	"Ljava/lang/Object;"
#define use_vrml_external_field_EventOut_userData(env, clazz)	\
	(fieldID_vrml_external_field_EventOut_userData =	\
		JRI_GetFieldID(env, clazz,	\
			name_vrml_external_field_EventOut_userData,	\
			sig_vrml_external_field_EventOut_userData))
#define unuse_vrml_external_field_EventOut_userData(env, clazz)	\
		(fieldID_vrml_external_field_EventOut_userData = JRIUninitialized)

extern JRIFieldID FAR fieldID_vrml_external_field_EventOut_observer;
#define name_vrml_external_field_EventOut_observer	"observer"
#define sig_vrml_external_field_EventOut_observer 	"Lvrml/external/field/EventOutObserver;"
#define use_vrml_external_field_EventOut_observer(env, clazz)	\
	(fieldID_vrml_external_field_EventOut_observer =	\
		JRI_GetFieldID(env, clazz,	\
			name_vrml_external_field_EventOut_observer,	\
			sig_vrml_external_field_EventOut_observer))
#define unuse_vrml_external_field_EventOut_observer(env, clazz)	\
		(fieldID_vrml_external_field_EventOut_observer = JRIUninitialized)

/*******************************************************************************
 * Implementation Methods: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** protected <init> (III)V ***/
extern JRI_PUBLIC_API(struct vrml_external_field_EventOut*)
vrml_external_field_EventOut_new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c);

/*** private native advise ()V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_advise_1(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*** protected callback (D)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_callback(JRIEnv* env, struct vrml_external_field_EventOut* self, jdouble a);

/*** protected native getString ([Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getString(JRIEnv* env, struct vrml_external_field_EventOut* self, jstringArray a);

/*** protected native get1String (I)Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_field_EventOut_get1String(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a);

/*** protected native getNode ([Lvrml/external/Node;)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getNode(JRIEnv* env, struct vrml_external_field_EventOut* self, jobjectArray a);

/*** protected native get1Node (I)Lvrml/external/Node; ***/
extern JRI_PUBLIC_API(struct vrml_external_Node *)
vrml_external_field_EventOut_get1Node(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a);

/*** protected native getInt ([I)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getInt(JRIEnv* env, struct vrml_external_field_EventOut* self, jintArray a);

/*** protected native get1Int (I)I ***/
extern JRI_PUBLIC_API(jint)
vrml_external_field_EventOut_get1Int(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a);

/*** protected native getFloat (I[F)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getFloat(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a, jfloatArray b);

/*** protected native get1Float (I)F ***/
extern JRI_PUBLIC_API(jfloat)
vrml_external_field_EventOut_get1Float(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a);

/*** protected native getSize ()I ***/
extern JRI_PUBLIC_API(jint)
vrml_external_field_EventOut_getSize(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*** protected native getTime ()D ***/
extern JRI_PUBLIC_API(jdouble)
vrml_external_field_EventOut_getTime(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*** protected native getBoolean ()Z ***/
extern JRI_PUBLIC_API(jbool)
vrml_external_field_EventOut_getBoolean(JRIEnv* env, struct vrml_external_field_EventOut* self);

/*** protected native getByte ([B)V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getByte(JRIEnv* env, struct vrml_external_field_EventOut* self, jbyteArray a);

/*** protected static newEventOut (III)Lvrml/external/field/EventOut; ***/
extern JRI_PUBLIC_API(struct vrml_external_field_EventOut *)
vrml_external_field_EventOut_newEventOut(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c);

/*** private native nFinalize ()V ***/
extern JRI_PUBLIC_API(void)
vrml_external_field_EventOut_nFinalize(JRIEnv* env, struct vrml_external_field_EventOut* self);

#else /* !DEBUG */

/*** protected <init> (III)V ***/
#define vrml_external_field_EventOut_new(env, clazz, a, b, c)	\
	((struct vrml_external_field_EventOut*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_vrml_external_field_EventOut_new, a, b, c))

/*** private native advise ()V ***/
#define vrml_external_field_EventOut_advise_1(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_advise_1))

/*** protected callback (D)V ***/
#define vrml_external_field_EventOut_callback(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_callback, a))

/*** protected native getString ([Ljava/lang/String;)V ***/
#define vrml_external_field_EventOut_getString(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_getString, a))

/*** protected native get1String (I)Ljava/lang/String; ***/
#define vrml_external_field_EventOut_get1String(env, obj, a) \
	((struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_get1String, a))

/*** protected native getNode ([Lvrml/external/Node;)V ***/
#define vrml_external_field_EventOut_getNode(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_getNode, a))

/*** protected native get1Node (I)Lvrml/external/Node; ***/
#define vrml_external_field_EventOut_get1Node(env, obj, a) \
	((struct vrml_external_Node *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_get1Node, a))

/*** protected native getInt ([I)V ***/
#define vrml_external_field_EventOut_getInt(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_getInt, a))

/*** protected native get1Int (I)I ***/
#define vrml_external_field_EventOut_get1Int(env, obj, a) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_get1Int, a))

/*** protected native getFloat (I[F)V ***/
#define vrml_external_field_EventOut_getFloat(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_getFloat, a, b))

/*** protected native get1Float (I)F ***/
#define vrml_external_field_EventOut_get1Float(env, obj, a) \
	((jfloat)JRI_CallMethodFloat(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_get1Float, a))

/*** protected native getSize ()I ***/
#define vrml_external_field_EventOut_getSize(env, obj) \
	((jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_getSize))

/*** protected native getTime ()D ***/
#define vrml_external_field_EventOut_getTime(env, obj) \
	((jdouble)JRI_CallMethodDouble(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_getTime))

/*** protected native getBoolean ()Z ***/
#define vrml_external_field_EventOut_getBoolean(env, obj) \
	((jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_getBoolean))

/*** protected native getByte ([B)V ***/
#define vrml_external_field_EventOut_getByte(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_getByte, a))

/*** protected static newEventOut (III)Lvrml/external/field/EventOut; ***/
#define vrml_external_field_EventOut_newEventOut(env, clazz, a, b, c) \
	((struct vrml_external_field_EventOut *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_vrml_external_field_EventOut_newEventOut, a, b, c))

/*** private native nFinalize ()V ***/
#define vrml_external_field_EventOut_nFinalize(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_vrml_external_field_EventOut_nFinalize))

#endif /* !DEBUG*/

/*** protected <init> (III)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_new;
#define name_vrml_external_field_EventOut_new	"<init>"
#define sig_vrml_external_field_EventOut_new 	"(III)V"
#define use_vrml_external_field_EventOut_new(env, clazz)	\
	(methodID_vrml_external_field_EventOut_new =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_new,	\
			sig_vrml_external_field_EventOut_new))
#define unuse_vrml_external_field_EventOut_new(env, clazz)	\
	(methodID_vrml_external_field_EventOut_new = JRIUninitialized)

/*** private native advise ()V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_advise_1;
#define name_vrml_external_field_EventOut_advise_1	"advise"
#define sig_vrml_external_field_EventOut_advise_1 	"()V"
#define use_vrml_external_field_EventOut_advise_1(env, clazz)	\
	(methodID_vrml_external_field_EventOut_advise_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_advise_1,	\
			sig_vrml_external_field_EventOut_advise_1))
#define unuse_vrml_external_field_EventOut_advise_1(env, clazz)	\
	(methodID_vrml_external_field_EventOut_advise_1 = JRIUninitialized)

/*** protected callback (D)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_callback;
#define name_vrml_external_field_EventOut_callback	"callback"
#define sig_vrml_external_field_EventOut_callback 	"(D)V"
#define use_vrml_external_field_EventOut_callback(env, clazz)	\
	(methodID_vrml_external_field_EventOut_callback =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_callback,	\
			sig_vrml_external_field_EventOut_callback))
#define unuse_vrml_external_field_EventOut_callback(env, clazz)	\
	(methodID_vrml_external_field_EventOut_callback = JRIUninitialized)

/*** protected native getString ([Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_getString;
#define name_vrml_external_field_EventOut_getString	"getString"
#define sig_vrml_external_field_EventOut_getString 	"([Ljava/lang/String;)V"
#define use_vrml_external_field_EventOut_getString(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getString =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_getString,	\
			sig_vrml_external_field_EventOut_getString))
#define unuse_vrml_external_field_EventOut_getString(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getString = JRIUninitialized)

/*** protected native get1String (I)Ljava/lang/String; ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_get1String;
#define name_vrml_external_field_EventOut_get1String	"get1String"
#define sig_vrml_external_field_EventOut_get1String 	"(I)Ljava/lang/String;"
#define use_vrml_external_field_EventOut_get1String(env, clazz)	\
	(methodID_vrml_external_field_EventOut_get1String =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_get1String,	\
			sig_vrml_external_field_EventOut_get1String))
#define unuse_vrml_external_field_EventOut_get1String(env, clazz)	\
	(methodID_vrml_external_field_EventOut_get1String = JRIUninitialized)

/*** protected native getNode ([Lvrml/external/Node;)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_getNode;
#define name_vrml_external_field_EventOut_getNode	"getNode"
#define sig_vrml_external_field_EventOut_getNode 	"([Lvrml/external/Node;)V"
#define use_vrml_external_field_EventOut_getNode(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getNode =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_getNode,	\
			sig_vrml_external_field_EventOut_getNode))
#define unuse_vrml_external_field_EventOut_getNode(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getNode = JRIUninitialized)

/*** protected native get1Node (I)Lvrml/external/Node; ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_get1Node;
#define name_vrml_external_field_EventOut_get1Node	"get1Node"
#define sig_vrml_external_field_EventOut_get1Node 	"(I)Lvrml/external/Node;"
#define use_vrml_external_field_EventOut_get1Node(env, clazz)	\
	(methodID_vrml_external_field_EventOut_get1Node =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_get1Node,	\
			sig_vrml_external_field_EventOut_get1Node))
#define unuse_vrml_external_field_EventOut_get1Node(env, clazz)	\
	(methodID_vrml_external_field_EventOut_get1Node = JRIUninitialized)

/*** protected native getInt ([I)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_getInt;
#define name_vrml_external_field_EventOut_getInt	"getInt"
#define sig_vrml_external_field_EventOut_getInt 	"([I)V"
#define use_vrml_external_field_EventOut_getInt(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getInt =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_getInt,	\
			sig_vrml_external_field_EventOut_getInt))
#define unuse_vrml_external_field_EventOut_getInt(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getInt = JRIUninitialized)

/*** protected native get1Int (I)I ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_get1Int;
#define name_vrml_external_field_EventOut_get1Int	"get1Int"
#define sig_vrml_external_field_EventOut_get1Int 	"(I)I"
#define use_vrml_external_field_EventOut_get1Int(env, clazz)	\
	(methodID_vrml_external_field_EventOut_get1Int =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_get1Int,	\
			sig_vrml_external_field_EventOut_get1Int))
#define unuse_vrml_external_field_EventOut_get1Int(env, clazz)	\
	(methodID_vrml_external_field_EventOut_get1Int = JRIUninitialized)

/*** protected native getFloat (I[F)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_getFloat;
#define name_vrml_external_field_EventOut_getFloat	"getFloat"
#define sig_vrml_external_field_EventOut_getFloat 	"(I[F)V"
#define use_vrml_external_field_EventOut_getFloat(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getFloat =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_getFloat,	\
			sig_vrml_external_field_EventOut_getFloat))
#define unuse_vrml_external_field_EventOut_getFloat(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getFloat = JRIUninitialized)

/*** protected native get1Float (I)F ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_get1Float;
#define name_vrml_external_field_EventOut_get1Float	"get1Float"
#define sig_vrml_external_field_EventOut_get1Float 	"(I)F"
#define use_vrml_external_field_EventOut_get1Float(env, clazz)	\
	(methodID_vrml_external_field_EventOut_get1Float =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_get1Float,	\
			sig_vrml_external_field_EventOut_get1Float))
#define unuse_vrml_external_field_EventOut_get1Float(env, clazz)	\
	(methodID_vrml_external_field_EventOut_get1Float = JRIUninitialized)

/*** protected native getSize ()I ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_getSize;
#define name_vrml_external_field_EventOut_getSize	"getSize"
#define sig_vrml_external_field_EventOut_getSize 	"()I"
#define use_vrml_external_field_EventOut_getSize(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getSize =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_getSize,	\
			sig_vrml_external_field_EventOut_getSize))
#define unuse_vrml_external_field_EventOut_getSize(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getSize = JRIUninitialized)

/*** protected native getTime ()D ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_getTime;
#define name_vrml_external_field_EventOut_getTime	"getTime"
#define sig_vrml_external_field_EventOut_getTime 	"()D"
#define use_vrml_external_field_EventOut_getTime(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getTime =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_getTime,	\
			sig_vrml_external_field_EventOut_getTime))
#define unuse_vrml_external_field_EventOut_getTime(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getTime = JRIUninitialized)

/*** protected native getBoolean ()Z ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_getBoolean;
#define name_vrml_external_field_EventOut_getBoolean	"getBoolean"
#define sig_vrml_external_field_EventOut_getBoolean 	"()Z"
#define use_vrml_external_field_EventOut_getBoolean(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getBoolean =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_getBoolean,	\
			sig_vrml_external_field_EventOut_getBoolean))
#define unuse_vrml_external_field_EventOut_getBoolean(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getBoolean = JRIUninitialized)

/*** protected native getByte ([B)V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_getByte;
#define name_vrml_external_field_EventOut_getByte	"getByte"
#define sig_vrml_external_field_EventOut_getByte 	"([B)V"
#define use_vrml_external_field_EventOut_getByte(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getByte =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_getByte,	\
			sig_vrml_external_field_EventOut_getByte))
#define unuse_vrml_external_field_EventOut_getByte(env, clazz)	\
	(methodID_vrml_external_field_EventOut_getByte = JRIUninitialized)

/*** protected static newEventOut (III)Lvrml/external/field/EventOut; ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_newEventOut;
#define name_vrml_external_field_EventOut_newEventOut	"newEventOut"
#define sig_vrml_external_field_EventOut_newEventOut 	"(III)Lvrml/external/field/EventOut;"
#define use_vrml_external_field_EventOut_newEventOut(env, clazz)	\
	(methodID_vrml_external_field_EventOut_newEventOut =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_newEventOut,	\
			sig_vrml_external_field_EventOut_newEventOut))
#define unuse_vrml_external_field_EventOut_newEventOut(env, clazz)	\
	(methodID_vrml_external_field_EventOut_newEventOut = JRIUninitialized)

/*** private native nFinalize ()V ***/
extern JRIMethodID FAR methodID_vrml_external_field_EventOut_nFinalize;
#define name_vrml_external_field_EventOut_nFinalize	"nFinalize"
#define sig_vrml_external_field_EventOut_nFinalize 	"()V"
#define use_vrml_external_field_EventOut_nFinalize(env, clazz)	\
	(methodID_vrml_external_field_EventOut_nFinalize =	\
		JRI_GetMethodID(env, clazz,	\
			name_vrml_external_field_EventOut_nFinalize,	\
			sig_vrml_external_field_EventOut_nFinalize))
#define unuse_vrml_external_field_EventOut_nFinalize(env, clazz)	\
	(methodID_vrml_external_field_EventOut_nFinalize = JRIUninitialized)

#endif /* IMPLEMENT_vrml_external_field_EventOut */

#ifdef __cplusplus
} /* extern "C" */

/*******************************************************************************
 * C++ Definitions
 ******************************************************************************/

#include "java_lang_Object.h"

struct vrml_external_field_EventOut : virtual public java_lang_Object {

	static struct java_lang_Class* _use(JRIEnv* env) {
		return use_vrml_external_field_EventOut(env);
	}

	static void _unuse(JRIEnv* env) {
		unuse_vrml_external_field_EventOut(env);
	}

	static struct java_lang_Class* _register(JRIEnv* env) {
		return register_vrml_external_field_EventOut(env);
	}

	static void _unregister(JRIEnv* env) {
		unregister_vrml_external_field_EventOut(env);
	}

	static struct java_lang_Class* _class(JRIEnv* env) {
		return class_vrml_external_field_EventOut(env);
	}

	/* Public Methods */
	/*** public getType ()I ***/
	jint getType(JRIEnv* env) {
		return vrml_external_field_EventOut_getType(env, this);
	}

	/*** public advise (Lvrml/external/field/EventOutObserver;Ljava/lang/Object;)V ***/
	void advise(JRIEnv* env, struct vrml_external_field_EventOutObserver *a, struct java_lang_Object *b) {
		vrml_external_field_EventOut_advise(env, this, a, b);
	}

	/*** public finalize ()V ***/
	void finalize(JRIEnv* env) {
		vrml_external_field_EventOut_finalize(env, this);
	}

#ifdef IMPLEMENT_vrml_external_field_EventOut

	/* Protected Methods */
	/*** protected <init> (III)V ***/
	static vrml_external_field_EventOut* _new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
		return vrml_external_field_EventOut_new(env, clazz, a, b, c);
	}

	/*** protected callback (D)V ***/
	void callback(JRIEnv* env, jdouble a) {
		vrml_external_field_EventOut_callback(env, this, a);
	}

	/*** protected native getString ([Ljava/lang/String;)V ***/
	void getString(JRIEnv* env, jstringArray a) {
		vrml_external_field_EventOut_getString(env, this, a);
	}

	/*** protected native get1String (I)Ljava/lang/String; ***/
	struct java_lang_String * get1String(JRIEnv* env, jint a) {
		return vrml_external_field_EventOut_get1String(env, this, a);
	}

	/*** protected native getNode ([Lvrml/external/Node;)V ***/
	void getNode(JRIEnv* env, jobjectArray a) {
		vrml_external_field_EventOut_getNode(env, this, a);
	}

	/*** protected native get1Node (I)Lvrml/external/Node; ***/
	struct vrml_external_Node * get1Node(JRIEnv* env, jint a) {
		return vrml_external_field_EventOut_get1Node(env, this, a);
	}

	/*** protected native getInt ([I)V ***/
	void getInt(JRIEnv* env, jintArray a) {
		vrml_external_field_EventOut_getInt(env, this, a);
	}

	/*** protected native get1Int (I)I ***/
	jint get1Int(JRIEnv* env, jint a) {
		return vrml_external_field_EventOut_get1Int(env, this, a);
	}

	/*** protected native getFloat (I[F)V ***/
	void getFloat(JRIEnv* env, jint a, jfloatArray b) {
		vrml_external_field_EventOut_getFloat(env, this, a, b);
	}

	/*** protected native get1Float (I)F ***/
	jfloat get1Float(JRIEnv* env, jint a) {
		return vrml_external_field_EventOut_get1Float(env, this, a);
	}

	/*** protected native getSize ()I ***/
	jint getSize(JRIEnv* env) {
		return vrml_external_field_EventOut_getSize(env, this);
	}

	/*** protected native getTime ()D ***/
	jdouble getTime(JRIEnv* env) {
		return vrml_external_field_EventOut_getTime(env, this);
	}

	/*** protected native getBoolean ()Z ***/
	jbool getBoolean(JRIEnv* env) {
		return vrml_external_field_EventOut_getBoolean(env, this);
	}

	/*** protected native getByte ([B)V ***/
	void getByte(JRIEnv* env, jbyteArray a) {
		vrml_external_field_EventOut_getByte(env, this, a);
	}

	/*** protected static newEventOut (III)Lvrml/external/field/EventOut; ***/
	static struct vrml_external_field_EventOut * newEventOut(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
		return vrml_external_field_EventOut_newEventOut(env, clazz, a, b, c);
	}

	/* Private Field Accessors */
	/*** private cBrowser I ***/
	jint cBrowser(JRIEnv* env) {
		return get_vrml_external_field_EventOut_cBrowser(env, this);
	}
	void cBrowser(JRIEnv* env, jint v) {
		set_vrml_external_field_EventOut_cBrowser(env, this, v);
	}

	/*** private cEvent I ***/
	jint cEvent(JRIEnv* env) {
		return get_vrml_external_field_EventOut_cEvent(env, this);
	}
	void cEvent(JRIEnv* env, jint v) {
		set_vrml_external_field_EventOut_cEvent(env, this, v);
	}

	/*** private type I ***/
	jint type(JRIEnv* env) {
		return get_vrml_external_field_EventOut_type(env, this);
	}
	void type(JRIEnv* env, jint v) {
		set_vrml_external_field_EventOut_type(env, this, v);
	}

	/*** private userData Ljava/lang/Object; ***/
	struct java_lang_Object * userData(JRIEnv* env) {
		return get_vrml_external_field_EventOut_userData(env, this);
	}
	void userData(JRIEnv* env, struct java_lang_Object * v) {
		set_vrml_external_field_EventOut_userData(env, this, v);
	}

	/*** private observer Lvrml/external/field/EventOutObserver; ***/
	struct vrml_external_field_EventOutObserver * observer(JRIEnv* env) {
		return get_vrml_external_field_EventOut_observer(env, this);
	}
	void observer(JRIEnv* env, struct vrml_external_field_EventOutObserver * v) {
		set_vrml_external_field_EventOut_observer(env, this, v);
	}

	/* Private Methods */
	/*** private native advise ()V ***/
	void advise(JRIEnv* env) {
		vrml_external_field_EventOut_advise_1(env, this);
	}

	/*** private native nFinalize ()V ***/
	void nFinalize(JRIEnv* env) {
		vrml_external_field_EventOut_nFinalize(env, this);
	}

#endif /* IMPLEMENT_vrml_external_field_EventOut */
};

#endif /* __cplusplus */

#endif /* Class vrml/external/field/EventOut */
