/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class vrml/external/Node */

#ifdef IMPLEMENT_vrml_external_Node
#define _implementing_vrml_external_Node
#endif /* IMPLEMENT_vrml_external_Node */
#define IMPLEMENT_vrml_external_Node
#include "vrml_external_Node.h"

#ifndef UNUSED_vrml_external_Node_cBrowser
JRIFieldID FAR fieldID_vrml_external_Node_cBrowser = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_vrml_external_Node_cBrowser(JRIEnv* env, struct vrml_external_Node* obj) {
	if (fieldID_vrml_external_Node_cBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before accessing field cBrowser I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_vrml_external_Node_cBrowser);
}
JRI_PUBLIC_API(void)
set_vrml_external_Node_cBrowser(JRIEnv* env, struct vrml_external_Node* obj, jint v) {
	if (fieldID_vrml_external_Node_cBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before accessing field cBrowser I");
	}
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_Node_cBrowser, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Node_cBrowser */

#ifndef UNUSED_vrml_external_Node_cNode
JRIFieldID FAR fieldID_vrml_external_Node_cNode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_vrml_external_Node_cNode(JRIEnv* env, struct vrml_external_Node* obj) {
	if (fieldID_vrml_external_Node_cNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before accessing field cNode I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_vrml_external_Node_cNode);
}
JRI_PUBLIC_API(void)
set_vrml_external_Node_cNode(JRIEnv* env, struct vrml_external_Node* obj, jint v) {
	if (fieldID_vrml_external_Node_cNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before accessing field cNode I");
	}
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_Node_cNode, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Node_cNode */

#ifndef UNUSED_vrml_external_Node_new
JRIMethodID FAR methodID_vrml_external_Node_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Node*)
vrml_external_Node_new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b) {
	if (methodID_vrml_external_Node_new == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before calling method <init> (II)V");
	}
	return (struct vrml_external_Node*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_vrml_external_Node_new, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Node_new */

#ifndef UNUSED_vrml_external_Node_getType
JRIMethodID FAR methodID_vrml_external_Node_getType = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Node_getType(JRIEnv* env, struct vrml_external_Node* self) {
	if (methodID_vrml_external_Node_getType == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before calling method getType ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Node_getType);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Node_getType */

#ifndef UNUSED_vrml_external_Node_getEventIn
JRIMethodID FAR methodID_vrml_external_Node_getEventIn = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_field_EventIn *)
vrml_external_Node_getEventIn(JRIEnv* env, struct vrml_external_Node* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Node_getEventIn == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before calling method getEventIn (Ljava/lang/String;)Lvrml/external/field/EventIn;");
	}
	return (struct vrml_external_field_EventIn *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Node_getEventIn, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Node_getEventIn */

#ifndef UNUSED_vrml_external_Node_getEventOut
JRIMethodID FAR methodID_vrml_external_Node_getEventOut = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_field_EventOut *)
vrml_external_Node_getEventOut(JRIEnv* env, struct vrml_external_Node* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Node_getEventOut == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before calling method getEventOut (Ljava/lang/String;)Lvrml/external/field/EventOut;");
	}
	return (struct vrml_external_field_EventOut *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Node_getEventOut, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Node_getEventOut */

#ifndef UNUSED_vrml_external_Node_finalize
JRIMethodID FAR methodID_vrml_external_Node_finalize = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Node_finalize(JRIEnv* env, struct vrml_external_Node* self) {
	if (methodID_vrml_external_Node_finalize == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before calling method finalize ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Node_finalize);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Node_finalize */

#ifndef UNUSED_vrml_external_Node_nFinalize
JRIMethodID FAR methodID_vrml_external_Node_nFinalize = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Node_nFinalize(JRIEnv* env, struct vrml_external_Node* self) {
	if (methodID_vrml_external_Node_nFinalize == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Node(env) before calling method nFinalize ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Node_nFinalize);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Node_nFinalize */

#ifndef UNUSED_use_vrml_external_Node

static jglobal _globalclass_vrml_external_Node = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_vrml_external_Node(JRIEnv* env)
{
	if (_globalclass_vrml_external_Node == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_Node);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_Node);
			return NULL;
		}
		use_vrml_external_Node_cBrowser(env, clazz);
		use_vrml_external_Node_cNode(env, clazz);
		use_vrml_external_Node_new(env, clazz);
		use_vrml_external_Node_getType(env, clazz);
		use_vrml_external_Node_getEventIn(env, clazz);
		use_vrml_external_Node_getEventOut(env, clazz);
		use_vrml_external_Node_finalize(env, clazz);
		use_vrml_external_Node_nFinalize(env, clazz);
		_globalclass_vrml_external_Node = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_Node);
	}
}

JRI_PUBLIC_API(void)
unuse_vrml_external_Node(JRIEnv* env)
{
	if (_globalclass_vrml_external_Node != NULL) {
		struct java_lang_Class* clazz = (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_Node);
		unuse_vrml_external_Node_cBrowser(env, clazz);
		unuse_vrml_external_Node_cNode(env, clazz);
		unuse_vrml_external_Node_new(env, clazz);
		unuse_vrml_external_Node_getType(env, clazz);
		unuse_vrml_external_Node_getEventIn(env, clazz);
		unuse_vrml_external_Node_getEventOut(env, clazz);
		unuse_vrml_external_Node_finalize(env, clazz);
		unuse_vrml_external_Node_nFinalize(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_vrml_external_Node);
		_globalclass_vrml_external_Node = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_vrml_external_Node */

#ifdef _implementing_vrml_external_Node

JRI_PUBLIC_API(struct java_lang_Class*)
register_vrml_external_Node(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"getType()Ljava/lang/String;",
		"getEventIn(Ljava/lang/String;)Lvrml/external/field/EventIn;",
		"getEventOut(Ljava/lang/String;)Lvrml/external/field/EventOut;",
		"nFinalize()V",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_vrml_external_Node_getType,
		(void*)native_vrml_external_Node_getEventIn,
		(void*)native_vrml_external_Node_getEventOut,
		(void*)native_vrml_external_Node_nFinalize,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_Node);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_Node);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_vrml_external_Node(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_vrml_external_Node(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_Node);
	JRI_UnregisterNatives(env, clazz);
	unuse_vrml_external_Node(env);
}

#endif /* _implementing_vrml_external_Node */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

/* SYMBOL: "vrml/external/Node/getType()Ljava/lang/String;", Java_vrml_external_Node_getType_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Node_getType_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Node_getType(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Node/getEventIn(Ljava/lang/String;)Lvrml/external/field/EventIn;", Java_vrml_external_Node_getEventIn_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Node_getEventIn_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Node_getEventIn(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Node/getEventOut(Ljava/lang/String;)Lvrml/external/field/EventOut;", Java_vrml_external_Node_getEventOut_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Node_getEventOut_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Node_getEventOut(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Node/nFinalize()V", Java_vrml_external_Node_nFinalize_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Node_nFinalize_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Node_nFinalize(_EE_,_P_[0].p);
	return _P_;
}

#endif /* NO_JDK */

