/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class vrml/external/Browser */

#ifdef IMPLEMENT_vrml_external_Browser
#define _implementing_vrml_external_Browser
#endif /* IMPLEMENT_vrml_external_Browser */
#define IMPLEMENT_vrml_external_Browser
#include "vrml_external_Browser.h"

#ifndef UNUSED_vrml_external_Browser_obsEvents
JRIFieldID FAR fieldID_vrml_external_Browser_obsEvents = JRIUninitialized;
#ifdef DEBUG
struct java_util_Vector;
JRI_PUBLIC_API(struct java_util_Vector *)
get_vrml_external_Browser_obsEvents(JRIEnv* env, struct vrml_external_Browser* obj) {
	if (fieldID_vrml_external_Browser_obsEvents == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before accessing field obsEvents Ljava/util/Vector;");
	}
	return (struct java_util_Vector *)
		JRI_GetField(env, obj, fieldID_vrml_external_Browser_obsEvents);
}
JRI_PUBLIC_API(void)
set_vrml_external_Browser_obsEvents(JRIEnv* env, struct vrml_external_Browser* obj, struct java_util_Vector * v) {
	if (fieldID_vrml_external_Browser_obsEvents == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before accessing field obsEvents Ljava/util/Vector;");
	}
	JRI_SetField(env, obj, fieldID_vrml_external_Browser_obsEvents, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_obsEvents */

#ifndef UNUSED_vrml_external_Browser_theBrowser
JRIFieldID FAR fieldID_vrml_external_Browser_theBrowser = JRIUninitialized;
#ifdef DEBUG
struct vrml_external_Browser;
JRI_PUBLIC_API(struct vrml_external_Browser *)
get_vrml_external_Browser_theBrowser(JRIEnv* env, struct java_lang_Class* clazz) {
	if (fieldID_vrml_external_Browser_theBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before accessing field theBrowser Lvrml/external/Browser;");
	}
	return (struct vrml_external_Browser *)
		JRI_GetStaticField(env, clazz, fieldID_vrml_external_Browser_theBrowser);
}
JRI_PUBLIC_API(void)
set_vrml_external_Browser_theBrowser(JRIEnv* env, struct java_lang_Class* clazz, struct vrml_external_Browser * v) {
	if (fieldID_vrml_external_Browser_theBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before accessing field theBrowser Lvrml/external/Browser;");
	}
	JRI_SetStaticField(env, clazz, fieldID_vrml_external_Browser_theBrowser, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_theBrowser */

#ifndef UNUSED_vrml_external_Browser_new
JRIMethodID FAR methodID_vrml_external_Browser_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Browser*)
vrml_external_Browser_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_vrml_external_Browser_new == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method <init> ()V");
	}
	return (struct vrml_external_Browser*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_vrml_external_Browser_new);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_new */

#ifndef UNUSED_vrml_external_Browser_setBrowser
JRIMethodID FAR methodID_vrml_external_Browser_setBrowser = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setBrowser(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_setBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setBrowser ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setBrowser);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setBrowser */

#ifndef UNUSED_vrml_external_Browser_init
JRIMethodID FAR methodID_vrml_external_Browser_init = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_init(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_init == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method init ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_init);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_init */

#ifndef UNUSED_vrml_external_Browser_destroy
JRIMethodID FAR methodID_vrml_external_Browser_destroy = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_destroy(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_destroy == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method destroy ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_destroy);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_destroy */

#ifndef UNUSED_vrml_external_Browser_getBrowser
JRIMethodID FAR methodID_vrml_external_Browser_getBrowser = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Browser *)
vrml_external_Browser_getBrowser(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a) {
	if (methodID_vrml_external_Browser_getBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getBrowser (Ljava/lang/Object;)Lvrml/external/Browser;");
	}
	return (struct vrml_external_Browser *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_vrml_external_Browser_getBrowser, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getBrowser */

#ifndef UNUSED_vrml_external_Browser_getBrowser_1
JRIMethodID FAR methodID_vrml_external_Browser_getBrowser_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Browser *)
vrml_external_Browser_getBrowser_1(JRIEnv* env, struct java_lang_Class* clazz, struct java_applet_Applet *a) {
	if (methodID_vrml_external_Browser_getBrowser_1 == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getBrowser (Ljava/applet/Applet;)Lvrml/external/Browser;");
	}
	return (struct vrml_external_Browser *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_vrml_external_Browser_getBrowser_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getBrowser_1 */

#ifndef UNUSED_vrml_external_Browser_getBrowser_2
JRIMethodID FAR methodID_vrml_external_Browser_getBrowser_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Browser *)
vrml_external_Browser_getBrowser_2(JRIEnv* env, struct java_lang_Class* clazz, struct java_applet_Applet *a, struct java_lang_String *b, jint c) {
	if (methodID_vrml_external_Browser_getBrowser_2 == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getBrowser (Ljava/applet/Applet;Ljava/lang/String;I)Lvrml/external/Browser;");
	}
	return (struct vrml_external_Browser *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_vrml_external_Browser_getBrowser_2, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getBrowser_2 */

#ifndef UNUSED_vrml_external_Browser_getString
JRIMethodID FAR methodID_vrml_external_Browser_getString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Browser_getString(JRIEnv* env, struct vrml_external_Browser* self, jint a) {
	if (methodID_vrml_external_Browser_getString == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getString (I)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getString, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getString */

#ifndef UNUSED_vrml_external_Browser_getBoolean
JRIMethodID FAR methodID_vrml_external_Browser_getBoolean = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_getBoolean(JRIEnv* env, struct vrml_external_Browser* self, jint a) {
	if (methodID_vrml_external_Browser_getBoolean == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getBoolean (I)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getBoolean, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getBoolean */

#ifndef UNUSED_vrml_external_Browser_setString
JRIMethodID FAR methodID_vrml_external_Browser_setString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setString(JRIEnv* env, struct vrml_external_Browser* self, jint a, struct java_lang_String *b) {
	if (methodID_vrml_external_Browser_setString == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setString (ILjava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setString, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setString */

#ifndef UNUSED_vrml_external_Browser_setBoolean
JRIMethodID FAR methodID_vrml_external_Browser_setBoolean = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setBoolean(JRIEnv* env, struct vrml_external_Browser* self, jint a, jbool b) {
	if (methodID_vrml_external_Browser_setBoolean == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setBoolean (IZ)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setBoolean, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setBoolean */

#ifndef UNUSED_vrml_external_Browser_addObserver
JRIMethodID FAR methodID_vrml_external_Browser_addObserver = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_addObserver(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_field_EventOut *a) {
	if (methodID_vrml_external_Browser_addObserver == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method addObserver (Lvrml/external/field/EventOut;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_addObserver, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_addObserver */

#ifndef UNUSED_vrml_external_Browser_getName
JRIMethodID FAR methodID_vrml_external_Browser_getName = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Browser_getName(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getName == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getName ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getName);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getName */

#ifndef UNUSED_vrml_external_Browser_getVersion
JRIMethodID FAR methodID_vrml_external_Browser_getVersion = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Browser_getVersion(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getVersion == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getVersion ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getVersion);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getVersion */

#ifndef UNUSED_vrml_external_Browser_getWorldURL
JRIMethodID FAR methodID_vrml_external_Browser_getWorldURL = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Browser_getWorldURL(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getWorldURL == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getWorldURL ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getWorldURL);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getWorldURL */

#ifndef UNUSED_vrml_external_Browser_getViewerMode
JRIMethodID FAR methodID_vrml_external_Browser_getViewerMode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Browser_getViewerMode(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getViewerMode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getViewerMode ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getViewerMode);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getViewerMode */

#ifndef UNUSED_vrml_external_Browser_getViewpoint
JRIMethodID FAR methodID_vrml_external_Browser_getViewpoint = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Browser_getViewpoint(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getViewpoint == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getViewpoint ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getViewpoint);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getViewpoint */

#ifndef UNUSED_vrml_external_Browser_getCurrentSpeed
JRIMethodID FAR methodID_vrml_external_Browser_getCurrentSpeed = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jfloat)
vrml_external_Browser_getCurrentSpeed(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getCurrentSpeed == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getCurrentSpeed ()F");
	}
	return (jfloat)JRI_CallMethodFloat(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getCurrentSpeed);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getCurrentSpeed */

#ifndef UNUSED_vrml_external_Browser_getCurrentFrameRate
JRIMethodID FAR methodID_vrml_external_Browser_getCurrentFrameRate = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jfloat)
vrml_external_Browser_getCurrentFrameRate(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getCurrentFrameRate == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getCurrentFrameRate ()F");
	}
	return (jfloat)JRI_CallMethodFloat(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getCurrentFrameRate);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getCurrentFrameRate */

#ifndef UNUSED_vrml_external_Browser_getCollisionDetection
JRIMethodID FAR methodID_vrml_external_Browser_getCollisionDetection = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_getCollisionDetection(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getCollisionDetection == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getCollisionDetection ()Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getCollisionDetection);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getCollisionDetection */

#ifndef UNUSED_vrml_external_Browser_getHeadlight
JRIMethodID FAR methodID_vrml_external_Browser_getHeadlight = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_getHeadlight(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getHeadlight == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getHeadlight ()Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getHeadlight);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getHeadlight */

#ifndef UNUSED_vrml_external_Browser_getanimateAllViewpoints
JRIMethodID FAR methodID_vrml_external_Browser_getanimateAllViewpoints = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_getanimateAllViewpoints(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getanimateAllViewpoints == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getanimateAllViewpoints ()Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getanimateAllViewpoints);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getanimateAllViewpoints */

#ifndef UNUSED_vrml_external_Browser_getWorld
JRIMethodID FAR methodID_vrml_external_Browser_getWorld = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Node *)
vrml_external_Browser_getWorld(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getWorld == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getWorld ()Lvrml/external/Node;");
	}
	return (struct vrml_external_Node *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getWorld);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getWorld */

#ifndef UNUSED_vrml_external_Browser_getNode
JRIMethodID FAR methodID_vrml_external_Browser_getNode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Node *)
vrml_external_Browser_getNode(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_getNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getNode (Ljava/lang/String;)Lvrml/external/Node;");
	}
	return (struct vrml_external_Node *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getNode, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getNode */

#ifndef UNUSED_vrml_external_Browser_loadURL
JRIMethodID FAR methodID_vrml_external_Browser_loadURL = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_loadURL(JRIEnv* env, struct vrml_external_Browser* self, jstringArray a, jstringArray b) {
	if (methodID_vrml_external_Browser_loadURL == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method loadURL ([Ljava/lang/String;[Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_loadURL, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_loadURL */

#ifndef UNUSED_vrml_external_Browser_nLoadURL
JRIMethodID FAR methodID_vrml_external_Browser_nLoadURL = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_nLoadURL(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a, struct java_lang_String *b) {
	if (methodID_vrml_external_Browser_nLoadURL == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method nLoadURL (Ljava/lang/String;Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_nLoadURL, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_nLoadURL */

#ifndef UNUSED_vrml_external_Browser_createVrmlFromString
JRIMethodID FAR methodID_vrml_external_Browser_createVrmlFromString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jref)
vrml_external_Browser_createVrmlFromString(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_createVrmlFromString == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method createVrmlFromString (Ljava/lang/String;)[Lvrml/external/Node;");
	}
	return (jref)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_createVrmlFromString, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_createVrmlFromString */

#ifndef UNUSED_vrml_external_Browser_createVrmlFromURL
JRIMethodID FAR methodID_vrml_external_Browser_createVrmlFromURL = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_createVrmlFromURL(JRIEnv* env, struct vrml_external_Browser* self, jstringArray a, struct vrml_external_Node *b, struct java_lang_String *c) {
	if (methodID_vrml_external_Browser_createVrmlFromURL == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method createVrmlFromURL ([Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_createVrmlFromURL, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_createVrmlFromURL */

#ifndef UNUSED_vrml_external_Browser_nCreateVrmlFromURL
JRIMethodID FAR methodID_vrml_external_Browser_nCreateVrmlFromURL = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_nCreateVrmlFromURL(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a, struct vrml_external_Node *b, struct java_lang_String *c) {
	if (methodID_vrml_external_Browser_nCreateVrmlFromURL == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method nCreateVrmlFromURL (Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_nCreateVrmlFromURL, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_nCreateVrmlFromURL */

#ifndef UNUSED_vrml_external_Browser_createNode
JRIMethodID FAR methodID_vrml_external_Browser_createNode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Node *)
vrml_external_Browser_createNode(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_createNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method createNode (Ljava/lang/String;)Lvrml/external/Node;");
	}
	return (struct vrml_external_Node *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_createNode, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_createNode */

#ifndef UNUSED_vrml_external_Browser_addRoute
JRIMethodID FAR methodID_vrml_external_Browser_addRoute = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_addRoute(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a, struct java_lang_String *b, struct vrml_external_Node *c, struct java_lang_String *d) {
	if (methodID_vrml_external_Browser_addRoute == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method addRoute (Lvrml/external/Node;Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_addRoute, a, b, c, d);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_addRoute */

#ifndef UNUSED_vrml_external_Browser_deleteRoute
JRIMethodID FAR methodID_vrml_external_Browser_deleteRoute = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_deleteRoute(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a, struct java_lang_String *b, struct vrml_external_Node *c, struct java_lang_String *d) {
	if (methodID_vrml_external_Browser_deleteRoute == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method deleteRoute (Lvrml/external/Node;Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_deleteRoute, a, b, c, d);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_deleteRoute */

#ifndef UNUSED_vrml_external_Browser_replaceWorld
JRIMethodID FAR methodID_vrml_external_Browser_replaceWorld = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_replaceWorld(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a) {
	if (methodID_vrml_external_Browser_replaceWorld == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method replaceWorld (Lvrml/external/Node;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_replaceWorld, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_replaceWorld */

#ifndef UNUSED_vrml_external_Browser_replaceWorld_1
JRIMethodID FAR methodID_vrml_external_Browser_replaceWorld_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_replaceWorld_1(JRIEnv* env, struct vrml_external_Browser* self, jobjectArray a) {
	if (methodID_vrml_external_Browser_replaceWorld_1 == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method replaceWorld ([Lvrml/external/Node;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_replaceWorld_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_replaceWorld_1 */

#ifndef UNUSED_vrml_external_Browser_addNode
JRIMethodID FAR methodID_vrml_external_Browser_addNode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_addNode(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a) {
	if (methodID_vrml_external_Browser_addNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method addNode (Lvrml/external/Node;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_addNode, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_addNode */

#ifndef UNUSED_vrml_external_Browser_removeNode
JRIMethodID FAR methodID_vrml_external_Browser_removeNode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_removeNode(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a) {
	if (methodID_vrml_external_Browser_removeNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method removeNode (Lvrml/external/Node;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_removeNode, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_removeNode */

#ifndef UNUSED_vrml_external_Browser_setNodeName
JRIMethodID FAR methodID_vrml_external_Browser_setNodeName = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setNodeName(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a, struct java_lang_String *b) {
	if (methodID_vrml_external_Browser_setNodeName == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setNodeName (Lvrml/external/Node;Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setNodeName, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setNodeName */

#ifndef UNUSED_vrml_external_Browser_setDescription
JRIMethodID FAR methodID_vrml_external_Browser_setDescription = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setDescription(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_setDescription == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setDescription (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setDescription, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setDescription */

#ifndef UNUSED_vrml_external_Browser_setViewerMode
JRIMethodID FAR methodID_vrml_external_Browser_setViewerMode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setViewerMode(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_setViewerMode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setViewerMode (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setViewerMode, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setViewerMode */

#ifndef UNUSED_vrml_external_Browser_setViewpoint
JRIMethodID FAR methodID_vrml_external_Browser_setViewpoint = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setViewpoint(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_setViewpoint == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setViewpoint (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setViewpoint, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setViewpoint */

#ifndef UNUSED_vrml_external_Browser_setCollisionDetection
JRIMethodID FAR methodID_vrml_external_Browser_setCollisionDetection = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setCollisionDetection(JRIEnv* env, struct vrml_external_Browser* self, jbool a) {
	if (methodID_vrml_external_Browser_setCollisionDetection == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setCollisionDetection (Z)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setCollisionDetection, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setCollisionDetection */

#ifndef UNUSED_vrml_external_Browser_setHeadlight
JRIMethodID FAR methodID_vrml_external_Browser_setHeadlight = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setHeadlight(JRIEnv* env, struct vrml_external_Browser* self, jbool a) {
	if (methodID_vrml_external_Browser_setHeadlight == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setHeadlight (Z)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setHeadlight, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setHeadlight */

#ifndef UNUSED_vrml_external_Browser_setAnimateAllViewpoints
JRIMethodID FAR methodID_vrml_external_Browser_setAnimateAllViewpoints = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setAnimateAllViewpoints(JRIEnv* env, struct vrml_external_Browser* self, jbool a) {
	if (methodID_vrml_external_Browser_setAnimateAllViewpoints == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setAnimateAllViewpoints (Z)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setAnimateAllViewpoints, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setAnimateAllViewpoints */

#ifndef UNUSED_vrml_external_Browser_setNextViewpoint
JRIMethodID FAR methodID_vrml_external_Browser_setNextViewpoint = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setNextViewpoint(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_setNextViewpoint == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setNextViewpoint ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setNextViewpoint);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setNextViewpoint */

#ifndef UNUSED_vrml_external_Browser_setPrevViewpoint
JRIMethodID FAR methodID_vrml_external_Browser_setPrevViewpoint = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setPrevViewpoint(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_setPrevViewpoint == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setPrevViewpoint ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setPrevViewpoint);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setPrevViewpoint */

#ifndef UNUSED_vrml_external_Browser_beginUpdate
JRIMethodID FAR methodID_vrml_external_Browser_beginUpdate = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_beginUpdate(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_beginUpdate == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method beginUpdate ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_beginUpdate);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_beginUpdate */

#ifndef UNUSED_vrml_external_Browser_endUpdate
JRIMethodID FAR methodID_vrml_external_Browser_endUpdate = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_endUpdate(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_endUpdate == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method endUpdate ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_endUpdate);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_endUpdate */

#ifndef UNUSED_vrml_external_Browser_setTimerInterval
JRIMethodID FAR methodID_vrml_external_Browser_setTimerInterval = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
vrml_external_Browser_setTimerInterval(JRIEnv* env, struct vrml_external_Browser* self, jint a) {
	if (methodID_vrml_external_Browser_setTimerInterval == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setTimerInterval (I)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setTimerInterval, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setTimerInterval */

#ifndef UNUSED_vrml_external_Browser_adviseOnUrlChanged
JRIMethodID FAR methodID_vrml_external_Browser_adviseOnUrlChanged = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_field_EventOut *)
vrml_external_Browser_adviseOnUrlChanged(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_field_EventOutObserver *a, struct java_lang_Object *b) {
	if (methodID_vrml_external_Browser_adviseOnUrlChanged == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method adviseOnUrlChanged (Lvrml/external/field/EventOutObserver;Ljava/lang/Object;)Lvrml/external/field/EventOut;");
	}
	return (struct vrml_external_field_EventOut *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_adviseOnUrlChanged, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_adviseOnUrlChanged */

#ifndef UNUSED_vrml_external_Browser_OnNextViewpoint
JRIMethodID FAR methodID_vrml_external_Browser_OnNextViewpoint = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_OnNextViewpoint(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_OnNextViewpoint == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method OnNextViewpoint ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_OnNextViewpoint);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_OnNextViewpoint */

#ifndef UNUSED_vrml_external_Browser_OnPrevViewpoint
JRIMethodID FAR methodID_vrml_external_Browser_OnPrevViewpoint = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_OnPrevViewpoint(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_OnPrevViewpoint == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method OnPrevViewpoint ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_OnPrevViewpoint);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_OnPrevViewpoint */

#ifndef UNUSED_vrml_external_Browser_isSceneLoaded
JRIMethodID FAR methodID_vrml_external_Browser_isSceneLoaded = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_isSceneLoaded(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_isSceneLoaded == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method isSceneLoaded ()Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_isSceneLoaded);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_isSceneLoaded */

#ifndef UNUSED_vrml_external_Browser_getNodeName
JRIMethodID FAR methodID_vrml_external_Browser_getNodeName = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Browser_getNodeName(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a) {
	if (methodID_vrml_external_Browser_getNodeName == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getNodeName (Lvrml/external/Node;)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getNodeName, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getNodeName */

#ifndef UNUSED_vrml_external_Browser_getEventOut
JRIMethodID FAR methodID_vrml_external_Browser_getEventOut = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_field_EventOut *)
vrml_external_Browser_getEventOut(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_getEventOut == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getEventOut (Ljava/lang/String;)Lvrml/external/field/EventOut;");
	}
	return (struct vrml_external_field_EventOut *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getEventOut, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getEventOut */

#ifndef UNUSED_vrml_external_Browser_getEventIn
JRIMethodID FAR methodID_vrml_external_Browser_getEventIn = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_field_EventIn *)
vrml_external_Browser_getEventIn(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_getEventIn == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getEventIn (Ljava/lang/String;)Lvrml/external/field/EventIn;");
	}
	return (struct vrml_external_field_EventIn *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getEventIn, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getEventIn */

#ifndef UNUSED_vrml_external_Browser_saveWorld
JRIMethodID FAR methodID_vrml_external_Browser_saveWorld = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_saveWorld(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_saveWorld == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method saveWorld (Ljava/lang/String;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_saveWorld, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_saveWorld */

#ifndef UNUSED_vrml_external_Browser_saveViewpoint
JRIMethodID FAR methodID_vrml_external_Browser_saveViewpoint = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_saveViewpoint(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_saveViewpoint == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method saveViewpoint (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_saveViewpoint, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_saveViewpoint */

#ifndef UNUSED_vrml_external_Browser_setFullscreen
JRIMethodID FAR methodID_vrml_external_Browser_setFullscreen = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_setFullscreen(JRIEnv* env, struct vrml_external_Browser* self, jbool a) {
	if (methodID_vrml_external_Browser_setFullscreen == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setFullscreen (Z)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setFullscreen, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setFullscreen */

#ifndef UNUSED_vrml_external_Browser_getUiMode
JRIMethodID FAR methodID_vrml_external_Browser_getUiMode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
vrml_external_Browser_getUiMode(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getUiMode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getUiMode ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getUiMode);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getUiMode */

#ifndef UNUSED_vrml_external_Browser_setUiMode
JRIMethodID FAR methodID_vrml_external_Browser_setUiMode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setUiMode(JRIEnv* env, struct vrml_external_Browser* self, jint a) {
	if (methodID_vrml_external_Browser_setUiMode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setUiMode (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setUiMode, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setUiMode */

#ifndef UNUSED_vrml_external_Browser_openPreferences
JRIMethodID FAR methodID_vrml_external_Browser_openPreferences = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_openPreferences(JRIEnv* env, struct vrml_external_Browser* self, jint a) {
	if (methodID_vrml_external_Browser_openPreferences == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method openPreferences (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_openPreferences, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_openPreferences */

#ifndef UNUSED_vrml_external_Browser_playSound
JRIMethodID FAR methodID_vrml_external_Browser_playSound = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_playSound(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_playSound == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method playSound (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_playSound, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_playSound */

#ifndef UNUSED_vrml_external_Browser_print
JRIMethodID FAR methodID_vrml_external_Browser_print = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_print(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_print == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method print (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_print, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_print */

#ifndef UNUSED_vrml_external_Browser_computeRayHit
JRIMethodID FAR methodID_vrml_external_Browser_computeRayHit = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Node *)
vrml_external_Browser_computeRayHit(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a, jfloatArray b, jfloatArray c, jint d) {
	if (methodID_vrml_external_Browser_computeRayHit == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method computeRayHit (Lvrml/external/Node;[F[FI)Lvrml/external/Node;");
	}
	return (struct vrml_external_Node *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_computeRayHit, a, b, c, d);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_computeRayHit */

#ifndef UNUSED_vrml_external_Browser_setViewpointByValue
JRIMethodID FAR methodID_vrml_external_Browser_setViewpointByValue = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setViewpointByValue(JRIEnv* env, struct vrml_external_Browser* self, jfloatArray a, jfloatArray b, jint c) {
	if (methodID_vrml_external_Browser_setViewpointByValue == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setViewpointByValue ([F[FI)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setViewpointByValue, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setViewpointByValue */

#ifndef UNUSED_vrml_external_Browser_getViewpointByValue
JRIMethodID FAR methodID_vrml_external_Browser_getViewpointByValue = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_getViewpointByValue(JRIEnv* env, struct vrml_external_Browser* self, jfloatArray a, jfloatArray b, jint c) {
	if (methodID_vrml_external_Browser_getViewpointByValue == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getViewpointByValue ([F[FI)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getViewpointByValue, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getViewpointByValue */

#ifndef UNUSED_vrml_external_Browser_getNodeBoundingBox
JRIMethodID FAR methodID_vrml_external_Browser_getNodeBoundingBox = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_getNodeBoundingBox(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a, jint b, jfloatArray c, jfloatArray d) {
	if (methodID_vrml_external_Browser_getNodeBoundingBox == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getNodeBoundingBox (Lvrml/external/Node;I[F[F)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getNodeBoundingBox, a, b, c, d);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getNodeBoundingBox */

#ifndef UNUSED_vrml_external_Browser_setThirdPersonView
JRIMethodID FAR methodID_vrml_external_Browser_setThirdPersonView = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setThirdPersonView(JRIEnv* env, struct vrml_external_Browser* self, jbool a) {
	if (methodID_vrml_external_Browser_setThirdPersonView == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setThirdPersonView (Z)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setThirdPersonView, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setThirdPersonView */

#ifndef UNUSED_vrml_external_Browser_getThirdPersonView
JRIMethodID FAR methodID_vrml_external_Browser_getThirdPersonView = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_getThirdPersonView(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getThirdPersonView == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getThirdPersonView ()Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getThirdPersonView);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getThirdPersonView */

#ifndef UNUSED_vrml_external_Browser_setMyAvatarNode
JRIMethodID FAR methodID_vrml_external_Browser_setMyAvatarNode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setMyAvatarNode(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a) {
	if (methodID_vrml_external_Browser_setMyAvatarNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setMyAvatarNode (Lvrml/external/Node;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setMyAvatarNode, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setMyAvatarNode */

#ifndef UNUSED_vrml_external_Browser_getMyAvatarNode
JRIMethodID FAR methodID_vrml_external_Browser_getMyAvatarNode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Node *)
vrml_external_Browser_getMyAvatarNode(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getMyAvatarNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getMyAvatarNode ()Lvrml/external/Node;");
	}
	return (struct vrml_external_Node *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getMyAvatarNode);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getMyAvatarNode */

#ifndef UNUSED_vrml_external_Browser_setMyAvatarURL
JRIMethodID FAR methodID_vrml_external_Browser_setMyAvatarURL = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser_setMyAvatarURL(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a) {
	if (methodID_vrml_external_Browser_setMyAvatarURL == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setMyAvatarURL (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setMyAvatarURL, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setMyAvatarURL */

#ifndef UNUSED_vrml_external_Browser_getMyAvatarURL
JRIMethodID FAR methodID_vrml_external_Browser_getMyAvatarURL = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Browser_getMyAvatarURL(JRIEnv* env, struct vrml_external_Browser* self) {
	if (methodID_vrml_external_Browser_getMyAvatarURL == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getMyAvatarURL ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getMyAvatarURL);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getMyAvatarURL */

#ifndef UNUSED_vrml_external_Browser_setViewpointFollow
JRIMethodID FAR methodID_vrml_external_Browser_setViewpointFollow = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_setViewpointFollow(JRIEnv* env, struct vrml_external_Browser* self, struct vrml_external_Node *a, jfloatArray b, jint c) {
	if (methodID_vrml_external_Browser_setViewpointFollow == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setViewpointFollow (Lvrml/external/Node;[FI)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setViewpointFollow, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setViewpointFollow */

#ifndef UNUSED_vrml_external_Browser_setNodeEventIn
JRIMethodID FAR methodID_vrml_external_Browser_setNodeEventIn = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_Browser_setNodeEventIn(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a, struct java_lang_String *b, struct java_lang_String *c) {
	if (methodID_vrml_external_Browser_setNodeEventIn == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method setNodeEventIn (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_setNodeEventIn, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_setNodeEventIn */

#ifndef UNUSED_vrml_external_Browser_getNodeEventOut
JRIMethodID FAR methodID_vrml_external_Browser_getNodeEventOut = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_Browser_getNodeEventOut(JRIEnv* env, struct vrml_external_Browser* self, struct java_lang_String *a, struct java_lang_String *b) {
	if (methodID_vrml_external_Browser_getNodeEventOut == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getNodeEventOut (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getNodeEventOut, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getNodeEventOut */

#ifndef UNUSED_vrml_external_Browser_getObject
JRIMethodID FAR methodID_vrml_external_Browser_getObject = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
vrml_external_Browser_getObject(JRIEnv* env, struct vrml_external_Browser* self, jint a) {
	if (methodID_vrml_external_Browser_getObject == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method getObject (I)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_Browser_getObject, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser_getObject */

#ifndef UNUSED_vrml_external_Browser__0003cclinit_0003e
JRIMethodID FAR methodID_vrml_external_Browser__0003cclinit_0003e = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_Browser__0003cclinit_0003e(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_vrml_external_Browser__0003cclinit_0003e == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_Browser(env) before calling method <clinit> ()V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_vrml_external_Browser__0003cclinit_0003e);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_Browser__0003cclinit_0003e */

#ifndef UNUSED_use_vrml_external_Browser

static jglobal _globalclass_vrml_external_Browser = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_vrml_external_Browser(JRIEnv* env)
{
	if (_globalclass_vrml_external_Browser == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_Browser);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_Browser);
			return NULL;
		}
		use_vrml_external_Browser_obsEvents(env, clazz);
		use_vrml_external_Browser_theBrowser(env, clazz);
		use_vrml_external_Browser_new(env, clazz);
		use_vrml_external_Browser_setBrowser(env, clazz);
		use_vrml_external_Browser_init(env, clazz);
		use_vrml_external_Browser_destroy(env, clazz);
		use_vrml_external_Browser_getBrowser(env, clazz);
		use_vrml_external_Browser_getBrowser_1(env, clazz);
		use_vrml_external_Browser_getBrowser_2(env, clazz);
		use_vrml_external_Browser_getString(env, clazz);
		use_vrml_external_Browser_getBoolean(env, clazz);
		use_vrml_external_Browser_setString(env, clazz);
		use_vrml_external_Browser_setBoolean(env, clazz);
		use_vrml_external_Browser_addObserver(env, clazz);
		use_vrml_external_Browser_getName(env, clazz);
		use_vrml_external_Browser_getVersion(env, clazz);
		use_vrml_external_Browser_getWorldURL(env, clazz);
		use_vrml_external_Browser_getViewerMode(env, clazz);
		use_vrml_external_Browser_getViewpoint(env, clazz);
		use_vrml_external_Browser_getCurrentSpeed(env, clazz);
		use_vrml_external_Browser_getCurrentFrameRate(env, clazz);
		use_vrml_external_Browser_getCollisionDetection(env, clazz);
		use_vrml_external_Browser_getHeadlight(env, clazz);
		use_vrml_external_Browser_getanimateAllViewpoints(env, clazz);
		use_vrml_external_Browser_getWorld(env, clazz);
		use_vrml_external_Browser_getNode(env, clazz);
		use_vrml_external_Browser_loadURL(env, clazz);
		use_vrml_external_Browser_nLoadURL(env, clazz);
		use_vrml_external_Browser_createVrmlFromString(env, clazz);
		use_vrml_external_Browser_createVrmlFromURL(env, clazz);
		use_vrml_external_Browser_nCreateVrmlFromURL(env, clazz);
		use_vrml_external_Browser_createNode(env, clazz);
		use_vrml_external_Browser_addRoute(env, clazz);
		use_vrml_external_Browser_deleteRoute(env, clazz);
		use_vrml_external_Browser_replaceWorld(env, clazz);
		use_vrml_external_Browser_replaceWorld_1(env, clazz);
		use_vrml_external_Browser_addNode(env, clazz);
		use_vrml_external_Browser_removeNode(env, clazz);
		use_vrml_external_Browser_setNodeName(env, clazz);
		use_vrml_external_Browser_setDescription(env, clazz);
		use_vrml_external_Browser_setViewerMode(env, clazz);
		use_vrml_external_Browser_setViewpoint(env, clazz);
		use_vrml_external_Browser_setCollisionDetection(env, clazz);
		use_vrml_external_Browser_setHeadlight(env, clazz);
		use_vrml_external_Browser_setAnimateAllViewpoints(env, clazz);
		use_vrml_external_Browser_setNextViewpoint(env, clazz);
		use_vrml_external_Browser_setPrevViewpoint(env, clazz);
		use_vrml_external_Browser_beginUpdate(env, clazz);
		use_vrml_external_Browser_endUpdate(env, clazz);
		use_vrml_external_Browser_setTimerInterval(env, clazz);
		use_vrml_external_Browser_adviseOnUrlChanged(env, clazz);
		use_vrml_external_Browser_OnNextViewpoint(env, clazz);
		use_vrml_external_Browser_OnPrevViewpoint(env, clazz);
		use_vrml_external_Browser_isSceneLoaded(env, clazz);
		use_vrml_external_Browser_getNodeName(env, clazz);
		use_vrml_external_Browser_getEventOut(env, clazz);
		use_vrml_external_Browser_getEventIn(env, clazz);
		use_vrml_external_Browser_saveWorld(env, clazz);
		use_vrml_external_Browser_saveViewpoint(env, clazz);
		use_vrml_external_Browser_setFullscreen(env, clazz);
		use_vrml_external_Browser_getUiMode(env, clazz);
		use_vrml_external_Browser_setUiMode(env, clazz);
		use_vrml_external_Browser_openPreferences(env, clazz);
		use_vrml_external_Browser_playSound(env, clazz);
		use_vrml_external_Browser_print(env, clazz);
		use_vrml_external_Browser_computeRayHit(env, clazz);
		use_vrml_external_Browser_setViewpointByValue(env, clazz);
		use_vrml_external_Browser_getViewpointByValue(env, clazz);
		use_vrml_external_Browser_getNodeBoundingBox(env, clazz);
		use_vrml_external_Browser_setThirdPersonView(env, clazz);
		use_vrml_external_Browser_getThirdPersonView(env, clazz);
		use_vrml_external_Browser_setMyAvatarNode(env, clazz);
		use_vrml_external_Browser_getMyAvatarNode(env, clazz);
		use_vrml_external_Browser_setMyAvatarURL(env, clazz);
		use_vrml_external_Browser_getMyAvatarURL(env, clazz);
		use_vrml_external_Browser_setViewpointFollow(env, clazz);
		use_vrml_external_Browser_setNodeEventIn(env, clazz);
		use_vrml_external_Browser_getNodeEventOut(env, clazz);
		use_vrml_external_Browser_getObject(env, clazz);
		use_vrml_external_Browser__0003cclinit_0003e(env, clazz);
		_globalclass_vrml_external_Browser = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_Browser);
	}
}

JRI_PUBLIC_API(void)
unuse_vrml_external_Browser(JRIEnv* env)
{
	if (_globalclass_vrml_external_Browser != NULL) {
		struct java_lang_Class* clazz = (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_Browser);
		unuse_vrml_external_Browser_obsEvents(env, clazz);
		unuse_vrml_external_Browser_theBrowser(env, clazz);
		unuse_vrml_external_Browser_new(env, clazz);
		unuse_vrml_external_Browser_setBrowser(env, clazz);
		unuse_vrml_external_Browser_init(env, clazz);
		unuse_vrml_external_Browser_destroy(env, clazz);
		unuse_vrml_external_Browser_getBrowser(env, clazz);
		unuse_vrml_external_Browser_getBrowser_1(env, clazz);
		unuse_vrml_external_Browser_getBrowser_2(env, clazz);
		unuse_vrml_external_Browser_getString(env, clazz);
		unuse_vrml_external_Browser_getBoolean(env, clazz);
		unuse_vrml_external_Browser_setString(env, clazz);
		unuse_vrml_external_Browser_setBoolean(env, clazz);
		unuse_vrml_external_Browser_addObserver(env, clazz);
		unuse_vrml_external_Browser_getName(env, clazz);
		unuse_vrml_external_Browser_getVersion(env, clazz);
		unuse_vrml_external_Browser_getWorldURL(env, clazz);
		unuse_vrml_external_Browser_getViewerMode(env, clazz);
		unuse_vrml_external_Browser_getViewpoint(env, clazz);
		unuse_vrml_external_Browser_getCurrentSpeed(env, clazz);
		unuse_vrml_external_Browser_getCurrentFrameRate(env, clazz);
		unuse_vrml_external_Browser_getCollisionDetection(env, clazz);
		unuse_vrml_external_Browser_getHeadlight(env, clazz);
		unuse_vrml_external_Browser_getanimateAllViewpoints(env, clazz);
		unuse_vrml_external_Browser_getWorld(env, clazz);
		unuse_vrml_external_Browser_getNode(env, clazz);
		unuse_vrml_external_Browser_loadURL(env, clazz);
		unuse_vrml_external_Browser_nLoadURL(env, clazz);
		unuse_vrml_external_Browser_createVrmlFromString(env, clazz);
		unuse_vrml_external_Browser_createVrmlFromURL(env, clazz);
		unuse_vrml_external_Browser_nCreateVrmlFromURL(env, clazz);
		unuse_vrml_external_Browser_createNode(env, clazz);
		unuse_vrml_external_Browser_addRoute(env, clazz);
		unuse_vrml_external_Browser_deleteRoute(env, clazz);
		unuse_vrml_external_Browser_replaceWorld(env, clazz);
		unuse_vrml_external_Browser_replaceWorld_1(env, clazz);
		unuse_vrml_external_Browser_addNode(env, clazz);
		unuse_vrml_external_Browser_removeNode(env, clazz);
		unuse_vrml_external_Browser_setNodeName(env, clazz);
		unuse_vrml_external_Browser_setDescription(env, clazz);
		unuse_vrml_external_Browser_setViewerMode(env, clazz);
		unuse_vrml_external_Browser_setViewpoint(env, clazz);
		unuse_vrml_external_Browser_setCollisionDetection(env, clazz);
		unuse_vrml_external_Browser_setHeadlight(env, clazz);
		unuse_vrml_external_Browser_setAnimateAllViewpoints(env, clazz);
		unuse_vrml_external_Browser_setNextViewpoint(env, clazz);
		unuse_vrml_external_Browser_setPrevViewpoint(env, clazz);
		unuse_vrml_external_Browser_beginUpdate(env, clazz);
		unuse_vrml_external_Browser_endUpdate(env, clazz);
		unuse_vrml_external_Browser_setTimerInterval(env, clazz);
		unuse_vrml_external_Browser_adviseOnUrlChanged(env, clazz);
		unuse_vrml_external_Browser_OnNextViewpoint(env, clazz);
		unuse_vrml_external_Browser_OnPrevViewpoint(env, clazz);
		unuse_vrml_external_Browser_isSceneLoaded(env, clazz);
		unuse_vrml_external_Browser_getNodeName(env, clazz);
		unuse_vrml_external_Browser_getEventOut(env, clazz);
		unuse_vrml_external_Browser_getEventIn(env, clazz);
		unuse_vrml_external_Browser_saveWorld(env, clazz);
		unuse_vrml_external_Browser_saveViewpoint(env, clazz);
		unuse_vrml_external_Browser_setFullscreen(env, clazz);
		unuse_vrml_external_Browser_getUiMode(env, clazz);
		unuse_vrml_external_Browser_setUiMode(env, clazz);
		unuse_vrml_external_Browser_openPreferences(env, clazz);
		unuse_vrml_external_Browser_playSound(env, clazz);
		unuse_vrml_external_Browser_print(env, clazz);
		unuse_vrml_external_Browser_computeRayHit(env, clazz);
		unuse_vrml_external_Browser_setViewpointByValue(env, clazz);
		unuse_vrml_external_Browser_getViewpointByValue(env, clazz);
		unuse_vrml_external_Browser_getNodeBoundingBox(env, clazz);
		unuse_vrml_external_Browser_setThirdPersonView(env, clazz);
		unuse_vrml_external_Browser_getThirdPersonView(env, clazz);
		unuse_vrml_external_Browser_setMyAvatarNode(env, clazz);
		unuse_vrml_external_Browser_getMyAvatarNode(env, clazz);
		unuse_vrml_external_Browser_setMyAvatarURL(env, clazz);
		unuse_vrml_external_Browser_getMyAvatarURL(env, clazz);
		unuse_vrml_external_Browser_setViewpointFollow(env, clazz);
		unuse_vrml_external_Browser_setNodeEventIn(env, clazz);
		unuse_vrml_external_Browser_getNodeEventOut(env, clazz);
		unuse_vrml_external_Browser_getObject(env, clazz);
		unuse_vrml_external_Browser__0003cclinit_0003e(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_vrml_external_Browser);
		_globalclass_vrml_external_Browser = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_vrml_external_Browser */

#ifdef _implementing_vrml_external_Browser

JRI_PUBLIC_API(struct java_lang_Class*)
register_vrml_external_Browser(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"getString(I)Ljava/lang/String;",
		"getBoolean(I)Z",
		"setString(ILjava/lang/String;)V",
		"setBoolean(IZ)V",
		"getCurrentSpeed()F",
		"getCurrentFrameRate()F",
		"getWorld()Lvrml/external/Node;",
		"getNode(Ljava/lang/String;)Lvrml/external/Node;",
		"nLoadURL(Ljava/lang/String;Ljava/lang/String;)V",
		"createVrmlFromString(Ljava/lang/String;)[Lvrml/external/Node;",
		"nCreateVrmlFromURL(Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V",
		"createNode(Ljava/lang/String;)Lvrml/external/Node;",
		"addRoute(Lvrml/external/Node;Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V",
		"deleteRoute(Lvrml/external/Node;Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V",
		"replaceWorld(Lvrml/external/Node;)V",
		"addNode(Lvrml/external/Node;)V",
		"removeNode(Lvrml/external/Node;)Z",
		"setNodeName(Lvrml/external/Node;Ljava/lang/String;)V",
		"setTimerInterval(I)I",
		"adviseOnUrlChanged(Lvrml/external/field/EventOutObserver;Ljava/lang/Object;)Lvrml/external/field/EventOut;",
		"getNodeName(Lvrml/external/Node;)Ljava/lang/String;",
		"getEventOut(Ljava/lang/String;)Lvrml/external/field/EventOut;",
		"getEventIn(Ljava/lang/String;)Lvrml/external/field/EventIn;",
		"saveWorld(Ljava/lang/String;)Z",
		"setFullscreen(Z)Z",
		"getUiMode()I",
		"setUiMode(I)V",
		"openPreferences(I)V",
		"computeRayHit(Lvrml/external/Node;[F[FI)Lvrml/external/Node;",
		"setViewpointByValue([F[FI)V",
		"getViewpointByValue([F[FI)V",
		"getNodeBoundingBox(Lvrml/external/Node;I[F[F)Z",
		"setMyAvatarNode(Lvrml/external/Node;)V",
		"getMyAvatarNode()Lvrml/external/Node;",
		"setViewpointFollow(Lvrml/external/Node;[FI)Z",
		"setNodeEventIn(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z",
		"getNodeEventOut(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
		"getObject(I)I",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_vrml_external_Browser_getString,
		(void*)native_vrml_external_Browser_getBoolean,
		(void*)native_vrml_external_Browser_setString,
		(void*)native_vrml_external_Browser_setBoolean,
		(void*)native_vrml_external_Browser_getCurrentSpeed,
		(void*)native_vrml_external_Browser_getCurrentFrameRate,
		(void*)native_vrml_external_Browser_getWorld,
		(void*)native_vrml_external_Browser_getNode,
		(void*)native_vrml_external_Browser_nLoadURL,
		(void*)native_vrml_external_Browser_createVrmlFromString,
		(void*)native_vrml_external_Browser_nCreateVrmlFromURL,
		(void*)native_vrml_external_Browser_createNode,
		(void*)native_vrml_external_Browser_addRoute,
		(void*)native_vrml_external_Browser_deleteRoute,
		(void*)native_vrml_external_Browser_replaceWorld,
		(void*)native_vrml_external_Browser_addNode,
		(void*)native_vrml_external_Browser_removeNode,
		(void*)native_vrml_external_Browser_setNodeName,
		(void*)native_vrml_external_Browser_setTimerInterval,
		(void*)native_vrml_external_Browser_adviseOnUrlChanged,
		(void*)native_vrml_external_Browser_getNodeName,
		(void*)native_vrml_external_Browser_getEventOut,
		(void*)native_vrml_external_Browser_getEventIn,
		(void*)native_vrml_external_Browser_saveWorld,
		(void*)native_vrml_external_Browser_setFullscreen,
		(void*)native_vrml_external_Browser_getUiMode,
		(void*)native_vrml_external_Browser_setUiMode,
		(void*)native_vrml_external_Browser_openPreferences,
		(void*)native_vrml_external_Browser_computeRayHit,
		(void*)native_vrml_external_Browser_setViewpointByValue,
		(void*)native_vrml_external_Browser_getViewpointByValue,
		(void*)native_vrml_external_Browser_getNodeBoundingBox,
		(void*)native_vrml_external_Browser_setMyAvatarNode,
		(void*)native_vrml_external_Browser_getMyAvatarNode,
		(void*)native_vrml_external_Browser_setViewpointFollow,
		(void*)native_vrml_external_Browser_setNodeEventIn,
		(void*)native_vrml_external_Browser_getNodeEventOut,
		(void*)native_vrml_external_Browser_getObject,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_Browser);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_Browser);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_vrml_external_Browser(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_vrml_external_Browser(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_Browser);
	JRI_UnregisterNatives(env, clazz);
	unuse_vrml_external_Browser(env);
}

#endif /* _implementing_vrml_external_Browser */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

/* SYMBOL: "vrml/external/Browser/getString(I)Ljava/lang/String;", Java_vrml_external_Browser_getString_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getString_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_getString(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getBoolean(I)Z", Java_vrml_external_Browser_getBoolean_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getBoolean_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = (native_vrml_external_Browser_getBoolean(_EE_,_P_[0].p,((_P_[1].i))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/setString(ILjava/lang/String;)V", Java_vrml_external_Browser_setString_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setString_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_setString(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/setBoolean(IZ)V", Java_vrml_external_Browser_setBoolean_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setBoolean_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_setBoolean(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].i)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/getCurrentSpeed()F", Java_vrml_external_Browser_getCurrentSpeed_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getCurrentSpeed_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].f = native_vrml_external_Browser_getCurrentSpeed(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getCurrentFrameRate()F", Java_vrml_external_Browser_getCurrentFrameRate_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getCurrentFrameRate_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].f = native_vrml_external_Browser_getCurrentFrameRate(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getWorld()Lvrml/external/Node;", Java_vrml_external_Browser_getWorld_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getWorld_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_getWorld(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getNode(Ljava/lang/String;)Lvrml/external/Node;", Java_vrml_external_Browser_getNode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getNode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_getNode(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/nLoadURL(Ljava/lang/String;Ljava/lang/String;)V", Java_vrml_external_Browser_nLoadURL_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_nLoadURL_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_nLoadURL(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/createVrmlFromString(Ljava/lang/String;)[Lvrml/external/Node;", Java_vrml_external_Browser_createVrmlFromString_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_createVrmlFromString_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_createVrmlFromString(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/nCreateVrmlFromURL(Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V", Java_vrml_external_Browser_nCreateVrmlFromURL_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_nCreateVrmlFromURL_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_nCreateVrmlFromURL(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/createNode(Ljava/lang/String;)Lvrml/external/Node;", Java_vrml_external_Browser_createNode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_createNode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_createNode(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/addRoute(Lvrml/external/Node;Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V", Java_vrml_external_Browser_addRoute_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_addRoute_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_addRoute(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].p)),((_P_[4].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/deleteRoute(Lvrml/external/Node;Ljava/lang/String;Lvrml/external/Node;Ljava/lang/String;)V", Java_vrml_external_Browser_deleteRoute_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_deleteRoute_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_deleteRoute(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].p)),((_P_[4].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/replaceWorld(Lvrml/external/Node;)V", Java_vrml_external_Browser_replaceWorld_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_replaceWorld_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_replaceWorld(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/addNode(Lvrml/external/Node;)V", Java_vrml_external_Browser_addNode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_addNode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_addNode(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/removeNode(Lvrml/external/Node;)Z", Java_vrml_external_Browser_removeNode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_removeNode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = (native_vrml_external_Browser_removeNode(_EE_,_P_[0].p,((_P_[1].p))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/setNodeName(Lvrml/external/Node;Ljava/lang/String;)V", Java_vrml_external_Browser_setNodeName_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setNodeName_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_setNodeName(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/setTimerInterval(I)I", Java_vrml_external_Browser_setTimerInterval_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setTimerInterval_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = native_vrml_external_Browser_setTimerInterval(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/adviseOnUrlChanged(Lvrml/external/field/EventOutObserver;Ljava/lang/Object;)Lvrml/external/field/EventOut;", Java_vrml_external_Browser_adviseOnUrlChanged_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_adviseOnUrlChanged_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_adviseOnUrlChanged(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getNodeName(Lvrml/external/Node;)Ljava/lang/String;", Java_vrml_external_Browser_getNodeName_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getNodeName_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_getNodeName(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getEventOut(Ljava/lang/String;)Lvrml/external/field/EventOut;", Java_vrml_external_Browser_getEventOut_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getEventOut_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_getEventOut(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getEventIn(Ljava/lang/String;)Lvrml/external/field/EventIn;", Java_vrml_external_Browser_getEventIn_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getEventIn_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_getEventIn(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/saveWorld(Ljava/lang/String;)Z", Java_vrml_external_Browser_saveWorld_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_saveWorld_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = (native_vrml_external_Browser_saveWorld(_EE_,_P_[0].p,((_P_[1].p))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/setFullscreen(Z)Z", Java_vrml_external_Browser_setFullscreen_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setFullscreen_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = (native_vrml_external_Browser_setFullscreen(_EE_,_P_[0].p,((_P_[1].i))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getUiMode()I", Java_vrml_external_Browser_getUiMode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getUiMode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = native_vrml_external_Browser_getUiMode(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/setUiMode(I)V", Java_vrml_external_Browser_setUiMode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setUiMode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_setUiMode(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/openPreferences(I)V", Java_vrml_external_Browser_openPreferences_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_openPreferences_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_openPreferences(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/computeRayHit(Lvrml/external/Node;[F[FI)Lvrml/external/Node;", Java_vrml_external_Browser_computeRayHit_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_computeRayHit_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_computeRayHit(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].p)),((_P_[4].i)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/setViewpointByValue([F[FI)V", Java_vrml_external_Browser_setViewpointByValue_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setViewpointByValue_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_setViewpointByValue(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].i)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/getViewpointByValue([F[FI)V", Java_vrml_external_Browser_getViewpointByValue_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getViewpointByValue_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_getViewpointByValue(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].i)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/getNodeBoundingBox(Lvrml/external/Node;I[F[F)Z", Java_vrml_external_Browser_getNodeBoundingBox_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getNodeBoundingBox_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = (native_vrml_external_Browser_getNodeBoundingBox(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].p)),((_P_[4].p))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/setMyAvatarNode(Lvrml/external/Node;)V", Java_vrml_external_Browser_setMyAvatarNode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setMyAvatarNode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_Browser_setMyAvatarNode(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/Browser/getMyAvatarNode()Lvrml/external/Node;", Java_vrml_external_Browser_getMyAvatarNode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getMyAvatarNode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_getMyAvatarNode(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/setViewpointFollow(Lvrml/external/Node;[FI)Z", Java_vrml_external_Browser_setViewpointFollow_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setViewpointFollow_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = (native_vrml_external_Browser_setViewpointFollow(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].i))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/setNodeEventIn(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z", Java_vrml_external_Browser_setNodeEventIn_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_setNodeEventIn_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = (native_vrml_external_Browser_setNodeEventIn(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].p))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getNodeEventOut(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", Java_vrml_external_Browser_getNodeEventOut_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getNodeEventOut_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_Browser_getNodeEventOut(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/Browser/getObject(I)I", Java_vrml_external_Browser_getObject_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_Browser_getObject_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = native_vrml_external_Browser_getObject(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_ + 1;
}

#endif /* NO_JDK */

