/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class vrml/external/field/EventOut */

#ifdef IMPLEMENT_vrml_external_field_EventOut
#define _implementing_vrml_external_field_EventOut
#endif /* IMPLEMENT_vrml_external_field_EventOut */
#define IMPLEMENT_vrml_external_field_EventOut
#include "vrml_external_field_EventOut.h"

#ifndef UNUSED_vrml_external_field_EventOut_cBrowser
JRIFieldID FAR fieldID_vrml_external_field_EventOut_cBrowser = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_vrml_external_field_EventOut_cBrowser(JRIEnv* env, struct vrml_external_field_EventOut* obj) {
	if (fieldID_vrml_external_field_EventOut_cBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field cBrowser I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_cBrowser);
}
JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_cBrowser(JRIEnv* env, struct vrml_external_field_EventOut* obj, jint v) {
	if (fieldID_vrml_external_field_EventOut_cBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field cBrowser I");
	}
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_cBrowser, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_cBrowser */

#ifndef UNUSED_vrml_external_field_EventOut_cEvent
JRIFieldID FAR fieldID_vrml_external_field_EventOut_cEvent = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_vrml_external_field_EventOut_cEvent(JRIEnv* env, struct vrml_external_field_EventOut* obj) {
	if (fieldID_vrml_external_field_EventOut_cEvent == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field cEvent I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_cEvent);
}
JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_cEvent(JRIEnv* env, struct vrml_external_field_EventOut* obj, jint v) {
	if (fieldID_vrml_external_field_EventOut_cEvent == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field cEvent I");
	}
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_cEvent, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_cEvent */

#ifndef UNUSED_vrml_external_field_EventOut_type
JRIFieldID FAR fieldID_vrml_external_field_EventOut_type = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_vrml_external_field_EventOut_type(JRIEnv* env, struct vrml_external_field_EventOut* obj) {
	if (fieldID_vrml_external_field_EventOut_type == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field type I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_type);
}
JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_type(JRIEnv* env, struct vrml_external_field_EventOut* obj, jint v) {
	if (fieldID_vrml_external_field_EventOut_type == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field type I");
	}
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventOut_type, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_type */

#ifndef UNUSED_vrml_external_field_EventOut_userData
JRIFieldID FAR fieldID_vrml_external_field_EventOut_userData = JRIUninitialized;
#ifdef DEBUG
struct java_lang_Object;
JRI_PUBLIC_API(struct java_lang_Object *)
get_vrml_external_field_EventOut_userData(JRIEnv* env, struct vrml_external_field_EventOut* obj) {
	if (fieldID_vrml_external_field_EventOut_userData == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field userData Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)
		JRI_GetField(env, obj, fieldID_vrml_external_field_EventOut_userData);
}
JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_userData(JRIEnv* env, struct vrml_external_field_EventOut* obj, struct java_lang_Object * v) {
	if (fieldID_vrml_external_field_EventOut_userData == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field userData Ljava/lang/Object;");
	}
	JRI_SetField(env, obj, fieldID_vrml_external_field_EventOut_userData, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_userData */

#ifndef UNUSED_vrml_external_field_EventOut_observer
JRIFieldID FAR fieldID_vrml_external_field_EventOut_observer = JRIUninitialized;
#ifdef DEBUG
struct vrml_external_field_EventOutObserver;
JRI_PUBLIC_API(struct vrml_external_field_EventOutObserver *)
get_vrml_external_field_EventOut_observer(JRIEnv* env, struct vrml_external_field_EventOut* obj) {
	if (fieldID_vrml_external_field_EventOut_observer == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field observer Lvrml/external/field/EventOutObserver;");
	}
	return (struct vrml_external_field_EventOutObserver *)
		JRI_GetField(env, obj, fieldID_vrml_external_field_EventOut_observer);
}
JRI_PUBLIC_API(void)
set_vrml_external_field_EventOut_observer(JRIEnv* env, struct vrml_external_field_EventOut* obj, struct vrml_external_field_EventOutObserver * v) {
	if (fieldID_vrml_external_field_EventOut_observer == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before accessing field observer Lvrml/external/field/EventOutObserver;");
	}
	JRI_SetField(env, obj, fieldID_vrml_external_field_EventOut_observer, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_observer */

#ifndef UNUSED_vrml_external_field_EventOut_new
JRIMethodID FAR methodID_vrml_external_field_EventOut_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_field_EventOut*)
vrml_external_field_EventOut_new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
	if (methodID_vrml_external_field_EventOut_new == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method <init> (III)V");
	}
	return (struct vrml_external_field_EventOut*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_vrml_external_field_EventOut_new, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_new */

#ifndef UNUSED_vrml_external_field_EventOut_getType
JRIMethodID FAR methodID_vrml_external_field_EventOut_getType = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
vrml_external_field_EventOut_getType(JRIEnv* env, struct vrml_external_field_EventOut* self) {
	if (methodID_vrml_external_field_EventOut_getType == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method getType ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_getType);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_getType */

#ifndef UNUSED_vrml_external_field_EventOut_advise
JRIMethodID FAR methodID_vrml_external_field_EventOut_advise = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_advise(JRIEnv* env, struct vrml_external_field_EventOut* self, struct vrml_external_field_EventOutObserver *a, struct java_lang_Object *b) {
	if (methodID_vrml_external_field_EventOut_advise == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method advise (Lvrml/external/field/EventOutObserver;Ljava/lang/Object;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_advise, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_advise */

#ifndef UNUSED_vrml_external_field_EventOut_advise_1
JRIMethodID FAR methodID_vrml_external_field_EventOut_advise_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_advise_1(JRIEnv* env, struct vrml_external_field_EventOut* self) {
	if (methodID_vrml_external_field_EventOut_advise_1 == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method advise ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_advise_1);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_advise_1 */

#ifndef UNUSED_vrml_external_field_EventOut_callback
JRIMethodID FAR methodID_vrml_external_field_EventOut_callback = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_callback(JRIEnv* env, struct vrml_external_field_EventOut* self, jdouble a) {
	if (methodID_vrml_external_field_EventOut_callback == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method callback (D)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_callback, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_callback */

#ifndef UNUSED_vrml_external_field_EventOut_getString
JRIMethodID FAR methodID_vrml_external_field_EventOut_getString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getString(JRIEnv* env, struct vrml_external_field_EventOut* self, jstringArray a) {
	if (methodID_vrml_external_field_EventOut_getString == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method getString ([Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_getString, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_getString */

#ifndef UNUSED_vrml_external_field_EventOut_get1String
JRIMethodID FAR methodID_vrml_external_field_EventOut_get1String = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
vrml_external_field_EventOut_get1String(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a) {
	if (methodID_vrml_external_field_EventOut_get1String == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method get1String (I)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_get1String, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_get1String */

#ifndef UNUSED_vrml_external_field_EventOut_getNode
JRIMethodID FAR methodID_vrml_external_field_EventOut_getNode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getNode(JRIEnv* env, struct vrml_external_field_EventOut* self, jobjectArray a) {
	if (methodID_vrml_external_field_EventOut_getNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method getNode ([Lvrml/external/Node;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_getNode, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_getNode */

#ifndef UNUSED_vrml_external_field_EventOut_get1Node
JRIMethodID FAR methodID_vrml_external_field_EventOut_get1Node = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_Node *)
vrml_external_field_EventOut_get1Node(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a) {
	if (methodID_vrml_external_field_EventOut_get1Node == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method get1Node (I)Lvrml/external/Node;");
	}
	return (struct vrml_external_Node *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_get1Node, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_get1Node */

#ifndef UNUSED_vrml_external_field_EventOut_getInt
JRIMethodID FAR methodID_vrml_external_field_EventOut_getInt = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getInt(JRIEnv* env, struct vrml_external_field_EventOut* self, jintArray a) {
	if (methodID_vrml_external_field_EventOut_getInt == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method getInt ([I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_getInt, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_getInt */

#ifndef UNUSED_vrml_external_field_EventOut_get1Int
JRIMethodID FAR methodID_vrml_external_field_EventOut_get1Int = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
vrml_external_field_EventOut_get1Int(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a) {
	if (methodID_vrml_external_field_EventOut_get1Int == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method get1Int (I)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_get1Int, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_get1Int */

#ifndef UNUSED_vrml_external_field_EventOut_getFloat
JRIMethodID FAR methodID_vrml_external_field_EventOut_getFloat = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getFloat(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a, jfloatArray b) {
	if (methodID_vrml_external_field_EventOut_getFloat == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method getFloat (I[F)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_getFloat, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_getFloat */

#ifndef UNUSED_vrml_external_field_EventOut_get1Float
JRIMethodID FAR methodID_vrml_external_field_EventOut_get1Float = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jfloat)
vrml_external_field_EventOut_get1Float(JRIEnv* env, struct vrml_external_field_EventOut* self, jint a) {
	if (methodID_vrml_external_field_EventOut_get1Float == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method get1Float (I)F");
	}
	return (jfloat)JRI_CallMethodFloat(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_get1Float, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_get1Float */

#ifndef UNUSED_vrml_external_field_EventOut_getSize
JRIMethodID FAR methodID_vrml_external_field_EventOut_getSize = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
vrml_external_field_EventOut_getSize(JRIEnv* env, struct vrml_external_field_EventOut* self) {
	if (methodID_vrml_external_field_EventOut_getSize == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method getSize ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_getSize);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_getSize */

#ifndef UNUSED_vrml_external_field_EventOut_getTime
JRIMethodID FAR methodID_vrml_external_field_EventOut_getTime = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jdouble)
vrml_external_field_EventOut_getTime(JRIEnv* env, struct vrml_external_field_EventOut* self) {
	if (methodID_vrml_external_field_EventOut_getTime == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method getTime ()D");
	}
	return (jdouble)JRI_CallMethodDouble(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_getTime);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_getTime */

#ifndef UNUSED_vrml_external_field_EventOut_getBoolean
JRIMethodID FAR methodID_vrml_external_field_EventOut_getBoolean = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
vrml_external_field_EventOut_getBoolean(JRIEnv* env, struct vrml_external_field_EventOut* self) {
	if (methodID_vrml_external_field_EventOut_getBoolean == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method getBoolean ()Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_getBoolean);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_getBoolean */

#ifndef UNUSED_vrml_external_field_EventOut_getByte
JRIMethodID FAR methodID_vrml_external_field_EventOut_getByte = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_getByte(JRIEnv* env, struct vrml_external_field_EventOut* self, jbyteArray a) {
	if (methodID_vrml_external_field_EventOut_getByte == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method getByte ([B)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_getByte, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_getByte */

#ifndef UNUSED_vrml_external_field_EventOut_newEventOut
JRIMethodID FAR methodID_vrml_external_field_EventOut_newEventOut = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_field_EventOut *)
vrml_external_field_EventOut_newEventOut(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
	if (methodID_vrml_external_field_EventOut_newEventOut == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method newEventOut (III)Lvrml/external/field/EventOut;");
	}
	return (struct vrml_external_field_EventOut *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_vrml_external_field_EventOut_newEventOut, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_newEventOut */

#ifndef UNUSED_vrml_external_field_EventOut_finalize
JRIMethodID FAR methodID_vrml_external_field_EventOut_finalize = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_finalize(JRIEnv* env, struct vrml_external_field_EventOut* self) {
	if (methodID_vrml_external_field_EventOut_finalize == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method finalize ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_finalize);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_finalize */

#ifndef UNUSED_vrml_external_field_EventOut_nFinalize
JRIMethodID FAR methodID_vrml_external_field_EventOut_nFinalize = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventOut_nFinalize(JRIEnv* env, struct vrml_external_field_EventOut* self) {
	if (methodID_vrml_external_field_EventOut_nFinalize == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventOut(env) before calling method nFinalize ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventOut_nFinalize);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventOut_nFinalize */

#ifndef UNUSED_use_vrml_external_field_EventOut

static jglobal _globalclass_vrml_external_field_EventOut = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_vrml_external_field_EventOut(JRIEnv* env)
{
	if (_globalclass_vrml_external_field_EventOut == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_field_EventOut);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_field_EventOut);
			return NULL;
		}
		use_vrml_external_field_EventOut_cBrowser(env, clazz);
		use_vrml_external_field_EventOut_cEvent(env, clazz);
		use_vrml_external_field_EventOut_type(env, clazz);
		use_vrml_external_field_EventOut_userData(env, clazz);
		use_vrml_external_field_EventOut_observer(env, clazz);
		use_vrml_external_field_EventOut_new(env, clazz);
		use_vrml_external_field_EventOut_getType(env, clazz);
		use_vrml_external_field_EventOut_advise(env, clazz);
		use_vrml_external_field_EventOut_advise_1(env, clazz);
		use_vrml_external_field_EventOut_callback(env, clazz);
		use_vrml_external_field_EventOut_getString(env, clazz);
		use_vrml_external_field_EventOut_get1String(env, clazz);
		use_vrml_external_field_EventOut_getNode(env, clazz);
		use_vrml_external_field_EventOut_get1Node(env, clazz);
		use_vrml_external_field_EventOut_getInt(env, clazz);
		use_vrml_external_field_EventOut_get1Int(env, clazz);
		use_vrml_external_field_EventOut_getFloat(env, clazz);
		use_vrml_external_field_EventOut_get1Float(env, clazz);
		use_vrml_external_field_EventOut_getSize(env, clazz);
		use_vrml_external_field_EventOut_getTime(env, clazz);
		use_vrml_external_field_EventOut_getBoolean(env, clazz);
		use_vrml_external_field_EventOut_getByte(env, clazz);
		use_vrml_external_field_EventOut_newEventOut(env, clazz);
		use_vrml_external_field_EventOut_finalize(env, clazz);
		use_vrml_external_field_EventOut_nFinalize(env, clazz);
		_globalclass_vrml_external_field_EventOut = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_field_EventOut);
	}
}

JRI_PUBLIC_API(void)
unuse_vrml_external_field_EventOut(JRIEnv* env)
{
	if (_globalclass_vrml_external_field_EventOut != NULL) {
		struct java_lang_Class* clazz = (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_field_EventOut);
		unuse_vrml_external_field_EventOut_cBrowser(env, clazz);
		unuse_vrml_external_field_EventOut_cEvent(env, clazz);
		unuse_vrml_external_field_EventOut_type(env, clazz);
		unuse_vrml_external_field_EventOut_userData(env, clazz);
		unuse_vrml_external_field_EventOut_observer(env, clazz);
		unuse_vrml_external_field_EventOut_new(env, clazz);
		unuse_vrml_external_field_EventOut_getType(env, clazz);
		unuse_vrml_external_field_EventOut_advise(env, clazz);
		unuse_vrml_external_field_EventOut_advise_1(env, clazz);
		unuse_vrml_external_field_EventOut_callback(env, clazz);
		unuse_vrml_external_field_EventOut_getString(env, clazz);
		unuse_vrml_external_field_EventOut_get1String(env, clazz);
		unuse_vrml_external_field_EventOut_getNode(env, clazz);
		unuse_vrml_external_field_EventOut_get1Node(env, clazz);
		unuse_vrml_external_field_EventOut_getInt(env, clazz);
		unuse_vrml_external_field_EventOut_get1Int(env, clazz);
		unuse_vrml_external_field_EventOut_getFloat(env, clazz);
		unuse_vrml_external_field_EventOut_get1Float(env, clazz);
		unuse_vrml_external_field_EventOut_getSize(env, clazz);
		unuse_vrml_external_field_EventOut_getTime(env, clazz);
		unuse_vrml_external_field_EventOut_getBoolean(env, clazz);
		unuse_vrml_external_field_EventOut_getByte(env, clazz);
		unuse_vrml_external_field_EventOut_newEventOut(env, clazz);
		unuse_vrml_external_field_EventOut_finalize(env, clazz);
		unuse_vrml_external_field_EventOut_nFinalize(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_vrml_external_field_EventOut);
		_globalclass_vrml_external_field_EventOut = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_vrml_external_field_EventOut */

#ifdef _implementing_vrml_external_field_EventOut

JRI_PUBLIC_API(struct java_lang_Class*)
register_vrml_external_field_EventOut(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"advise()V",
		"getString([Ljava/lang/String;)V",
		"get1String(I)Ljava/lang/String;",
		"getNode([Lvrml/external/Node;)V",
		"get1Node(I)Lvrml/external/Node;",
		"getInt([I)V",
		"get1Int(I)I",
		"getFloat(I[F)V",
		"get1Float(I)F",
		"getSize()I",
		"getTime()D",
		"getBoolean()Z",
		"getByte([B)V",
		"nFinalize()V",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_vrml_external_field_EventOut_advise_1,
		(void*)native_vrml_external_field_EventOut_getString,
		(void*)native_vrml_external_field_EventOut_get1String,
		(void*)native_vrml_external_field_EventOut_getNode,
		(void*)native_vrml_external_field_EventOut_get1Node,
		(void*)native_vrml_external_field_EventOut_getInt,
		(void*)native_vrml_external_field_EventOut_get1Int,
		(void*)native_vrml_external_field_EventOut_getFloat,
		(void*)native_vrml_external_field_EventOut_get1Float,
		(void*)native_vrml_external_field_EventOut_getSize,
		(void*)native_vrml_external_field_EventOut_getTime,
		(void*)native_vrml_external_field_EventOut_getBoolean,
		(void*)native_vrml_external_field_EventOut_getByte,
		(void*)native_vrml_external_field_EventOut_nFinalize,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_field_EventOut);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_field_EventOut);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_vrml_external_field_EventOut(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_vrml_external_field_EventOut(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_field_EventOut);
	JRI_UnregisterNatives(env, clazz);
	unuse_vrml_external_field_EventOut(env);
}

#endif /* _implementing_vrml_external_field_EventOut */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

/* SYMBOL: "vrml/external/field/EventOut/advise()V", Java_vrml_external_field_EventOut_advise_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_advise_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventOut_advise_1(_EE_,_P_[0].p);
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventOut/getString([Ljava/lang/String;)V", Java_vrml_external_field_EventOut_getString_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_getString_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventOut_getString(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventOut/get1String(I)Ljava/lang/String;", Java_vrml_external_field_EventOut_get1String_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_get1String_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_field_EventOut_get1String(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/field/EventOut/getNode([Lvrml/external/Node;)V", Java_vrml_external_field_EventOut_getNode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_getNode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventOut_getNode(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventOut/get1Node(I)Lvrml/external/Node;", Java_vrml_external_field_EventOut_get1Node_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_get1Node_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_vrml_external_field_EventOut_get1Node(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/field/EventOut/getInt([I)V", Java_vrml_external_field_EventOut_getInt_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_getInt_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventOut_getInt(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventOut/get1Int(I)I", Java_vrml_external_field_EventOut_get1Int_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_get1Int_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = native_vrml_external_field_EventOut_get1Int(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/field/EventOut/getFloat(I[F)V", Java_vrml_external_field_EventOut_getFloat_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_getFloat_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventOut_getFloat(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventOut/get1Float(I)F", Java_vrml_external_field_EventOut_get1Float_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_get1Float_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].f = native_vrml_external_field_EventOut_get1Float(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/field/EventOut/getSize()I", Java_vrml_external_field_EventOut_getSize_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_getSize_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = native_vrml_external_field_EventOut_getSize(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/field/EventOut/getTime()D", Java_vrml_external_field_EventOut_getTime_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_getTime_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	JRI_JDK_Java8 _tval;
	JRI_SET_DOUBLE(_tval, _P_, native_vrml_external_field_EventOut_getTime(_EE_,_P_[0].p));
	return _P_ + 2;
}

/* SYMBOL: "vrml/external/field/EventOut/getBoolean()Z", Java_vrml_external_field_EventOut_getBoolean_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_getBoolean_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = (native_vrml_external_field_EventOut_getBoolean(_EE_,_P_[0].p) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "vrml/external/field/EventOut/getByte([B)V", Java_vrml_external_field_EventOut_getByte_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_getByte_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventOut_getByte(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventOut/nFinalize()V", Java_vrml_external_field_EventOut_nFinalize_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventOut_nFinalize_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventOut_nFinalize(_EE_,_P_[0].p);
	return _P_;
}

#endif /* NO_JDK */

