/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class vrml/external/field/EventIn */

#ifdef IMPLEMENT_vrml_external_field_EventIn
#define _implementing_vrml_external_field_EventIn
#endif /* IMPLEMENT_vrml_external_field_EventIn */
#define IMPLEMENT_vrml_external_field_EventIn
#include "vrml_external_field_EventIn.h"

#ifndef UNUSED_vrml_external_field_EventIn_cBrowser
JRIFieldID FAR fieldID_vrml_external_field_EventIn_cBrowser = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_vrml_external_field_EventIn_cBrowser(JRIEnv* env, struct vrml_external_field_EventIn* obj) {
	if (fieldID_vrml_external_field_EventIn_cBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before accessing field cBrowser I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_cBrowser);
}
JRI_PUBLIC_API(void)
set_vrml_external_field_EventIn_cBrowser(JRIEnv* env, struct vrml_external_field_EventIn* obj, jint v) {
	if (fieldID_vrml_external_field_EventIn_cBrowser == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before accessing field cBrowser I");
	}
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_cBrowser, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_cBrowser */

#ifndef UNUSED_vrml_external_field_EventIn_cEvent
JRIFieldID FAR fieldID_vrml_external_field_EventIn_cEvent = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_vrml_external_field_EventIn_cEvent(JRIEnv* env, struct vrml_external_field_EventIn* obj) {
	if (fieldID_vrml_external_field_EventIn_cEvent == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before accessing field cEvent I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_cEvent);
}
JRI_PUBLIC_API(void)
set_vrml_external_field_EventIn_cEvent(JRIEnv* env, struct vrml_external_field_EventIn* obj, jint v) {
	if (fieldID_vrml_external_field_EventIn_cEvent == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before accessing field cEvent I");
	}
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_cEvent, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_cEvent */

#ifndef UNUSED_vrml_external_field_EventIn_type
JRIFieldID FAR fieldID_vrml_external_field_EventIn_type = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_vrml_external_field_EventIn_type(JRIEnv* env, struct vrml_external_field_EventIn* obj) {
	if (fieldID_vrml_external_field_EventIn_type == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before accessing field type I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_type);
}
JRI_PUBLIC_API(void)
set_vrml_external_field_EventIn_type(JRIEnv* env, struct vrml_external_field_EventIn* obj, jint v) {
	if (fieldID_vrml_external_field_EventIn_type == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before accessing field type I");
	}
	JRI_SetFieldInt(env, obj, fieldID_vrml_external_field_EventIn_type, v);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_type */

#ifndef UNUSED_vrml_external_field_EventIn_new
JRIMethodID FAR methodID_vrml_external_field_EventIn_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_field_EventIn*)
vrml_external_field_EventIn_new(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
	if (methodID_vrml_external_field_EventIn_new == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method <init> (III)V");
	}
	return (struct vrml_external_field_EventIn*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_vrml_external_field_EventIn_new, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_new */

#ifndef UNUSED_vrml_external_field_EventIn_getType
JRIMethodID FAR methodID_vrml_external_field_EventIn_getType = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
vrml_external_field_EventIn_getType(JRIEnv* env, struct vrml_external_field_EventIn* self) {
	if (methodID_vrml_external_field_EventIn_getType == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method getType ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_getType);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_getType */

#ifndef UNUSED_vrml_external_field_EventIn_setString
JRIMethodID FAR methodID_vrml_external_field_EventIn_setString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setString(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jstringArray b) {
	if (methodID_vrml_external_field_EventIn_setString == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method setString (I[Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_setString, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_setString */

#ifndef UNUSED_vrml_external_field_EventIn_set1String
JRIMethodID FAR methodID_vrml_external_field_EventIn_set1String = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_set1String(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, struct java_lang_String *b) {
	if (methodID_vrml_external_field_EventIn_set1String == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method set1String (ILjava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_set1String, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_set1String */

#ifndef UNUSED_vrml_external_field_EventIn_setNode
JRIMethodID FAR methodID_vrml_external_field_EventIn_setNode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setNode(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jobjectArray b) {
	if (methodID_vrml_external_field_EventIn_setNode == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method setNode (I[Lvrml/external/Node;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_setNode, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_setNode */

#ifndef UNUSED_vrml_external_field_EventIn_set1Node
JRIMethodID FAR methodID_vrml_external_field_EventIn_set1Node = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_set1Node(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, struct vrml_external_Node *b) {
	if (methodID_vrml_external_field_EventIn_set1Node == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method set1Node (ILvrml/external/Node;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_set1Node, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_set1Node */

#ifndef UNUSED_vrml_external_field_EventIn_setInt
JRIMethodID FAR methodID_vrml_external_field_EventIn_setInt = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setInt(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jintArray b) {
	if (methodID_vrml_external_field_EventIn_setInt == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method setInt (I[I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_setInt, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_setInt */

#ifndef UNUSED_vrml_external_field_EventIn_set1Int
JRIMethodID FAR methodID_vrml_external_field_EventIn_set1Int = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_set1Int(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jint b) {
	if (methodID_vrml_external_field_EventIn_set1Int == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method set1Int (II)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_set1Int, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_set1Int */

#ifndef UNUSED_vrml_external_field_EventIn_setFloat
JRIMethodID FAR methodID_vrml_external_field_EventIn_setFloat = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setFloat(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jfloat b) {
	if (methodID_vrml_external_field_EventIn_setFloat == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method setFloat (IF)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_setFloat, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_setFloat */

#ifndef UNUSED_vrml_external_field_EventIn_setFloatArray
JRIMethodID FAR methodID_vrml_external_field_EventIn_setFloatArray = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setFloatArray(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jfloatArray b) {
	if (methodID_vrml_external_field_EventIn_setFloatArray == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method setFloatArray (I[F)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_setFloatArray, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_setFloatArray */

#ifndef UNUSED_vrml_external_field_EventIn_set1Float
JRIMethodID FAR methodID_vrml_external_field_EventIn_set1Float = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_set1Float(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jfloatArray b) {
	if (methodID_vrml_external_field_EventIn_set1Float == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method set1Float (I[F)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_set1Float, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_set1Float */

#ifndef UNUSED_vrml_external_field_EventIn_setTime
JRIMethodID FAR methodID_vrml_external_field_EventIn_setTime = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setTime(JRIEnv* env, struct vrml_external_field_EventIn* self, jdouble a) {
	if (methodID_vrml_external_field_EventIn_setTime == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method setTime (D)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_setTime, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_setTime */

#ifndef UNUSED_vrml_external_field_EventIn_setBoolean
JRIMethodID FAR methodID_vrml_external_field_EventIn_setBoolean = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setBoolean(JRIEnv* env, struct vrml_external_field_EventIn* self, jbool a) {
	if (methodID_vrml_external_field_EventIn_setBoolean == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method setBoolean (Z)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_setBoolean, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_setBoolean */

#ifndef UNUSED_vrml_external_field_EventIn_setImage
JRIMethodID FAR methodID_vrml_external_field_EventIn_setImage = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_setImage(JRIEnv* env, struct vrml_external_field_EventIn* self, jint a, jint b, jint c, jint d, jbyteArray e) {
	if (methodID_vrml_external_field_EventIn_setImage == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method setImage (IIII[B)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_setImage, a, b, c, d, e);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_setImage */

#ifndef UNUSED_vrml_external_field_EventIn_newEventIn
JRIMethodID FAR methodID_vrml_external_field_EventIn_newEventIn = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_field_EventIn *)
vrml_external_field_EventIn_newEventIn(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c) {
	if (methodID_vrml_external_field_EventIn_newEventIn == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method newEventIn (III)Lvrml/external/field/EventIn;");
	}
	return (struct vrml_external_field_EventIn *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_vrml_external_field_EventIn_newEventIn, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_newEventIn */

#ifndef UNUSED_vrml_external_field_EventIn_finalize
JRIMethodID FAR methodID_vrml_external_field_EventIn_finalize = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_finalize(JRIEnv* env, struct vrml_external_field_EventIn* self) {
	if (methodID_vrml_external_field_EventIn_finalize == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method finalize ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_finalize);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_finalize */

#ifndef UNUSED_vrml_external_field_EventIn_nFinalize
JRIMethodID FAR methodID_vrml_external_field_EventIn_nFinalize = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
vrml_external_field_EventIn_nFinalize(JRIEnv* env, struct vrml_external_field_EventIn* self) {
	if (methodID_vrml_external_field_EventIn_nFinalize == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_field_EventIn(env) before calling method nFinalize ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_vrml_external_field_EventIn_nFinalize);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_field_EventIn_nFinalize */

#ifndef UNUSED_use_vrml_external_field_EventIn

static jglobal _globalclass_vrml_external_field_EventIn = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_vrml_external_field_EventIn(JRIEnv* env)
{
	if (_globalclass_vrml_external_field_EventIn == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_field_EventIn);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_field_EventIn);
			return NULL;
		}
		use_vrml_external_field_EventIn_cBrowser(env, clazz);
		use_vrml_external_field_EventIn_cEvent(env, clazz);
		use_vrml_external_field_EventIn_type(env, clazz);
		use_vrml_external_field_EventIn_new(env, clazz);
		use_vrml_external_field_EventIn_getType(env, clazz);
		use_vrml_external_field_EventIn_setString(env, clazz);
		use_vrml_external_field_EventIn_set1String(env, clazz);
		use_vrml_external_field_EventIn_setNode(env, clazz);
		use_vrml_external_field_EventIn_set1Node(env, clazz);
		use_vrml_external_field_EventIn_setInt(env, clazz);
		use_vrml_external_field_EventIn_set1Int(env, clazz);
		use_vrml_external_field_EventIn_setFloat(env, clazz);
		use_vrml_external_field_EventIn_setFloatArray(env, clazz);
		use_vrml_external_field_EventIn_set1Float(env, clazz);
		use_vrml_external_field_EventIn_setTime(env, clazz);
		use_vrml_external_field_EventIn_setBoolean(env, clazz);
		use_vrml_external_field_EventIn_setImage(env, clazz);
		use_vrml_external_field_EventIn_newEventIn(env, clazz);
		use_vrml_external_field_EventIn_finalize(env, clazz);
		use_vrml_external_field_EventIn_nFinalize(env, clazz);
		_globalclass_vrml_external_field_EventIn = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_field_EventIn);
	}
}

JRI_PUBLIC_API(void)
unuse_vrml_external_field_EventIn(JRIEnv* env)
{
	if (_globalclass_vrml_external_field_EventIn != NULL) {
		struct java_lang_Class* clazz = (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_field_EventIn);
		unuse_vrml_external_field_EventIn_cBrowser(env, clazz);
		unuse_vrml_external_field_EventIn_cEvent(env, clazz);
		unuse_vrml_external_field_EventIn_type(env, clazz);
		unuse_vrml_external_field_EventIn_new(env, clazz);
		unuse_vrml_external_field_EventIn_getType(env, clazz);
		unuse_vrml_external_field_EventIn_setString(env, clazz);
		unuse_vrml_external_field_EventIn_set1String(env, clazz);
		unuse_vrml_external_field_EventIn_setNode(env, clazz);
		unuse_vrml_external_field_EventIn_set1Node(env, clazz);
		unuse_vrml_external_field_EventIn_setInt(env, clazz);
		unuse_vrml_external_field_EventIn_set1Int(env, clazz);
		unuse_vrml_external_field_EventIn_setFloat(env, clazz);
		unuse_vrml_external_field_EventIn_setFloatArray(env, clazz);
		unuse_vrml_external_field_EventIn_set1Float(env, clazz);
		unuse_vrml_external_field_EventIn_setTime(env, clazz);
		unuse_vrml_external_field_EventIn_setBoolean(env, clazz);
		unuse_vrml_external_field_EventIn_setImage(env, clazz);
		unuse_vrml_external_field_EventIn_newEventIn(env, clazz);
		unuse_vrml_external_field_EventIn_finalize(env, clazz);
		unuse_vrml_external_field_EventIn_nFinalize(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_vrml_external_field_EventIn);
		_globalclass_vrml_external_field_EventIn = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_vrml_external_field_EventIn */

#ifdef _implementing_vrml_external_field_EventIn

JRI_PUBLIC_API(struct java_lang_Class*)
register_vrml_external_field_EventIn(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"setString(I[Ljava/lang/String;)V",
		"set1String(ILjava/lang/String;)V",
		"setNode(I[Lvrml/external/Node;)V",
		"set1Node(ILvrml/external/Node;)V",
		"setInt(I[I)V",
		"set1Int(II)V",
		"setFloat(IF)V",
		"setFloatArray(I[F)V",
		"set1Float(I[F)V",
		"setTime(D)V",
		"setBoolean(Z)V",
		"setImage(IIII[B)V",
		"nFinalize()V",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_vrml_external_field_EventIn_setString,
		(void*)native_vrml_external_field_EventIn_set1String,
		(void*)native_vrml_external_field_EventIn_setNode,
		(void*)native_vrml_external_field_EventIn_set1Node,
		(void*)native_vrml_external_field_EventIn_setInt,
		(void*)native_vrml_external_field_EventIn_set1Int,
		(void*)native_vrml_external_field_EventIn_setFloat,
		(void*)native_vrml_external_field_EventIn_setFloatArray,
		(void*)native_vrml_external_field_EventIn_set1Float,
		(void*)native_vrml_external_field_EventIn_setTime,
		(void*)native_vrml_external_field_EventIn_setBoolean,
		(void*)native_vrml_external_field_EventIn_setImage,
		(void*)native_vrml_external_field_EventIn_nFinalize,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_field_EventIn);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_field_EventIn);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_vrml_external_field_EventIn(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_vrml_external_field_EventIn(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_field_EventIn);
	JRI_UnregisterNatives(env, clazz);
	unuse_vrml_external_field_EventIn(env);
}

#endif /* _implementing_vrml_external_field_EventIn */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

/* SYMBOL: "vrml/external/field/EventIn/setString(I[Ljava/lang/String;)V", Java_vrml_external_field_EventIn_setString_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_setString_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_setString(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/set1String(ILjava/lang/String;)V", Java_vrml_external_field_EventIn_set1String_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_set1String_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_set1String(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/setNode(I[Lvrml/external/Node;)V", Java_vrml_external_field_EventIn_setNode_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_setNode_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_setNode(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/set1Node(ILvrml/external/Node;)V", Java_vrml_external_field_EventIn_set1Node_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_set1Node_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_set1Node(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/setInt(I[I)V", Java_vrml_external_field_EventIn_setInt_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_setInt_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_setInt(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/set1Int(II)V", Java_vrml_external_field_EventIn_set1Int_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_set1Int_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_set1Int(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].i)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/setFloat(IF)V", Java_vrml_external_field_EventIn_setFloat_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_setFloat_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_setFloat(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].f)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/setFloatArray(I[F)V", Java_vrml_external_field_EventIn_setFloatArray_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_setFloatArray_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_setFloatArray(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/set1Float(I[F)V", Java_vrml_external_field_EventIn_set1Float_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_set1Float_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_set1Float(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/setTime(D)V", Java_vrml_external_field_EventIn_setTime_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_setTime_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	JRI_JDK_Java8 _t1;
	(void) native_vrml_external_field_EventIn_setTime(_EE_,_P_[0].p,JRI_GET_DOUBLE(_t1, _P_+1));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/setBoolean(Z)V", Java_vrml_external_field_EventIn_setBoolean_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_setBoolean_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_setBoolean(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/setImage(IIII[B)V", Java_vrml_external_field_EventIn_setImage_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_setImage_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_setImage(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].p)));
	return _P_;
}

/* SYMBOL: "vrml/external/field/EventIn/nFinalize()V", Java_vrml_external_field_EventIn_nFinalize_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_vrml_external_field_EventIn_nFinalize_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_vrml_external_field_EventIn_nFinalize(_EE_,_P_[0].p);
	return _P_;
}

#endif /* NO_JDK */

