/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class vrml/external/exception/InvalidRouteException */

#ifdef IMPLEMENT_vrml_external_exception_InvalidRouteException
#define _implementing_vrml_external_exception_InvalidRouteException
#endif /* IMPLEMENT_vrml_external_exception_InvalidRouteException */
#define IMPLEMENT_vrml_external_exception_InvalidRouteException
#include "vrml_external_exception_InvalidRouteException.h"

#ifndef UNUSED_vrml_external_exception_InvalidRouteException_new
JRIMethodID FAR methodID_vrml_external_exception_InvalidRouteException_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_exception_InvalidRouteException*)
vrml_external_exception_InvalidRouteException_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_vrml_external_exception_InvalidRouteException_new == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_exception_InvalidRouteException(env) before calling method <init> ()V");
	}
	return (struct vrml_external_exception_InvalidRouteException*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_vrml_external_exception_InvalidRouteException_new);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_exception_InvalidRouteException_new */

#ifndef UNUSED_vrml_external_exception_InvalidRouteException_new_1
JRIMethodID FAR methodID_vrml_external_exception_InvalidRouteException_new_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct vrml_external_exception_InvalidRouteException*)
vrml_external_exception_InvalidRouteException_new_1(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
	if (methodID_vrml_external_exception_InvalidRouteException_new_1 == JRIUninitialized) {
		assert(!"Forgot to call use_vrml_external_exception_InvalidRouteException(env) before calling method <init> (Ljava/lang/String;)V");
	}
	return (struct vrml_external_exception_InvalidRouteException*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_vrml_external_exception_InvalidRouteException_new_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_vrml_external_exception_InvalidRouteException_new_1 */

#ifndef UNUSED_use_vrml_external_exception_InvalidRouteException

static jglobal _globalclass_vrml_external_exception_InvalidRouteException = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_vrml_external_exception_InvalidRouteException(JRIEnv* env)
{
	if (_globalclass_vrml_external_exception_InvalidRouteException == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_exception_InvalidRouteException);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_exception_InvalidRouteException);
			return NULL;
		}
		use_vrml_external_exception_InvalidRouteException_new(env, clazz);
		use_vrml_external_exception_InvalidRouteException_new_1(env, clazz);
		_globalclass_vrml_external_exception_InvalidRouteException = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_exception_InvalidRouteException);
	}
}

JRI_PUBLIC_API(void)
unuse_vrml_external_exception_InvalidRouteException(JRIEnv* env)
{
	if (_globalclass_vrml_external_exception_InvalidRouteException != NULL) {
		struct java_lang_Class* clazz = (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_vrml_external_exception_InvalidRouteException);
		unuse_vrml_external_exception_InvalidRouteException_new(env, clazz);
		unuse_vrml_external_exception_InvalidRouteException_new_1(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_vrml_external_exception_InvalidRouteException);
		_globalclass_vrml_external_exception_InvalidRouteException = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_vrml_external_exception_InvalidRouteException */

#ifdef _implementing_vrml_external_exception_InvalidRouteException

JRI_PUBLIC_API(struct java_lang_Class*)
register_vrml_external_exception_InvalidRouteException(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		NULL
	};
	void* nativeProcs[] = {
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_exception_InvalidRouteException);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_vrml_external_exception_InvalidRouteException);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_vrml_external_exception_InvalidRouteException(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_vrml_external_exception_InvalidRouteException(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_vrml_external_exception_InvalidRouteException);
	JRI_UnregisterNatives(env, clazz);
	unuse_vrml_external_exception_InvalidRouteException(env);
}

#endif /* _implementing_vrml_external_exception_InvalidRouteException */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

#endif /* NO_JDK */

