//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by blaxxuncc3d.rc
//
#define IDS_GLVIEWCTRL                  1
#define IDD_ABOUTBOX_GLVIEWCTRL         1
#define IDB_GLVIEWCTRL                  1
#define IDI_ABOUTDLL                    1
#define IDS_GLVIEWCTRL_PPG              2
#define IDHIDE                          2
#define IDS_GLVIEWCTRL_PPG_CAPTION      100
#define IDD_PROPPAGE_GLVIEWCTRL         100
#define IDR_MAINFRAME_POPUP             160
#define IDC_VERSION                     201
#define IDD_WORLD_INFO                  201
#define IDC_UPDATE_CHECK                202
#define IDR_ACCELERATOR                 202
#define IDD_PROPPAGE_RENDERING          202
#define IDC_VERSION2                    202
#define IDC_URL                         203
#define IDD_PROPPAGE_NAVIGATION         203
#define IDC_VERSION3                    203
#define IDC_TITLE                       204
#define IDD_PROP_D3D                    204
#define IDC_INFO                        205
#define IDD_PROP_GENERAL                205
#define IDC_VRML2                       206
#define IDD_ASKHARDWARE                 206
#define IDC_COMBO_DRIVER                207
#define IDC_INFO1                       207
#define IDC_DITHER                      208
#define IDC_TFILTER                     209
#define IDC_COLLISION                   210
#define IDC_COMBO_MODE                  210
#define IDC_RSOFTWARE                   210
#define IDC_GROUND                      211
#define IDC_VIDEO_MEM                   211
#define IDC_AVATAR_HEIGHT               212
#define IDC_TMIPMAP                     212
#define IDC_AVATAR_RADIUS               213
#define IDC_ANTI_ALIAS                  213
#define IDC_SPEED                       214
#define IDC_CURSOR1                     214
#define IDC_VISIBLILITY                 215
#define IDC_REGISTER_VRML               217
#define IDC_CURSOR2                     217
#define IDC_CACHE_BROWSE                218
#define IDC_CURSOR3                     218
#define IDC_MENUE_MODE                  219
#define IDC_CURSOR4                     219
#define IDC_CURSOR5                     220
#define IDC_ASK                         220
#define IDC_ASK3                        220
#define IDC_CURSOR6                     221
#define IDC_TEXT                        221
#define IDC_CURSOR7                     222
#define IDC_CLEAR                       222
#define IDC_CURSOR8                     223
#define IDC_CURSOR9                     224
#define IDC_COPY                        224
#define IDC_COMBO_QUALITY               224
#define IDC_CURSOR10                    225
#define IDC_USE_RSX                     225
#define IDC_CURSOR11                    226
#define IDC_NUM_SOUNDS                  226
#define IDC_CURSOR12                    227
#define IDC_CURSOR13                    228
#define IDC_CACHE                       228
#define IDC_CURSOR14                    229
#define IDC_DIRECTORY                   229
#define IDC_CURSOR15                    230
#define IDC_RO_DIRECTORY                230
#define IDC_CURSOR16                    231
#define IDC_DELETE                      231
#define IDC_CURSOR17                    232
#define IDC_VERIFY_DAYS                 232
#define IDC_CURSOR18                    233
#define IDC_CACHE_READ                  233
#define IDC_FULL_SPEED                  233
#define IDC_CURSOR19                    234
#define IDC_VERBOSE                     234
#define IDC_CURSOR20                    235
#define IDC_RESET                       235
#define IDC_EXACT_COLLISION             235
#define IDC_CURSOR21                    236
#define IDC_LIST                        236
#define IDC_CURSOR22                    237
#define IDC_MODE_LIST                   237
#define IDD_CONSOLE                     238
#define IDD_PROP_SOUND                  239
#define IDC_SPIN                        239
#define IDD_DIALOG1                     240
#define IDC_TOUR                        240
#define IDD_PROP_OPENGL                 241
#define IDC_CACHEOPT_ALWAYS             241
#define IDD_PROP_CACHE                  242
#define IDC_CACHEOPT_ONCE               242
#define IDB_BITMAP1                     242
#define IDB_SPHERE_OVER_1               242
#define IDD_PROP_AVATAR_VIEW            243
#define IDC_CACHEOPT_DAYS               243
#define IDB_BITMAP2                     243
#define IDD_PROP_VIEWPOINTS             244
#define IDC_MAX_SPACE                   244
#define IDB_BITMAP3                     244
#define IDD_PROP_CACHE_SETTINGS         245
#define IDC_MIN_SPACE_FREE              245
#define IDB_BITMAP4                     245
#define IDC_MAX_SPACE_SPIN              246
#define IDD_PROP_NAVIGATION_MODE        246
#define IDB_BITMAP5                     246
#define IDC_MIN_SPACE_FREE_SPIN         247
#define IDB_BITMAP6                     247
#define IDD_PROP_D3D_2                  247
#define IDC_3DSOUND                     248
#define IDB_BITMAP7                     248
#define IDB_BITMAP8                     249
#define IDC_NAV_PANEL                   249
#define IDB_BITMAP9                     250
#define IDB_SPHERE_DOWN_1               250
#define IDT_USER_INTERFACE              250
#define IDB_BITMAP10                    251
#define IDC_TEXT_D3D                    251
#define IDB_BITMAP11                    252
#define IDC_TEXT_FULLSCREEN             252
#define IDB_BITMAP12                    253
#define IDC_TEXT_SOUNDS                 253
#define IDC_TEXT_DXLEVEL                253
#define IDB_BITMAP13                    254
#define IDC_TEXT_SOUNDQUAL              254
#define IDB_BITMAP14                    255
#define IDC_TEXT_CACHE1                 255
#define IDB_BITMAP15                    256
#define IDC_TEXT_CACHE3                 256
#define IDB_BITMAP16                    257
#define IDC_TEXT_CACHE2                 257
#define IDB_BITMAP17                    258
#define IDC_CACHEOPT1                   258
#define IDC_CACHEOPT3                   259
#define IDC_CACHEOPT4                   260
#define IDC_CACHEOPT2                   261
#define IDC_ASK1                        262
#define IDC_ASK2                        263
#define IDC_PIII                        264
#define IDC_SOFTWARE_LIGHTING           265
#define IDB_BITMAP18                    266
#define IDC_T_TARGET_FPS                266
#define IDB_BITMAP19                    267
#define IDC_TARGET_FPS                  267
#define IDB_BITMAP20                    268
#define IDB_VI2_U                       268
#define IDC_TARGET_FPS_SPIN             268
#define IDB_BITMAP21                    269
#define IDB_VI2_D                       269
#define IDC_NURBS_MODE                  269
#define IDB_BITMAP22                    270
#define IDB_VI3_U                       270
#define IDC_T_TESS_FACTOR               270
#define IDB_BITMAP23                    271
#define IDB_VI3_D                       271
#define IDC_TESS_FACTOR                 271
#define IDB_BITMAP24                    272
#define IDB_HELP_U                      272
#define IDC_TESS_FACTOR_SPIN            272
#define IDB_BITMAP25                    273
#define IDB_HELP_D                      273
#define IDC_T_NURBS_SETTINGS            273
#define IDB_BITMAP26                    274
#define IDB_SLIDE2_U                    274
#define IDC_USE_D3D_CULLING             274
#define IDC_SRC                         274
#define IDB_BITMAP27                    275
#define IDB_SLIDE2_F                    275
#define IDC_PANEL                       275
#define IDB_BITMAP28                    276
#define IDB_SLIDE2_D                    276
#define IDC_COMBO_DXLEVEL               276
#define IDB_BITMAP29                    277
#define IDB_SLIDE1_U                    277
#define IDC_TEXT_ASK_HW_PROB            277
#define IDB_BITMAP30                    278
#define IDB_SLIDE1_F                    278
#define ID_USEHWINDX3                   278
#define IDB_BITMAP31                    279
#define IDB_SLIDE1_D                    279
#define ID_USE_SOFT                     279
#define ID_SAFE_MODE                    279
#define IDB_BITMAP32                    280
#define IDC_TEXTURE_SIZE                280
#define IDC_TEXT_MAX_TEXTURE_SIZE       281
#define IDB_BITMAP33                    282
#define IDB_CLOSE_U                     282
#define IDC_T_VISIBILITY                282
#define IDB_BITMAP34                    283
#define IDB_CLOSE_F                     283
#define IDC_VISIBILITY_FACTOR           283
#define IDB_BITMAP35                    284
#define IDB_CLOSE_D                     284
#define IDC_VISIBILITY_FACTOR_SPIN      284
#define IDB_BITMAP36                    285
#define IDB_HELP_F                      285
#define IDC_T_AUTO_LOD                  285
#define IDC_AUTO_LOD                    286
#define IDB_VI2_F                       287
#define IDC_AUTO_LOD_SPIN               287
#define IDB_VI3_F                       288
#define IDC_T_DETAILS                   288
#define IDB_VI1_D                       289
#define IDC_USE_MOVIES                  289
#define IDB_VI1_F                       290
#define IDC_USE_SOUNDS                  290
#define IDB_VI1_U                       291
#define IDC_USE_TEXTURES                291
#define IDC_CURSOR23                    292
#define ID_NORMAL_MODE                  292
#define IDB_ROTATE                      293
#define IDC_T_NURBS_MODE                293
#define IDB_EXAMINE                     295
#define IDB_FLY                         297
#define IDB_SLIDE                       299
#define IDB_FLY0                        300
#define IDB_FLY1                        301
#define IDB_FLY2                        302
#define IDB_FLY3                        303
#define IDB_FLY4                        304
#define IDB_FLY5                        305
#define IDB_FLY6                        306
#define IDB_FLY7                        307
#define IDC_CURSOR24                    308
#define IDC_CURSOR25                    309
#define IDD_DIALOG_MENU_THREAD          311
#define IDD_ASK_HW_PROBLEM              312
#define IDD_PROP_PERFORMANCE            313
#define IDC_MEDIA_CACHE                 314 
#define IDC_MEDIA_DIRECTORY             315 
#define IDC_TEXT_MEDIA                  316
#define IDC_TEXT_MEDIA2                 317
#define ID_POPUP_HEADLIGHTON            32768
#define ID_CAMERA_COLLISION             32770
#define ID_CAMERA_FOLLOW_OBJECT         32771
#define ID_CAMERA_RESET                 32773
#define ID_CAMERA_ZOOM                  32777
#define ID_CAMERA_DOLLY_XY              32778
#define ID_CAMERA_ORBIT                 32779
#define ID_CAMERA_PAN                   32780
#define ID_CAMERA_WALK                  32781
#define ID_RENDER_WIREFRAME             32782
#define ID_RENDER_FLAT                  32784
#define ID_RENDER_GOURAUD               32785
#define ID_CAMERA_ROLL                  32787
#define ID_RENDER_VERTICES              32789
#define ID_RENDER_LIGHTED               32790
#define ID_RENDER_TEXTURED              32796
#define ID_RENDER_COLORED               32798
#define ID_CAMERA_FLY                   32837
#define ID_RENDER_NONLIGHTED            32838
#define IDD_CAMERA_RELATIVE             32872
#define ID_CAMERA_ANIMATE_VIEWPOINTS    32891
#define ID_CAMERA_VIEWPOINT_NEXT        32894
#define ID_CAMERA_VIEWPOINT_PREV        32895
#define ID_CAMERA_SEEKTO                32898
#define ID_CAMERA_NONE                  32899
#define ID_VIEWPOINT_0                  32900
#define ID_VIEWPOINT_1                  32901
#define ID_VIEWPOINT_2                  32902
#define ID_VIEWPOINT_3                  32903
#define ID_VIEWPOINT_4                  32904
#define ID_VIEWPOINT_5                  32905
#define ID_VIEWPOINT_6                  32906
#define ID_VIEWPOINT_7                  32907
#define ID_VIEWPOINT_8                  32908
#define ID_VIEWPOINT_9                  32909
#define ID_VIEWPOINT_10                 32910
#define ID_VIEWPOINT_11                 32911
#define ID_VIEWPOINT_12                 32912
#define ID_VIEWPOINT_13                 32913
#define ID_VIEWPOINT_14                 32914
#define ID_VIEWPOINT_15                 32915
#define ID_VIEWPOINT_16                 32916
#define ID_VIEWPOINT_17                 32917
#define ID_VIEWPOINT_18                 32918
#define ID_VIEWPOINT_19                 32919
#define ID_DRIVER_0                     32950
#define ID_DRIVER_1                     32951
#define ID_DRIVER_2                     32952
#define ID_DRIVER_3                     32953
#define ID_DRIVER_4                     32954
#define ID_DRIVER_5                     32955
#define ID_DRIVER_6                     32956
#define ID_DRIVER_7                     32957
#define ID_DRIVER_8                     32958
#define ID_DRIVER_9                     32959
#define ID_POPUP_VIEWPOINTS_DUMMY1      33000
#define ID_POPUP_HELP_MANUAL            33001
#define ID_POPUP_HELP_VISITBLACKSUN     33002
#define ID_POPUP_HELP_VISIT             33003
#define ID_POPUP_SETTINGS               33004
#define ID_POPUP_HELP_ABOUT             33005
#define ID_CAMERA_JUMP                  33006
#define ID_SETTINGS_STOP_LOADING        33007
#define ID_SETTINGS_RELOAD              33008
#define ID_SETTINGS_SOUND               33009
#define ID_POPUP_HELP_WORLDINFO         33010
#define ID_KEY_LEFT                     33011
#define ID_KEY_RIGHT                    33012
#define ID_KEY_UP                       33013
#define ID_KEY_DOWN                     33014
#define ID_KEY_PGUP                     33015
#define ID_KEY_PGDOWN                   33016
#define ID_POPUP_SETTINGS_STAYONGROUND  33017
#define ID_RENDER_DITHER                33018
#define ID_RENDER_TEXTURE_SMOOTH        33019
#define ID_POPUP_SETTINGS_SETTINGS      33020
#define ID_SETTINGS_PREFERENCES         33021
#define ID_USER_MENU_START              33022
#define ID_USER_MENU_END                38000
#define ID_POPUP_HELP_CHECKVERSION      38001
#define ID_CAMERA_ROTATE                38002
#define ID_POPUP_SPEED_VERYSLOW         38003
#define ID_POPUP_SPEED_SLOW             38004
#define ID_POPUP_SPEED_MEDIUM           38005
#define ID_POPUP_SPEED_FAST             38006
#define ID_POPUP_SPEED_VERYFAST         38007
#define ID_CAMERA_ZOOMOUT               38011
#define ID_CAMERA_STRAIGHTEN_UP         38012
#define ID_MENUITEM38013                38013
#define ID_GO_BACK                      38014
#define ID_CAMERA_GRAVITY               38015
#define ID_SETTINGS_CONSOLE             38016
#define ID_POPUP_3RPERSON               38017
#define ID_POPUP_PAD                    38018
#define ID_POPUP_PANEL                  38019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         38020
#define _APS_NEXT_CONTROL_VALUE         294
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
