//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GLVIEW.RC
//
#define IDHIDE                          0
#define IDR_MAINFRAME                   2
#define IDR_MAINFRAME_EVAL              3
#define IDAPPLY                         3
#define ID_GEN_FILE                     3
#define IDR_GLVIEW_TYPE                 4
#define IDD_ABOUTBOX                    100
#define IDD_ABOUTBOX_EVAL               101
#define IDW_URL                         101
#define IDC_PFDMAX                      102
#define IDD_CHOOSEPF                    102
#define IDC_CURPIXFMT                   103
#define IDC_CURSOR1                     103
#define IDC_PFFORMAT                    104
#define IDC_DOUBLEBUFFER                105
#define IDC_STEREO                      106
#define IDD_MOREPFD                     106
#define IDC_DRWWINDOW                   107
#define IDD_PFDINFO                     107
#define IDC_DRWBITMAP                   108
#define IDC_SUPPORTGDI                  109
#define IDD_MATERIAL                    109
#define IDC_SUPPORTOPENGL               110
#define IDD_DIALOG_TEXTURE              110
#define IDD_TEXTURE                     110
#define IDC_GENERIC_FORMAT              111
#define IDD_BACKGROUND_OPTIONS          112
#define IDC_DBUFFERDONTCARE             113
#define IDC_STEREODONTCARE              114
#define IDD_DEFORM_SPHERE               114
#define IDC_SWAP_EXCHANGE               115
#define IDD_OPTIONS                     116
#define IDC_SWAP_COPY                   116
#define IDD_FOG                         117
#define IDC_NEED_SYSTEM_PALETTE         117
#define IDC_COLORBITS                   118
#define IDD_PARAMETER                   118
#define IDC_ALPHABITS                   119
#define IDD_PIXELFORMAT                 119
#define IDC_accumbits                   120
#define IDD_DRAW_STYLE                  120
#define IDC_DEPTHBITS                   121
#define IDC_STENCILBITS                 122
#define IDD_STYLE                       122
#define IDC_CAUXBUFFERS                 123
#define IDD_NEW_OBJECT                  123
#define IDC_OVERLAYPLANE                124
#define IDD_STYLE_PAGE                  124
#define IDC_MAINPLANE                   125
#define IDD_ABOUTBOX1                   125
#define IDD_LIGHT                       125
#define IDC_UNDERLAYPLANE               126
#define IDD_FONT_LOGO                   127
#define IDC_NEED_PALETTE                127
#define IDD_OBJECT_INFO                 128
#define IDD_TIME                        129
#define IDC_TYPERGBA                    130
#define IDD_MORPH                       130
#define IDC_TYPECOLORINDEX              131
#define IDD_INTERNET_CONFIG             131
#define IDD_D3DOPTIONS                  131
#define IDC_MOREPFD                     133
#define IDD_OPEN_URL                    133
#define IDD_CAMERA_VIEWPOINT            134
#define IDC_REDBITS                     135
#define IDD_WWW_OPTIONS                 135
#define IDD_WWW_RETRY                   136
#define IDC_NEXT_PFD                    137
#define IDD_SCENE_INFO                  137
#define IDC_LAST_PFD                    138
#define IDD_ABOUTBOX_RELEASE            138
#define IDD_REGISTER_FILETYPES          138
#define IDC_INDEX                       139
#define IDC_END_PFD                     140
#define IDB_BITMAP_TREEVIEW             140
#define IDC_FIRST_PFD                   141
#define IDD_TREE_EDITOR                 141
#define IDR_MENU_TREE_EDITOR            142
#define IDC_DEVFMT                      143
#define IDC_GENFMT                      144
#define IDC_MAXPFD                      145
#define IDD_DIALOG_STRING               145
#define IDC_CURPFD                      146
#define IDD_WWW_CONFIG                  146
#define IDC_EDIT_DIFFUSE                147
#define IDD_URL_BAR                     147
#define IDC_STATIC_DIFFUSE              148
#define IDC_BLUEBITS                    149
#define IDC_STATIC_AMBIENT              149
#define IDD_INFO_OPENGL                 149
#define IDC_BLUESHIFT                   150
#define IDC_EDIT_SPECULAR               150
#define IDR_GLVIEW_AVI                  150
#define IDC_STATIC_SPECULAR             151
#define IDR_TEMP                        151
#define IDC_ALPHASHIFT                  152
#define IDC_EDIT_AMBIENT                152
#define IDD_RENDER_FILE                 152
#define IDC_GREENBITS                   153
#define IDC_EDIT_EMISSION               153
#define IDD_NEW_NODE                    153
#define IDC_GREENSHIFT                  154
#define IDC_STATIC_EMISSION             154
#define IDC_REDSHIFT                    155
#define IDC_MATERIAL_COLOR              155
#define IDC_ACCUMREDBITS                156
#define IDC_MATERIAL_APPLY              156
#define IDD_ABOUTBOX_EMD                156
#define IDC_DAMAGEMASK                  157
#define IDC_VISIBLEMASK                 158
#define IDC_STATIC_SHININESS            158
#define IDC_LAYERMASK                   159
#define IDC_STATIC_ALPHA                159
#define IDI_ICON1                       159
#define IDC_ACCUMALPHABITS              160
#define IDR_MAINFRAME_POPUP             160
#define IDC_ACCUMBLUEBITS               161
#define IDC_EDIT_SHININESS              161
#define IDR_TREE_EDITOR_POPUP           161
#define IDC_ACCUMGREENBITS              162
#define IDC_EDIT_ALPHA                  162
#define IDD_THANKS_TO                   162
#define IDC_MATERIAL_LOAD               163
#define IDD_TRANSFORM_POSITION          163
#define IDC_COMBO_TFUNCTION             164
#define IDD_DIALOG1                     164
#define IDC_STATIC_TFUNCTION            165
#define IDD_TRANSFORM                   165
#define IDC_STATIC_FILTERING            166
#define IDD_TRANSFORM_SCALE             166
#define IDC_COMBO_TFILTER_MIN           167
#define IDD_TRANSFORM_ROTATION          167
#define IDC_COMBO_TFILTER_MAX           168
#define IDD_TRANSFORM_NEW_OBJECT        168
#define IDC_STATIC_TFILTER_MAG          169
#define IDC_COMBO_TBLEND                170
#define IDD_OPTIMIZE_SETTINGS           170
#define IDC_STATIC_TFILTER_MA2          171
#define IDC_STATIC_TREPEAT              172
#define IDD_DIALOG2                     172
#define IDC_TYPE                        173
#define IDD_TRANSFORM_MODE              173
#define IDC_COLOR1                      174
#define IDC_RADIUS                      175
#define IDC_COLOR2                      175
#define IDD_METAVERSE                   175
#define IDC_SCALE                       176
#define IDC_COLOR3                      176
#define IDC_ENABLE                      177
#define IDC_DRAGIT                      179
#define IDC_UNSET_TRANSFORM             180
#define IDC_CHECK_TREPEAT_S             181
#define IDC_CHECK_TREPEAT_T             182
#define IDC_TEXTURE_MAX_SIZE            183
#define IDC_TEXTURE_ROTATE              184
#define IDC_STATIC3                     185
#define IDC_TEXTURE_TRANSLATE           186
#define IDC_TEXTURE_RESET               187
#define IDC_TEXTURE_GEN_MIPMAPS         188
#define IDC_TEXTURE_WHITE               189
#define IDC_EDIT_COLOR                  190
#define IDC_TEXTURE_SCALE               190
#define IDC_BUILD_TRISTRIPS             191
#define IDC_APPLY                       192
#define IDC_DEFAULTS                    193
#define IDC_COMBO_TYPE                  199
#define IDC_START                       200
#define IDC_END                         201
#define IDD_WORLD_INFO                  201
#define IDC_DENSITY                     202
#define IDC_COLOR                       203
#define IDC_TITLE                       204
#define IDD_PROP_D3D                    204
#define IDC_QUALITY                     205
#define IDD_PROP_GENERAL                205
#define IDC_USE_BACKGROUND              206
#define IDC_VRML2                       206
#define IDD_ASKHARDWARE                 206
#define IDC_INFO1                       207
#define IDC_COMBO_DRIVER                207
#define IDC_FOG_ENABLE                  208
#define IDC_COMBO_PFUNCTION             209
#define IDC_COMBO_PSOURCE               210
#define IDC_RSOFTWARE                   210
#define IDC_COMBO_MODE                  210
#define IDC_CHECK_NORMALIZE             211
#define IDC_VIDEO_MEM                   211
#define IDC_CHECK_MAPPING_VISIBLE       212
#define IDC_TMIPMAP                     212
#define IDC_PARAMETER_ENABLE            213
#define IDC_ANTI_ALIAS                  213
#define IDC_MAPPING_SCALE               214
#define IDC_MAPPING_ROTATE              215
#define IDC_MAPPING_TRANSLATE           216
#define IDC_MAPPING_RESET               217
#define IDC_REGISTER_VRML               217
#define IDC_COMBO_PMAPPING              218
#define IDC_CHECK_MAPPED_OBJECT_VISIBLE 219
#define IDC_STYLE                       219
#define IDC_MENUE_MODE                  219
#define IDC_ASK3                        220
#define IDC_RADIUS1                     221
#define IDC_RADIUS2                     222
#define IDC_STEPSX                      223
#define IDC_ORIENT                      224
#define IDC_COPY                        224
#define IDC_COMBO_QUALITY               224
#define IDC_STEPSY                      225
#define IDC_USE_RSX                     225
#define IDC_TEXTURE                     226
#define IDC_UMIN                        226
#define IDC_FILL                        227
#define IDC_UMAX                        227
#define IDC_EDGES_VISIBLE               228
#define IDC_VMIN                        228
#define IDC_CACHE                       228
#define IDC_EDGES_LIGHTED               229
#define IDC_VMAX                        229
#define IDC_DIRECTORY                   229
#define IDC_EDGES_SMOOTH                230
#define IDC_RO_DIRECTORY                230
#define IDC_EDGES_TEXTURED              231
#define IDC_HEIGHT                      231
#define IDC_DELETE                      231
#define IDC_EDGES_COLORED               232
#define IDC_VERIFY_DAYS                 232
#define IDC_EDGES_MATCOLOR              233
#define IDC_FULL_SPEED                  233
#define IDC_EDGE_COLOR                  234
#define IDC_VERBOSE                     234
#define IDC_EDGE_COLOR_EDIT             235
#define IDC_EXACT_COLLISION             235
#define IDC_RESET                       235
#define IDC_EDGE_DRAWSTYLE              236
#define IDC_MODE_LIST                   237
#define IDD_CONSOLE                     238
#define IDD_TRANSFORM_SELECT            239
#define IDC_SPIN                        239
#define IDC_TOUR                        240
#define IDC_VISIBLE                     241
#define IDD_PROP_OPENGL                 241
#define IDC_CACHEOPT_ALWAYS             241
#define IDC_TEXTURED                    242
#define IDC_CACHEOPT_ONCE               242
#define IDD_PROP_CACHE                  242
#define IDC_LIGHTED                     243
#define IDC_CACHEOPT_DAYS               243
#define IDD_PROP_AVATAR_VIEW            243
#define IDC_COLORED                     244
#define IDD_PROP_VIEWPOINTS             244
#define IDC_MAX_SPACE                   244
#define IDC_SMOOTH                      245
#define IDD_PROP_SOUND                  245
#define IDC_MIN_SPACE_FREE              245
#define IDC_MATCOLOR                    246
#define IDD_PROP_NAVIGATION_MODE        246
#define IDC_MAX_SPACE_SPIN              246
#define IDC_COLOR_EDIT                  247
#define IDD_PROP_D3D_2                  247
#define IDC_MIN_SPACE_FREE_SPIN         247
#define IDC_DRAWSTYLE                   248
#define IDD_PROP_CACHE_SETTINGS         248
#define IDC_POINT                       249
#define IDC_NAV_PANEL                   249
#define IDT_USER_INTERFACE              250
#define IDC_PRINT_TIME                  251
#define IDC_TEXT_D3D                    251
#define IDC_GL_CACHE                    252
#define IDC_TEXT_FULLSCREEN             252
#define IDC_DISPLAY                     253
#define IDC_DRAW_FRONT                  253
#define IDC_TEXT_SOUNDS                 253
#define IDC_LICENSE                     254
#define IDC_UPDATE_COLORS               254
#define IDC_TEXT_SOUNDQUAL              254
#define IDC_LIGHT                       255
#define IDC_RENDER_ZOOM2                255
#define IDC_LICENSE2                    255
#define IDC_TEXT_CACHE1                 255
#define IDC_TEXT_CACHE3                 256
#define IDC_TEXT_CACHE2                 257
#define IDC_CACHEOPT1                   258
#define IDC_TEXT                        259
#define IDC_CACHEOPT3                   259
#define IDC_FONT                        260
#define IDC_CACHEOPT4                   260
#define IDC_EXTRUDE                     261
#define IDC_CACHEOPT2                   261
#define IDC_EXTRUSION_FACTOR            262
#define IDC_ASK1                        262
#define IDC_PARAMETERS                  263
#define IDC_ASK2                        263
#define IDC_TOP                         264
#define IDC_PIII                        264
#define IDC_BOTTOM                      265
#define IDC_SOFTWARE_LIGHTING           265
#define IDC_FONT_DESCR                  266
#define IDC_T_TARGET_FPS                266
#define IDC_OBJECT_TYPE                 267
#define IDC_Invert                      267
#define IDC_TARGET_FPS                  267
#define IDC_NVERTS                      268
#define IDD_INVERT_FACTOR               268
#define IDC_TARGET_FPS_SPIN             268
#define IDC_NFACES                      269
#define IDC_OUTLINE                     269
#define IDC_NURBS_MODE                  269
#define IDC_NTRIANGLES                  270
#define IDC_T_TESS_FACTOR               270
#define IDC_VCOLOR                      271
#define IDC_TESS_FACTOR                 271
#define IDC_VPARAMETER                  272
#define IDC_TESS_FACTOR_SPIN            272
#define IDC_FCOLOR                      273
#define IDC_T_NURBS_SETTINGS            273
#define IDC_CONVEX_FACES                274
#define IDC_USE_D3D_CULLING             274
#define IDC_TRISTRIP                    275
#define IDC_WSIZE_X                     276
#define IDC_WSIZEX                      277
#define IDC_WSIZE_X2                    278
#define IDC_T                           278
#define IDC_WSIZEY                      279
#define IDC_T0                          279
#define IDC_BBOX_MIN                    280
#define IDC_T1                          280
#define IDC_BBOX_MAX                    281
#define IDC_DT                          281
#define IDC_WSIZE_X3                    283
#define IDC_WRAP                        283
#define IDC_ZDEPTH                      284
#define IDC_REALTIME                    284
#define IDC_WSIZE_X4                    285
#define IDC_MORPH_TYPE                  285
#define IDC_LAST_FRAME_TIME             286
#define IDC_INORMALS                    286
#define IDC_WSIZE_X5                    287
#define IDC_NSCALE1                     287
#define IDC_TRIS_PER_SEC                288
#define IDC_NSCALE1_EDIT                288
#define IDC_NSCALE2_EDIT                289
#define IDC_RSCALE_EDIT                 290
#define IDC_NWAVES_EDIT                 291
#define IDC_WAVE_OFFSET_EDIT            292
#define IDC_WAVE_SCALE_EDIT             293
#define IDC_NWAVES                      294
#define IDC_NSCALE2                     295
#define IDC_DT_SLIDER                   295
#define IDC_WAVE_SCALE                  296
#define IDC_SCROLLBAR_T                 296
#define IDC_RSCALE                      297
#define IDC_URL                         298
#define IDC_HISTORY                     299
#define IDC_T1_EDIT                     299
#define IDC_STATUS                      300
#define IDC_T2_EDIT                     300
#define IDC_VIEWPOINT_LIST              301
#define IDC_T2                          301
#define IDC_ADD_FILES                   302
#define IDC_ROTATION                    302
#define IDC_INLINE_NEVER                303
#define IDC_INLINE_IF_NEEDED            304
#define IDC_INLINE_ALL                  305
#define IDC_KEEP_CONNECTION             306
#define IDC_CACHE_DIRECTORY             307
#define IDC_USE_CAMERA                  308
#define IDC_SCENE_LIGTHS                309
#define IDC_SCENE_SPOT_LIGTHS           310
#define IDC_EMAIL                       311
#define IDC_SAVE                        312
#define IDC_MAX_INLINE                  313
#define IDC_INCREMENTAL_UPDATES         314
#define IDC_USE_TEXTURES                315
#define IDC_USE_SHAPE_HINTS             316
#define IDC_USE_MATERIALS               317
#define IDC_AUTO_SPIN                   318
#define IDC_BROWSER_PATH                318
#define IDC_WIN_SIZE_X                  319
#define IDC_LIGHT_SCALE                 319
#define IDC_WIN_SIZE_Y                  320
#define IDC_TEXTURE_NEVER               320
#define IDC_TEXTURE_ASK                 321
#define IDC_NUM_SOUNDS                  321
#define IDC_POSITION                    322
#define IDC_TEXTURE_ALL                 322
#define IDC_TARGET                      323
#define IDC_WWW_CONFIG                  323
#define IDC_UP                          324
#define IDC_SCENE_HEAD_LIGHT            324
#define IDC_ZNEAR                       325
#define IDC_USE_SENSORS                 325
#define IDC_ZFAR                        326
#define IDC_ENABLE_COLLISION            326
#define IDC_FOVY                        327
#define IDC_LIGHT_AMBIENT               327
#define IDC_SPEED                       328
#define IDC_AVATAR                      328
#define IDC_CLEAR                       329
#define IDC_DISTANCE                    329
#define IDC_WORLD_UP                    330
#define IDC_USE_CACHE                   331
#define IDC_CUSTOMER                    332
#define IDC_KEY                         334
#define IDC_GL_EXTENSIONS               335
#define IDC_SCENE_INFO                  336
#define IDC_INFO                        337
#define IDC_PERSPECTIVE_HINT            338
#define IDC_DEGRADE                     339
#define IDC_IGNORE_ALL                  340
#define IDC_DEGRADE_STYLE               341
#define IDC_ALIGN_LEFT                  342
#define IDC_ALIGN_CENTER                343
#define IDC_PAUSE                       343
#define IDC_ALIGN_RIGHT                 344
#define IDC_AUTO_PLAY                   344
#define IDC_FILETYPES                   346
#define IDC_BROWSE_BROWSER              347
#define IDC_BROWSE_CACHE                348
#define IDC_TREE                        348
#define IDC_PROMPT                      349
#define IDC_BROWSE_AVATAR               349
#define IDC_VALUE                       350
#define IDC_VIEWPOINT_SAVE              351
#define IDC_VIEWPOINT_SAVE_AS           352
#define IDC_COMPUTE_DISTANCE            353
#define IDC_CYCLE                       356
#define IDC_LOGO                        359
#define IDC_SAVE_WINDOWS_SIZE           360
#define IDC_VENDOR                      361
#define IDC_ZBUFFER_16                  361
#define IDC_VERSION                     362
#define IDC_RSX_SOUND                   362
#define IDC_RENDERER                    363
#define IDC_ANIMATE                     363
#define IDC_MIMIMIZE_FILE               363
#define IDC_EXTENSIONS                  364
#define IDC_COMPANY                     364
#define IDC_NODE_TYPE                   365
#define IDC_REGISTER_NETSCAPE           366
#define IDC_SCALE_SPIN                  367
#define IDC_ROTATEZ_SPIN                368
#define IDC_TRANSLATEX_SPIN             369
#define IDC_APPEND_SCENE                369
#define IDC_TRANSLATEY_SPIN             370
#define IDC_WORLD_UP_SET                370
#define IDC_VIEWPOINT_PREV              372
#define IDC_VIEWPOINT_NEXT              373
#define IDC_ANIMATE_ALL                 374
#define IDC_THANKS                      375
#define IDC_TYPE_SCREEN                 377
#define IDC_TYPE_WORLD                  378
#define IDC_TAB                         378
#define IDC_TYPE_LOCAL                  379
#define IDC_AXIS_X                      380
#define IDC_AXIS_Y                      381
#define IDC_AXIS_Z                      382
#define IDC_UNIFORM                     383
#define IDC_TRACKBALL                   384
#define IDC_SHARE                       385
#define IDC_TFILTER_LINEAR              388
#define IDC_TFILTER                     389
#define IDC_SOFTWARE                    389
#define IDC_EXPAND_IFS                  390
#define IDC_USE_VIDEOMEM                390
#define IDC_BUILD_BSP                   391
#define IDC_USE_D3DCULLING              391
#define IDC_KEEP_INLINES                392
#define IDC_BSP_HEURISTIC               393
#define IDC_SPLIT                       394
#define IDC_MAX_BSP_LEVEL               395
#define IDC_KEEP_LODS                   396
#define IDC_IGNORE_ROUTES               397
#define IDC_BSP_SEARCH_LIMT             398
#define IDC_DEEP                        399
#define IDC_COMPRESS                    399
#define IDC_REMOVE_NAMES                400
#define IDC_EXPAND_FACE_COLOR           401
#define IDC_MIN                         401
#define IDC_MAX                         402
#define IDC_KEEP_PRIMITIVES             402
#define IDC_TILES                       403
#define IDC_LIST                        403
#define IDC_BSP_INLINES                 403
#define IDC_LEVEL                       404
#define IDC_BSP_INLINE_LEVEL            404
#define IDC_TEXT_OGL_NURS_MODE          404
#define IDC_PATH                        405
#define IDC_IFS_ROUND_COORD             405
#define IDC_GL_NURBS_MODE               405
#define IDC_IFS_ROUND_COORD_SCALE       406
#define IDC_BX3D                        407
#define IDC_APPLY_TRANSFORMS            408
#define IDC_SHARE_COORD                 409
#define IDC_WIDTH_SPIN                  1000
#define IDC_WIDTH                       1001
#define IDC_DITHER                      1001
#define IDC_HEIGHT_SPIN                 1002
#define IDC_HIGHLIGHTS                  1002
#define IDC_DRIVER                      1003
#define IDC_PROXY                       1004
#define IDC_FILE                        1004
#define IDC_MODE                        1004
#define IDC_PROXY_BYPASS                1005
#define IDC_TEXTURE_MODE                1005
#define IDC_STIPPLE                     1006
#define IDC_MAX_THREAD                  1006
#define IDC_RADIO1                      1007
#define IDC_DEVICE                      1007
#define IDC_RADIO2                      1008
#define IDC_DXLEVEL                     1008
#define IDC_RADIO3                      1009
#define IDC_ANTIALIAS                   1009
#define IDC_RADIO4                      1010
#define ID_VIEW_PIXELFORMAT             32768
#define ID_PIXFMT_CHOOSE                32769
#define ID_PIXFMT_DESCRIBE              32770
#define ID_PIXFMT_ENUM                  32772
#define ID_CAMERA_RESET                 32773
#define ID_CAMERA_ZOOM                  32777
#define ID_CAMERA_DOLLY_XY              32778
#define ID_CAMERA_ORBIT                 32779
#define ID_CAMERA_PAN                   32780
#define ID_CAMERA_WALK                  32781
#define ID_RENDER_WIREFRAME             32782
#define ID_RENDER_SOLID                 32783
#define ID_RENDER_FLAT                  32784
#define ID_RENDER_GOURAUD               32785
#define ID_CAMERA_SPINAUTO              32786
#define ID_CAMERA_ROLL                  32787
#define ID_RENDER_VERTICES              32789
#define ID_RENDER_LIGHTED               32790
#define ID_RENDER_NORMALS               32791
#define ID_RENDER_OPTIONS_BACKFACECULL  32792
#define ID_RENDER_OPTIONS_2SIDEDLIGHTING 32793
#define ID_RENDER_OPTIONS_LOCALVIEWER   32794
#define ID_RENDER_OPTIONS_ANTIALIASLINES 32795
#define ID_RENDER_TEXTURED              32796
#define ID_RENDER_OPTIONS_LOADTEXTURE   32797
#define ID_RENDER_COLORED               32798
#define ID__LOAD                        32799
#define ID_MATERIAL_EDIT                32800
#define ID_MATERIAL_LOAD                32801
#define ID_MATERIAL_BACKGROUND          32802
#define ID_RENDER_OPTIONS_REVCULLING    32803
#define ID_MATERIAL_TEXTUREOPTIONS      32804
#define ID_MATERIAL_TEXTURE_OPTIONS     32805
#define ID_MATERIAL_BACKGROUNDOPTIONS   32806
#define ID_MATERIAL_BACKGROUND_OPTIONS  32807
#define ID_TOOLS_DEFORM                 32808
#define ID_TOOLS_DEFORM_SPHERE          32809
#define ID_DEFORM_SPHERE                32810
#define ID_OPTIONS_CONFIG               32811
#define ID_TOOLS_DEFORM_DISABLE         32812
#define ID_OPTIONS_TEST1                32813
#define ID_MATERIAL_FOG                 32814
#define ID_MATERIAL_PARAMETER           32815
#define ID_RENDER_STYLE                 32816
#define ID_FILE_SAVEAS                  32818
#define ID_CAMERA_AUTOSPIN              32819
#define ID_FILE_READ                    32820
#define ID_RENDER_OPTIONS_FLIPOBJECTNORMALS 32821
#define ID_OBJECT_FLIPNORMALS           32822
#define ID_TOOLS_BUILDSHELL             32824
#define ID_TOOLS_BUILD_SHELL            32825
#define ID_TOOLS_TRIANGULATE            32826
#define ID_FILE_NEWFONTLOGO             32827
#define ID_TOOLS_INFO                   32828
#define ID_RENDER_TIME                  32829
#define ID_TOOLS_MORPH                  32830
#define ID_WWW_OPENURL                  32831
#define ID_WWW_ABORTLOAD                32832
#define ID_WWW_OPTIONS                  32833
#define ID_RENDER_BOXES                 32834
#define ID_CAMERA_VIEWPOINTS            32835
#define ID_WWW_LOADALLINLINES           32836
#define ID_CAMERA_FLY                   32837
#define ID_RENDER_NONLIGHTED            32838
#define ID_RENDER_OPTIONS_TRANSPARENCY  32839
#define ID_RENDER_TRANSPARENCY          32840
#define ID_OPTIONS_REGISTERFILETYPES    32841
#define ID_OPTIONS_REGISTER_FILETYPES   32842
#define ID_WWW_RELOAD                   32843
#define ID_RENDER_ANIMATE               32844
#define ID_CAMERA_VIEW_OBJECT           32845
#define ID_EDIT_DELETE                  32846
#define ID_FILE_EXIT                    32848
#define ID_TOOLS_TREE_EDITOR            32849
#define ID_NODE_NEW                     32853
#define ID_NODE_RENAME                  32854
#define ID_NODE_INSERTFILE              32855
#define ID_NODE_SAVEAS                  32856
#define ID_VIEW_REFRESH                 32857
#define ID_NODE_EXPANDFIELDS            32858
#define ID_FIELD_EDIT                   32859
#define ID_VIEW_TREE                    32860
#define ID_VIEW_DEFED_OBJECTS           32861
#define ID_NODE_CONVERTTO_INDEXEDFACESET 32863
#define ID_NODE_CONVERTTO_SEPARATOR     32864
#define ID_VIEW_REFERENCES              32865
#define ID_FIELD_EDIT_AS_FILENAME       32866
#define ID_FIELD_EDIT_AS_COLOR          32867
#define ID_FIELD_DRAG                   32868
#define ID_OPTIONS_WRITEINLINES         32869
#define ID_OPTIONS_UPDATEINLINEBOUNDINGBOXES 32870
#define ID_NODE_EXPANDINLINES           32871
#define IDD_CAMERA_RELATIVE             32872
#define ID_NODE_OPERATIONS_OPTIMIZETREE 32873
#define ID_NODE_OPERATIONS_SPATIALSORT  32874
#define ID_NODE_OPERATIONS_COMBINE      32875
#define ID_NODE_OPERATIONS_LODEDIT      32877
#define ID_FILE_RENDER                  32878
#define ID_VIEW_URL_BAR                 32879
#define ID_OPTIONS_GLINFO               32880
#define ID_OPTIONS_GL_INFO              32881
#define ID_MATERIAL_BACKGROUNDIMAGE     32882
#define ID_FILE_RENDER_TO_FILE          32883
#define ID_MATERIAL_BACKGROUND_IMAGE    32884
#define ID_FIELD_EDIT_AS_STRING         32885
#define ID_EDIT_PASTE_into              32886
#define ID_MATERIAL_BACKGROUND_RESET    32887
#define ID_OPTIONS_DIRECT3D             32888
#define ID_OPTIONS_FULLSCRENN           32889
#define ID_OPTIONS_FULLSCREEN           32890
#define ID_CAMERA_ANIMATE_VIEWPOINTS    32891
#define ID_EDIT_PASTE_COPY              32892
#define ID_POPUP_NEXTVIEWPOINT          32893
#define ID_CAMERA_VIEWPOINT_NEXT        32894
#define ID_CAMERA_VIEWPOINT_PREV        32895
#define ID_NODE_CONVERTTO_ANCHOR        32896
#define ID_NODE_CONVERTTO_TRANSFORM     32897
#define ID_CAMERA_SEEKTO                32898
#define ID_TOOLS_TRANSFORM              32899
#define ID_CAMERA_NONE                  32900
#define ID_CAMERA_HEADLIGHT             32901
#define ID_POPUP_FOLLOWOBJECT           32902
#define ID_CAMERA_FOLLOW_OBJECT         32903
#define ID_CAMERA_COLLISION             32904
#define ID_NODE_OPERATIONS              32905
#define ID_NODE_OPERATIONS_UPDATEBBOX   32906
#define ID_NODE_EXPANDBBOX              32907
#define ID_NODE_UPDATE_BBOX             32908
#define ID_NODE_COMBINE                 32909
#define ID_NODE_TRANSFORM               32910
#define ID_NODE_NORMALIZE               32911
#define ID_NODE_OPTIMIZE                32913
#define ID_TOOLS_OPTIMIZE               32914
#define ID_CAMERA_JUMPTO                32915
#define ID_RENDER_SOUND                 32916
#define ID_SETTINGS_OPTIMIZER           32917
#define ID_OPTIONS_SHOWAVATAR           32918
#define ID_CAMERA_GRAVITY               32919
#define ID_VIEWPOINT_0                  32920
#define ID_VIEWPOINT_1                  32921
#define ID_VIEWPOINT_2                  32922
#define ID_VIEWPOINT_3                  32923
#define ID_VIEWPOINT_4                  32924
#define ID_VIEWPOINT_5                  32925
#define ID_VIEWPOINT_6                  32926
#define ID_VIEWPOINT_7                  32927
#define ID_VIEWPOINT_8                  32928
#define ID_VIEWPOINT_9                  32929
#define ID_VIEWPOINT_10                 32930
#define ID_VIEWPOINT_11                 32931
#define ID_VIEWPOINT_12                 32932
#define ID_VIEWPOINT_13                 32933
#define ID_VIEWPOINT_14                 32934
#define ID_VIEWPOINT_15                 32935
#define ID_VIEWPOINT_16                 32936
#define ID_VIEWPOINT_17                 32937
#define ID_VIEWPOINT_18                 32938
#define ID_VIEWPOINT_19                 32939
#define ID_DRIVER_0                     32950
#define ID_DRIVER_1                     32951
#define ID_DRIVER_2                     32952
#define ID_DRIVER_3                     32953
#define ID_DRIVER_4                     32954
#define ID_DRIVER_5                     32955
#define ID_DRIVER_6                     32956
#define ID_DRIVER_7                     32957
#define ID_DRIVER_8                     32958
#define ID_DRIVER_9                     32959
#define ID_POPUP_VIEWPOINTS_DUMMY1      32970
#define ID_NODE_CONVEXHUL               32971
#define ID_NODE_CONVEXHULL              32972
#define ID_TOOLS_METAVERSE              32973
#define ID_TOOLS_LIBRARY                32974
#define ID_NODE_CHECK                   32975
#define ID_OPTIONS_PREFERNCES           32976
#define ID_OPTIONS_PREFERENCES          32977
#define ID_TOOLS_VRML2_CON              32978
#define IDS_VERTEX                      61204
#define IDS_EDGE                        61205
#define IDS_FACE                        61206
#define IDS_NORMAL                      61207
#define IDS_DRAWING_STYLE               61208
#define IDS_BBOX                        61209

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32979
#define _APS_NEXT_CONTROL_VALUE         406
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
